### ISSUE TITLE
spring cloud alibaba dubbo with hessian protocal error

### ISSUE THREAD

**Issue by lloverj** [alibaba/spring-cloud-alibaba#1037]
when i use spring cloud alibaba dubbo with hessian protocal,get error is :
it looks is a bug ,because I use nomral way，not cloud like nacos:xxx.xxx.xxx.xxx:8848，it works 。

consumer：
```

Caused by: com.caucho.hessian.client.HessianConnectionException: 500: java.io.IOException: Server returned HTTP response code: 500 for URL: http://10.10.xx.xx:18888?anyhost=true&application=demo&bean.name=ServiceBean:com.ky.service.DemoService&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.ky.map.tra.cloud.track.service.DemoService&lazy=false&methods=demo&pid=11700&qos.enable=false&register=true&register.ip=10.10.xx.xx&release=2.7.3&remote.application=tra-cloud-provider&server=jetty&side=consumer&sticky=false&timeout=2000&timestamp=1572676328269
	at com.caucho.hessian.client.HessianURLConnection.sendRequest(HessianURLConnection.java:145)
	at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:296)
	at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:171)
	at com.sun.proxy.$Proxy142.demo(Unknown Source)
	at org.apache.dubbo.common.bytecode.Wrapper6.invokeMethod(Wrapper6.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:104)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:155)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:52)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)

```

provider：

```
> - dubbo:
> -   scan:
> -     base-packages: com.xxx
> -   protocols:
> -     hessian:
> -       name: hessian
> -       port: 18888
> -       server: jetty
> -   registry:
> -     address: spring-cloud://localhost
> -   application:
> -     qos:
> -       enable: false
> -   provider:
> -     timeout: 10000
```

```
javax.servlet.ServletException: java.lang.NullPointerException
	at org.apache.dubbo.rpc.protocol.hessian.HessianProtocol$HessianHandler.handle(HessianProtocol.java:196)
	at org.apache.dubbo.remoting.http.servlet.DispatcherServlet.service(DispatcherServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
```

**Comment by albert-lu** [comment]
Ｉ　ｇｏｔ　ｔｈｅ　ｓａｍｅ　ｉｓｓｕｅ

**Comment by xianwei** [comment]
+1
