### ISSUE TITLE
dubbo 无法正常使用，nacos 版本 1.2.1  远程调用不定时出现连接异常问题，远程调用不同，必须要生产者和消费者重启才能正常

### ISSUE THREAD

**Issue by itlidaye** [alibaba/spring-cloud-alibaba#1312]
`maven 配置信息

<spring-cloud.version>Hoxton.RELEASE</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>

 <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.2.6.RELEASE</version>
                <type>pom</type>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
         <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
               
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
               
            </dependency>

dubbo 配置

dubbo:
    scan:
        # dubbo 服务扫描基准包
        base-packages: com.aaa.mall
    protocol:
        # dubbo 协议
        name: dubbo
        serialization: fastjson
        # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
        port: -1
        heartbeat: 5000
    consumer:
        lazy: true
        check: false
        reconnect: true
        timeout: 15000
    ##registry:
    # 挂载到 Spring Cloud 注册中心
     ##   address: spring-cloud://192.168.0.171
    cloud:
        interval: 1000
        retry-count: 1`

异常信息

o.a.d.r.e.s.header.ReconnectTimerTask    :  [DUBBO] Initial connection to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [192.168.0.171:0 -> /192.168.0.171:20890]], dubbo version: 2.7.3, current host: 192.168.0.171
2020-04-02 15:36:13.652 ERROR 10860 --- [eCheck-thread-1] o.a.d.r.e.s.header.ReconnectTimerTask    :  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [192.168.0.171:0 -> /192.168.0.171:20890]], dubbo version: 2.7.3, current host: 192.168.0.171

org.apache.dubbo.remoting.RemotingException: client(url: dubbo://192.168.0.171:20890/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=shoppingCart-server&bind.ip=192.168.0.171&bind.port=20890&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=member-server&heartbeat=5000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&lazy=false&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=10860&qos.enable=false&reconnect=true&register.ip=192.168.0.171&release=2.7.4.1&remote.application=member-server&revision=2.2.0.RELEASE&serialization=fastjson&side=consumer&sticky=false&timeout=15000&timestamp=1585793653858&version=1.0.0) failed to connect to server /192.168.0.171:20890, error message is:Connection refused: /192.168.0.171:20890
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:166) ~[dubbo-2.7.3.jar!/:2.7.3]
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:190) ~[dubbo-2.7.3.jar!/:2.7.3]
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:246) ~[dubbo-2.7.3.jar!/:2.7.3]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:155) ~[dubbo-2.7.3.jar!/:2.7.3]
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49) ~[dubbo-2.7.3.jar!/:2.7.3]
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87) [dubbo-2.7.3.jar!/:2.7.3]
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648) [dubbo-2.7.3.jar!/:2.7.3]
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727) [dubbo-2.7.3.jar!/:2.7.3]
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449) [dubbo-2.7.3.jar!/:2.7.3]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /192.168.0.171:20890
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.36.Final.jar!/:4.1.36.Final]
	... 1 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 12 common frames omitted

**Comment by lcg72** [comment]
参见 #1259，已经修复，你打下补丁看看

**Comment by itlidaye** [comment]
有发布新版本嘛，这个补丁不知道怎么操作

**Comment by lcg72** [comment]
> 有发布新版本嘛，这个补丁不知道怎么操作

参考https://www.cnblogs.com/jaylen-ljl/p/10671721.html

另外2.2.0对应的dubbo版本是2.7.4.1，你怎么是2.7.3？

**Comment by itlidaye** [comment]
补丁是需要 把代码下载下来本地编译是嘛

**Comment by lcg72** [comment]
1259有打好的补丁，要是不会弄，你参考1259中测试工程，把补丁代码复制到你工程中

**Comment by lcg72** [comment]
更新了测试工程https://github.com/lcg72/testAlibaba
serviceA使用补丁方式，serviceB使用代码覆盖方式，
你选一种就行。

**Comment by mercyblitz** [comment]
Please build the lastest code from the master branch.

**Comment by w8l8g8** [comment]
> 
没看出AB有什么区别呢
