### ISSUE TITLE
nacos-server在Linux环境下运行，nacos客户端读取配置一直超时

### ISSUE THREAD

**Issue by Thinkingcao** [alibaba/spring-cloud-alibaba#1358]
2020-04-13 17:37:11.731 ERROR [jiuyv-gateway,,,] 12928 --- [252.80.192_8848] c.a.n.c.config.http.ServerHttpAgent      : [NACOS SocketTimeoutException httpPost] currentServerAddr: http://130.252.80.192:8848， err : Read timed out
2020-04-13 17:37:11.732 ERROR [jiuyv-gateway,,,] 12928 --- [252.80.192_8848] c.a.n.c.config.http.ServerHttpAgent      : no available server, currentServerAddr : http://130.252.80.192:8848
2020-04-13 17:37:11.744 ERROR [jiuyv-gateway,,,] 12928 --- [252.80.192_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-130.252.80.192_8848] [check-update] get changed dataId exception

java.net.ConnectException: no available server, currentServerAddr : http://130.252.80.192:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170) ~[nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:377) [nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:352) [nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:512) [nacos-client-1.1.4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by Thinkingcao** [comment]
已有相同的ISSUE
