### ISSUE TITLE
nacos-server在Linux服务器下运行时，一直会报超时异常 Read timed out

### ISSUE THREAD

**Issue by Thinkingcao** [alibaba/spring-cloud-alibaba#1359]
2020-04-13 17:37:11.731 ERROR [jiuyv-gateway,,,] 12928 --- [252.80.192_8848] c.a.n.c.config.http.ServerHttpAgent : [NACOS SocketTimeoutException httpPost] currentServerAddr: http://130.252.80.192:8848， err : Read timed out
2020-04-13 17:37:11.732 ERROR [jiuyv-gateway,,,] 12928 --- [252.80.192_8848] c.a.n.c.config.http.ServerHttpAgent : no available server, currentServerAddr : http://130.252.80.192:8848
2020-04-13 17:37:11.744 ERROR [jiuyv-gateway,,,] 12928 --- [252.80.192_8848] c.a.n.client.config.impl.ClientWorker : [fixed-130.252.80.192_8848] [check-update] get changed dataId exception

java.net.ConnectException: no available server, currentServerAddr : http://130.252.80.192:8848
at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170) ~[nacos-client-1.1.4.jar:na]
at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.1.4.jar:na]
at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:377) [nacos-client-1.1.4.jar:na]
at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:352) [nacos-client-1.1.4.jar:na]
at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:512) [nacos-client-1.1.4.jar:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_25]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_25]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by wujincheng2333** [comment]
这是我遇到的，不知道你是不是这个原因=。=
这个异常估计是网络波动了，没什么影响。nacos监听文件是使用http长轮询，默认30秒，服务端上如果配置没有更新就会在29.5秒后返回响应客户端，不超过30秒，防止http client超时。但可能由于某种原因导致没能在500毫秒内响应，所以直接报超时。

**Comment by Thinkingcao** [comment]
> 这是我遇到的，不知道你是不是这个原因=。=
> 这个异常估计是网络波动了，没什么影响。nacos监听文件是使用http长轮询，默认30秒，服务端上如果配置没有更新就会在29.5秒后返回响应客户端，不超过30秒，防止http client超时。但可能由于某种原因导致没能在500毫秒内响应，所以直接报超时。

没错，我的nacos-server所部属的服务器网络存在点延迟波动，请问你有对这个采取解决措施吗？

**Comment by wujincheng2333** [comment]
> > 这是我遇到的，不知道你是不是这个原因=。=
> > 这个异常估计是网络波动了，没什么影响。nacos监听文件是使用http长轮询，默认30秒，服务端上如果配置没有更新就会在29.5秒后返回响应客户端，不超过30秒，防止http client超时。但可能由于某种原因导致没能在500毫秒内响应，所以直接报超时。
> 
> 没错，我的nacos-server所部属的服务器网络存在点延迟波动，请问你有对这个采取解决措施吗？

我这边都是走内网的，线上内网很少出现这种问题。不过我改了nacos-server（1.1.4）的源码，让它在29秒的时候返回。其实这个应该影响不大，超时之后又会重新发起请求监听。

**Comment by Thinkingcao** [comment]
> > > 这是我遇到的，不知道你是不是这个原因=。=
> > > 这个异常估计是网络波动了，没什么影响。nacos监听文件是使用http长轮询，默认30秒，服务端上如果配置没有更新就会在29.5秒后返回响应客户端，不超过30秒，防止http client超时。但可能由于某种原因导致没能在500毫秒内响应，所以直接报超时。
> > 
> > 
> > 没错，我的nacos-server所部属的服务器网络存在点延迟波动，请问你有对这个采取解决措施吗？
> 
> 我这边都是走内网的，线上内网很少出现这种问题。不过我改了nacos-server（1.1.4）的源码，让它在29秒的时候返回。其实这个应该影响不大，超时之后又会重新发起请求监听。

我的解决方式是ncaos-client升级到1.2.0版本，nacos-server1.2.1，暂时解决这个问题
      
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.2.0</version>
        </dependency>

**Comment by Thinkingcao** [comment]
> > > > 这是我遇到的，不知道你是不是这个原因=。=
> > > > 这个异常估计是网络波动了，没什么影响。nacos监听文件是使用http长轮询，默认30秒，服务端上如果配置没有更新就会在29.5秒后返回响应客户端，不超过30秒，防止http client超时。但可能由于某种原因导致没能在500毫秒内响应，所以直接报超时。
> > > 
> > > 
> > > 没错，我的nacos-server所部属的服务器网络存在点延迟波动，请问你有对这个采取解决措施吗？
> > 
> > 
> > 我这边都是走内网的，线上内网很少出现这种问题。不过我改了nacos-server（1.1.4）的源码，让它在29秒的时候返回。其实这个应该影响不大，超时之后又会重新发起请求监听。
> 
> 我的解决方式是ncaos-client升级到1.2.0版本，nacos-server1.2.1，暂时解决这个问题

![image](https://user-images.githubusercontent.com/23623121/79310439-88e2a780-7f2e-11ea-80ab-bad32143d0db.png)

**Comment by wujincheng2333** [comment]
> > > > > 这是我遇到的，不知道你是不是这个原因=。=
> > > > > 这个异常估计是网络波动了，没什么影响。nacos监听文件是使用http长轮询，默认30秒，服务端上如果配置没有更新就会在29.5秒后返回响应客户端，不超过30秒，防止http client超时。但可能由于某种原因导致没能在500毫秒内响应，所以直接报超时。
> > > > 
> > > > 
> > > > 没错，我的nacos-server所部属的服务器网络存在点延迟波动，请问你有对这个采取解决措施吗？
> > > 
> > > 
> > > 我这边都是走内网的，线上内网很少出现这种问题。不过我改了nacos-server（1.1.4）的源码，让它在29秒的时候返回。其实这个应该影响不大，超时之后又会重新发起请求监听。
> > 
> > 
> > 我的解决方式是ncaos-client升级到1.2.0版本，nacos-server1.2.1，暂时解决这个问题
> 
> ![image](https://user-images.githubusercontent.com/23623121/79310439-88e2a780-7f2e-11ea-80ab-bad32143d0db.png)

我已经在线上跑了，不敢随意更新=。=   1.1.4版本感觉有时候会随意踢服务掉线，但实际服务还在运行。。你有遇到吗

**Comment by fulintang** [comment]
我也遇到这个问题，`2022-08-30 04:14:12.322 [com.alibaba.nacos.client.config.security.updater] ERROR com.alibaba.nacos.client.security.SecurityProxy:156 - [SecurityProxy] login http request failed url: http://parkcloud-nacos-prod:8848/nacos/v1/auth/users/login, params: {username=nacos}, bodyMap: {password=xxx}, errorMsg: Read timed out
`
我是用的容器部署的nacos，然后他就开始一直报这个错
