### ISSUE TITLE
Failed to stop bean 'inputBindingLifecycle'

### ISSUE THREAD

**Issue by rainsoft** [alibaba/spring-cloud-alibaba#1420]
**Which Component**
spring-cloud-starter-stream-rocketmq

**Describe the bug**
When I stop my application with spring-cloud-starter-stream-rocketmq, I receive an exception as below:

```
2020-05-03 19:09:22.225  WARN 24709 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'inputBindingLifecycle'

java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82) ~[na:1.8.0_212]
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239) ~[na:1.8.0_212]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.removeShutdownHook(AsyncTraceDispatcher.java:210) ~[rocketmq-client-4.4.0.jar:4.4.0]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.shutdown(AsyncTraceDispatcher.java:183) ~[rocketmq-client-4.4.0.jar:4.4.0]
	at org.apache.rocketmq.client.consumer.DefaultMQPushConsumer.shutdown(DefaultMQPushConsumer.java:598) ~[rocketmq-client-4.4.0.jar:4.4.0]
	at com.alibaba.cloud.stream.binder.rocketmq.consuming.RocketMQListenerBindingContainer.stop(RocketMQListenerBindingContainer.java:193) ~[spring-cloud-starter-stream-rocketmq-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at com.alibaba.cloud.stream.binder.rocketmq.integration.RocketMQInboundChannelAdapter.doStop(RocketMQInboundChannelAdapter.java:129) ~[spring-cloud-starter-stream-rocketmq-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.integration.endpoint.AbstractEndpoint.stop(AbstractEndpoint.java:173) ~[spring-integration-core-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinding.stop(DefaultBinding.java:135) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:332) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindInputs(AbstractBindableProxyFactory.java:156) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:66) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_212]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1021) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
```

**Additional context**
 MacOS  、Java8 、 Version 2.2.1.RELEASE

**Comment by casparcao** [comment]
我也是每次遇到这个异常，你解决了嘛？

**Comment by yangyang0507** [comment]
same problem

**Comment by xiaoyaojian** [comment]
同样的问题...

**Comment by FalconIA** [comment]
Same issue.

**Comment by hangzhou492** [comment]
up +1

**Comment by swmmm** [comment]
是rocketmq消息轨迹功能导致的 需要配置rocketmq.binder.enable-msg-trace: false   默认是true
