### ISSUE TITLE
关闭服务时spring-cloud-stream-binder-rockermq报java.lang.IllegalStateException: Shutdown in progress

### ISSUE THREAD

**Issue by casparcao** [alibaba/spring-cloud-alibaba#1524]
**Which Component**
spring-cloud-stream-binder-rockermq

**Describe the bug**
当关闭应用服务时（kill ${pid}），日志（控制台）每次都报java.lang.IllegalStateException: Shutdown in progress的异常，并且要等待大约1分钟超时后才能完成服务的关闭。

**To Reproduce**
1. 运行服务 java -jar xxx.jar 
2. 待服务启动完成
3. 执行 Ctrl+C或者 kill 命令
4. 报java.lang.IllegalStateException: Shutdown in progress异常，且阻塞关闭过程。

**Expected behavior**
正常执行完 shutdownhook，服务关闭

**Screenshots**
`2020-06-11 16:13:42.455  INFO [user,,,] 9488 --- [extShutdownHook] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application USER with eureka with status DOWN
2020-06-11 16:13:42.466  INFO [user,,,] 9488 --- [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[112.124.141.191:80] result: true
2020-06-11 16:13:42.469  INFO [user,,,] 9488 --- [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[112.124.141.191:80] result: true
2020-06-11 16:13:42.475  WARN [user,,,] 9488 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'outputBindingLifecycle'

java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82) ~[na:1.8.0_212]
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239) ~[na:1.8.0_212]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.removeShutdownHook(AsyncTraceDispatcher.java:210) ~[rocketmq-client-4.4.0.jar:4.4.0]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.shutdown(AsyncTraceDispatcher.java:183) ~[rocketmq-client-4.4.0.jar:4.4.0]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.shutdown(DefaultMQProducer.java:248) ~[rocketmq-client-4.4.0.jar:4.4.0]
	at org.apache.rocketmq.spring.core.RocketMQTemplate.destroy(RocketMQTemplate.java:496) ~[rocketmq-spring-boot-2.0.2.jar:2.0.2]
	at com.alibaba.cloud.stream.binder.rocketmq.integration.RocketMQMessageHandler.stop(RocketMQMessageHandler.java:143) ~[spring-cloud-stream-binder-rocketmq-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinding.stop(DefaultBinding.java:135) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.unbindProducers(BindingService.java:346) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindOutputs(AbstractBindableProxyFactory.java:174) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStopWithBindable(OutputBindingLifecycle.java:66) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_212]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.stop(OutputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.stop(OutputBindingLifecycle.java:34) ~[spring-cloud-stream-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1021) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]

2020-06-11 16:14:10.016  WARN [user,,,] 9488 --- [ngPollService-1] c.c.f.a.i.RemoteConfigLongPollService    : Long polling failed, will retry in 64 seconds. appId: user, cluster: default, namespaces: application, long polling url: null, reason: Get config services failed from http://dev-apollo-config:8700/services/config?appId=user&ip=172.168.1.142 [Cause: Could not complete get operation [Cause: dev-apollo-config]]
2020-06-11 16:14:12.478  INFO [user,,,] 9488 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to shut down 1 bean with phase value -2147482648 within timeout of 30000: [outputBindingLifecycle]
2020-06-11 16:14:12.479  INFO [user,,,] 9488 --- [extShutdownHook] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2020-06-11 16:14:12.480  INFO [user,,,] 9488 --- [extShutdownHook] o.s.i.channel.PublishSubscribeChannel    : Channel 'application-1.errorChannel' has 0 subscriber(s).
2020-06-11 16:14:12.480  INFO [user,,,] 9488 --- [extShutdownHook] o.s.i.endpoint.EventDrivenConsumer       : stopped bean '_org.springframework.integration.errorLogger'
2020-06-11 16:14:12.514  INFO [user,,,] 9488 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2020-06-11 16:14:12.515  INFO [user,,,] 9488 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-06-11 16:14:13.290  INFO [user,,,] 9488 --- [extShutdownHook] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
2020-06-11 16:14:13.329  INFO [user,,,] 9488 --- [extShutdownHook] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
2020-06-11 16:14:13.332  INFO [user,,,] 9488 --- [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[112.124.141.191:80] result: true
2020-06-11 16:14:13.332  INFO [user,,,] 9488 --- [extShutdownHook] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2020-06-11 16:14:13.350  INFO [user,,,] 9488 --- [extShutdownHook] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
`

**Comment by damaozsc** [comment]
遇到同样的问题，希望尽快修复

**Comment by for2cold** [comment]
@casparcao hi~ 请问你解决这个问题了吗，遇到同样的问题，2.2.3.RELEASE版本

**Comment by swmmm** [comment]
是rocketmq消息轨迹功能导致的 需要配置rocketmq.binder.enable-msg-trace: false   默认是true

**Comment by for2cold** [comment]
> 是rocketmq消息轨迹功能导致的 需要配置rocketmq.binder.enable-msg-trace: false 默认是true

感谢~

**Comment by casparcao** [comment]
> 是rocketmq消息轨迹功能导致的 需要配置rocketmq.binder.enable-msg-trace: false 默认是true

谢谢，方便告知为什么吗？
