### ISSUE TITLE
About spring-cloud-starter-alibaba-nacos-config CPU 100%

### ISSUE THREAD

**Issue by JackSlamDunk** [alibaba/spring-cloud-alibaba#1577]
CPU is up to 100% after a period of time
After debugging by visualVW, I found that there are many threads.
"com.alibaba.nacos.client.Worker.longPolling.fixed-10.248.224.252_8848"
This problem does not occur when I disable the dependency. This should be the main reason for the high CPU usage. Is there any way to solve this problem?

你好，我现在使用的是spring-cloud-starter-alibaba-nacos-config 2.2.1RELEASE版本
压测一段时间后，CPU高涨。Jstack线程列表中，出现了很多
com.alibaba.nacos.client.Worker.longPolling.fixed-***,出现这种原因有哪些？

"com.alibaba.nacos.client.Worker.longPolling.fixed-10.248.224.252_8848" #40 daemon prio=5 os_prio=0 tid=0x00007f0aec003000 nid=0x4b6a waiting on condition [0x00007f0b569a6000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000008649a468> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"com.alibaba.nacos.naming.beat.sender" #39 daemon prio=5 os_prio=0 tid=0x00007f0ae8156800 nid=0x4b68 waiting on condition [0x00007f0b56aa7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000086df7df0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"com.alibaba.nacos.client.Worker.longPolling.fixed-10.248.224.252_8848" #37 daemon prio=5 os_prio=0 tid=0x00007f0aec001000 nid=0x4b66 waiting on condition [0x00007f0b56ba8000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000008649a468> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by metaphysical-road** [comment]
在ClientWorker这个Longpolling类中，会通过如下代码开启一个定时线程
executorService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors(), new ThreadFactory() {
            @Override
            public Thread newThread(Runnable r) {
                Thread t = new Thread(r);
                t.setName("com.alibaba.nacos.client.Worker.longPolling." + agent.getName());
                t.setDaemon(true);
                return t;
            }
        });

正常情况只会通过一个线程executorService.execute(this);  但是如果发生异常，会直接开启定时执行 executorService.schedule(this, taskPenaltyTime, TimeUnit.MILLISECONDS); 好像也没看到关闭这个定时线程的方法逻辑。

**Comment by amao12580** [comment]
排查分析：使用maven helper查询一下druid依赖包版本，确保高于1.1.5

**Comment by amao12580** [comment]
参考：https://www.cnblogs.com/FlyAway2013/p/10818589.html

**Comment by JackSlamDunk** [comment]
> 排查分析：使用maven helper查询一下druid依赖包版本，确保高于1.1.5

**Comment by JackSlamDunk** [comment]
>

**Comment by JackSlamDunk** [comment]
> 排查分析：使用maven helper查询一下druid依赖包版本，确保高于1.1.5

没有引入druid数据源

**Comment by JackSlamDunk** [comment]
> 在ClientWorker这个Longpolling类中，会通过如下代码开启一个定时线程
> executorService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors(), new ThreadFactory() {
> @override
> public Thread newThread(Runnable r) {
> Thread t = new Thread(r);
> t.setName("com.alibaba.nacos.client.Worker.longPolling." + agent.getName());
> t.setDaemon(true);
> return t;
> }
> });
> 
> 正常情况只会通过一个线程executorService.execute(this); 但是如果发生异常，会直接开启定时执行 executorService.schedule(this, taskPenaltyTime, TimeUnit.MILLISECONDS); 好像也没看到关闭这个定时线程的方法逻辑。
你指的异常发生是？轮训的时候连接不了nacos?

**Comment by chuntaojun** [comment]
> 在ClientWorker这个Longpolling类中，会通过如下代码开启一个定时线程
> executorService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors(), new ThreadFactory() {
> @override
> public Thread newThread(Runnable r) {
> Thread t = new Thread(r);
> t.setName("com.alibaba.nacos.client.Worker.longPolling." + agent.getName());
> t.setDaemon(true);
> return t;
> }
> });
> 
> 正常情况只会通过一个线程executorService.execute(this); 但是如果发生异常，会直接开启定时执行 executorService.schedule(this, taskPenaltyTime, TimeUnit.MILLISECONDS); 好像也没看到关闭这个定时线程的方法逻辑。

你所说的这个并不是问题的原因，这个不会导致线程不断创建

**Comment by metaphysical-road** [comment]
> > 在ClientWorker这个Longpolling类中，会通过如下代码开启一个定时线程
> > executorService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors(), new ThreadFactory() {
> > @override
> > public Thread newThread(Runnable r) {
> > Thread t = new Thread(r);
> > t.setName("com.alibaba.nacos.client.Worker.longPolling." + agent.getName());
> > t.setDaemon(true);
> > return t;
> > }
> > });
> > 正常情况只会通过一个线程executorService.execute(this); 但是如果发生异常，会直接开启定时执行 executorService.schedule(this, taskPenaltyTime, TimeUnit.MILLISECONDS); 好像也没看到关闭这个定时线程的方法逻辑。
> 
> 你所说的这个并不是问题的原因，这个不会导致线程不断创建

是什么原因，春大神，求正解。

**Comment by yuhuangbin** [comment]
此issue关闭，CPU100%问题向Nacos社区提问。
