### ISSUE TITLE
spring cloud gateway 配置了nacos 的server-addr，但是一直尝试连接本地locahost

### ISSUE THREAD

**Issue by ZhuoSir** [alibaba/spring-cloud-alibaba#1599]
```
server:
  port: 8080
spring:
  application:
    name: spike-gateway
  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
    nacos:
      discovery:
        server-addr: 192.168.182.79:8848
```
上面我明明配置了server-add 为服务器地址的nacos；也成功连上了服务器的nacos；
但是控制台却一直打印本地连接，从服务启动便开始连接本地的nacos地址；

```
2020-07-24 14:48:20.590 ERROR 68812 --- [-localhost_8848] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err : Connection refused
2020-07-24 14:48:20.591 ERROR 68812 --- [-localhost_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-localhost_8848] [check-update] get changed dataId exception

java.net.ConnectException: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:386) [nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:354) [nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:521) [nacos-client-1.2.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

2020-07-24 14:48:20.591 ERROR 68812 --- [-localhost_8848] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.net.ConnectException: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:386) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:354) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:521) ~[nacos-client-1.2.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

```

希望能得到解答，具体是什么原因导致的

**Comment by fangjian0423** [comment]
Spring Boot 应用配置是有优先级的，可以进入 /actuator/env 这个 endpoint 查看配置。

Refer [Spring Boot 常见错误及解决方法](https://www.infoq.cn/article/Bri5Kou8LLy5CpiBSeqy).

**Comment by yuhuangbin** [comment]
你应该是引入了nacos-config的依赖，如果没有使用动态配置那就移出就行了。

**Comment by ZhuoSir** [comment]
> 你应该是引入了nacos-config的依赖，如果没有使用动态配置那就移出就行了。

3Q 解决了。

**Comment by RGaius** [comment]
![image](https://user-images.githubusercontent.com/19511826/91123383-4c3e6e00-e6cf-11ea-8788-3eaa5c24e27c.png)
![image](https://user-images.githubusercontent.com/19511826/91123421-68daa600-e6cf-11ea-89f5-f24717b0c7ea.png)
I have seen that I have no relevant dependence, but there is still this problem.
