### ISSUE TITLE
spring cloud alibaba重复启动服务提供者和消费者出现bug

### ISSUE THREAD

**Issue by teacherblitz** [alibaba/spring-cloud-alibaba#1711]
2020-09-11 16:42:21.779  WARN 21556 --- [yCache-thread-1] o.a.dubbo.registry.nacos.NacosRegistry   :  [DUBBO] Failed to save registry cache file after retrying 3 times, cause: null, dubbo version: 2.7.7, current host: 192.168.137.1

java.nio.channels.OverlappingFileLockException: null
  at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
  at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
  at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
  at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
  at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:180)
  at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:526)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

**Comment by baitly002** [comment]
同问，一样，不过这个ISSUE应该在DUBBO那边提
