### ISSUE TITLE
2.2.2.RELEASE undertow stop shows "Failed to stop bean 'nacosWatch'"

### ISSUE THREAD

**Issue by poem-love** [alibaba/spring-cloud-alibaba#1723]
**Which Component**
2.2.2.RELEASE work with undertow
**Describe the bug**
when stop a project, use tomcat will show no error.
when change to undertow , it will show
```properties
 WARN  o.s.c.s.DefaultLifecycleProcessor - Failed to stop bean 'nacosWatch'
java.lang.NullPointerException: null
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames(ServletContextImpl.java:430) ~[undertow-servlet-2.1.3.Final.jar:2.1.3.Final]
	at org.springframework.web.context.support.ServletContextPropertySource.getPropertyNames(ServletContextPropertySource.java:41) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:103) ~[spring-context-support-1.0.9.jar:na]
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:56) ~[spring-context-support-1.0.9.jar:na]
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.enrichNacosDiscoveryProperties(NacosDiscoveryProperties.java:610) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.getNacosProperties(NacosDiscoveryProperties.java:604) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:140) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:81) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1022) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:979) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.admin.SpringApplicationAdminMXBeanRegistrar$SpringApplicationAdmin.shutdown(SpringApplicationAdminMXBeanRegistrar.java:160) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) [na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) [na:1.8.0_101]
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193) [na:1.8.0_101]
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175) [na:1.8.0_101]
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117) [na:1.8.0_101]
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54) [na:1.8.0_101]
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237) [na:1.8.0_101]
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138) [na:1.8.0_101]
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252) [na:1.8.0_101]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_101]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_101]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468) [na:1.8.0_101]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) [na:1.8.0_101]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309) [na:1.8.0_101]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401) [na:1.8.0_101]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) [na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324) [na:1.8.0_101]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) [na:1.8.0_101]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) [na:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_101]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) [na:1.8.0_101]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568) [na:1.8.0_101]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826) [na:1.8.0_101]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683) [na:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_101]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```

**Additional context**
windows java8, spring cloud Hoxton SR8, version 2.2.2 nacos 1.3.2 spring boot 2.3.3

**Comment by yuhuangbin** [comment]
@poem-love 可以提供一个简单的示例项目复现一下吗？

**Comment by poem-love** [comment]
pom.xml 引入如下, eclipse点关闭会报错
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.3.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>com.test</groupId>
	<artifactId>test</artifactId>
	<version>1.0.0</version>
	<name>Order-2</name>
	<description>order</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
		<spring-cloud-alibaba.version>2.2.2.RELEASE</spring-cloud-alibaba.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
				<dependency>
				<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>${spring-cloud-alibaba.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
`

改成图片上的配置就正常
![e20200914172449](https://user-images.githubusercontent.com/62980541/93068695-6b696380-f6af-11ea-864e-b3b2882e1c1b.png)

**Comment by matevip** [comment]
### 我这里也是相同的问题，报错信息如下：
~~~java
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:04.380 INFO 30479 [] [SpringContextShutdownHook] io.undertow stopping server: Undertow - 2.1.3.Final
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:04.383 INFO 30479 [] [SpringContextShutdownHook] io.undertow.servlet Destroying Spring FrameworkServlet 'dispatcherServlet'
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:04.386 WARN 30479 [] [SpringContextShutdownHook] org.springframework.context.support.DefaultLifecycleProcessor Failed to stop bean 'nacosWatch'

java.lang.NullPointerException: null
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames(ServletContextImpl.java:430)
	at org.springframework.web.context.support.ServletContextPropertySource.getPropertyNames(ServletContextPropertySource.java:41)
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:103)
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:56)
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.enrichNacosDiscoveryProperties(NacosDiscoveryProperties.java:610)
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.getNacosProperties(NacosDiscoveryProperties.java:604)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:140)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:81)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210)
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1022)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949)
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:34.391 INFO 30479 [] [SpringContextShutdownHook] org.springframework.context.support.DefaultLifecycleProcessor Failed to shut down 1 bean with phase value 0 within timeout of 30000ms: [nacosWatch]
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:34.404 INFO 30479 [] [SpringContextShutdownHook] com.alicp.jetcache.support.DefaultMetricsManager cache stat canceled
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:34.406 INFO 30479 [] [SpringContextShutdownHook] org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor Shutting down ExecutorService 'applicationTaskExecutor'
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:34.408 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.cloud.nacos.registry.NacosServiceRegistry De-registering from Nacos Server now...
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:34.408 WARN 30479 [] [SpringContextShutdownHook] org.springframework.context.annotation.CommonAnnotationBeanPostProcessor Destroy method on bean with name 'nacosAutoServiceRegistration' threw an exception: java.lang.NullPointerException
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:34.408 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown begin
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:37.417 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown stop
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:37.418 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.core.EventDispatcher do shutdown begin
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:40.427 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.core.EventDispatcher do shutdown stop
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:40.427 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.core.HostReactor do shutdown begin
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:43.438 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.core.PushReceiver do shutdown begin
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.451 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.core.PushReceiver do shutdown stop
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.451 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown begin
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.451 ERROR 30479 [] [com.alibaba.nacos.naming.push.receiver] com.alibaba.nacos.client.naming [NA] error while receiving push data

java.net.SocketException: Socket closed
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.451 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown stop
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.451 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.core.HostReactor do shutdown stop
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.451 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.net.NamingProxy do shutdown begin
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.451 WARN 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming [NamingHttpClientManager] Start destroying NacosRestTemplate
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.452 WARN 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming [NamingHttpClientManager] Destruction of the end
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.452 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.nacos.client.naming com.alibaba.nacos.client.naming.net.NamingProxy do shutdown stop
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.455 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.druid.pool.DruidDataSource {dataSource-1} closing ...
[mate-system:192.168.3.6:20002] 2020-09-15 06:59:46.461 INFO 30479 [] [SpringContextShutdownHook] com.alibaba.druid.pool.DruidDataSource {dataSource-1} closed

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
~~~
### 复现代码样例：
项目开源：[https://github.com/matevip/matecloud](https://github.com/matevip/matecloud)
可以启动mate-uaa或mate-system模块都可以复现。web中间件使用的是undertow

**Comment by ChunMengLu** [comment]
@yuhuangbin @mercyblitz 我这边也有复现这个问题，我阅读了 NacosWatch 的代码，我有个疑问：

https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java#L154

```java
@Override
public void stop() {
	if (this.running.compareAndSet(true, false)) {
		if (this.watchFuture != null) {
			// shutdown current user-thread,
			// then the other daemon-threads will terminate automatic.
			((ThreadPoolTaskScheduler) this.taskScheduler).shutdown();
			this.watchFuture.cancel(true);
		}

		EventListener eventListener = listenerMap.get(buildKey());
		try {
			NamingService namingService = nacosServiceManager
					.getNamingService(properties.getNacosProperties());
			namingService.unsubscribe(properties.getService(), properties.getGroup(),
					Arrays.asList(properties.getClusterName()), eventListener);
		}
		catch (NacosException e) {
			log.error("namingService unsubscribe failed, properties:{}", properties,
					e);
		}
	}
}
```

这里的 unsubscribe 放这里合适么？个人觉得应该放到 bean 销毁或者在上下文onClose的时候更加合适。

**Comment by YingFengYou** [comment]
我也遇见了，难道是undertow容器的问题？io.undertow.servlet.spec.ServletContextImpl
![image](https://user-images.githubusercontent.com/21286619/103597776-f8287d80-4f3b-11eb-8993-94d6fdc60913.png)

**Comment by spidersq** [comment]
此问题依然没有解决
