### ISSUE TITLE
Too many polling timeouts in config-client-request.log

### ISSUE THREAD

**Issue by JohnNiang** [alibaba/spring-cloud-alibaba#1770]
**Which Component**

Nacos Config

**Describe the bug**
Too many polling timeouts in config-client-request.log.

- config-client-request.log

```java
2020-10-07 22:12:52,404|29501|timeout|192.168.0.144|polling|3|221
2020-10-07 22:13:02,382|29500|timeout|192.168.0.139|polling|3|248
2020-10-07 22:13:10,535|29501|timeout|192.168.0.142|polling|3|254
2020-10-07 22:13:14,278|29500|timeout|192.168.0.142|polling|3|245
2020-10-07 22:13:19,108|29500|timeout|192.168.0.139|polling|3|257
2020-10-07 22:13:31,883|29500|timeout|192.168.0.139|polling|3|248
```
- my application log (occurred every minute)

```java
2020-10-07 22:15:29.029 ERROR 132327 --- [0c-4ef52e0a68e0] c.a.n.c.config.http.ServerHttpAgent      : [NACOS SocketTimeoutException httpPost] currentServerAddr: http://192.168.0.140:8848， err : Read timed out
2020-10-07 22:15:29.029 ERROR 132327 --- [0c-4ef52e0a68e0] c.a.n.c.config.http.ServerHttpAgent      : no available server, currentServerAddr : http://192.168.0.140:8848
2020-10-07 22:15:29.032 ERROR 132327 --- [0c-4ef52e0a68e0] c.a.n.client.config.impl.ClientWorker    : [fixed-192.168.0.140_8848-826ae2ff-3748-4075-8e0c-4ef52e0a68e0] [check-update] get changed dataId exception

java.net.ConnectException: no available server, currentServerAddr : http://192.168.0.140:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:386) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:354) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:521) ~[nacos-client-1.2.1.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-10-07 22:15:29.033 ERROR 132327 --- [0c-4ef52e0a68e0] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.net.ConnectException: no available server, currentServerAddr : http://192.168.0.140:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:386) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:354) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:521) ~[nacos-client-1.2.1.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**To Reproduce**

I don't known how to reproduce that scene, but I found that the error may be caused by `com.alibaba.nacos.config.server.controller.ListenerController#getAllSubClientConfigByIp` -> `com.alibaba.nacos.config.server.service.ConfigSubService#getCollectSampleResultByIp`.

**Expected behavior**

Fail fast or set timeout with infinite.

**Additional context**

- OS: 5.8.11-1-MANJARO
- JDK: openjdk version "11.0.8" 2020-07-14
- Nacos client version: 1.2.1
- Nacos server: 1.3.1 standlone

**Comment by yuhuangbin** [comment]
move this issue to [Nacos](https://github.com/alibaba/nacos).

**Comment by JohnNiang** [comment]
Moved to https://github.com/alibaba/nacos/issues/3958 .
