### ISSUE TITLE
spring-cloud-alibaba 启动报错 java.lang.ClassNotFoundException: org.apache.dubbo.config.spring.util.PropertySourcesUtils

### ISSUE THREAD

**Issue by Eldon-Han** [alibaba/spring-cloud-alibaba#1782]
spring-cloud-alibaba  run error
13:53:05.411 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoClassDefFoundError: org/apache/dubbo/config/spring/util/PropertySourcesUtils
	at com.alibaba.cloud.dubbo.env.DubboNonWebApplicationEnvironmentPostProcessor.getRestPortFromProtocolsProperties(DubboNonWebApplicationEnvironmentPostProcessor.java:152)
	at com.alibaba.cloud.dubbo.env.DubboNonWebApplicationEnvironmentPostProcessor.resetServerPort(DubboNonWebApplicationEnvironmentPostProcessor.java:132)
	at com.alibaba.cloud.dubbo.env.DubboNonWebApplicationEnvironmentPostProcessor.createDefaultProperties(DubboNonWebApplicationEnvironmentPostProcessor.java:109)
	at com.alibaba.cloud.dubbo.env.DubboNonWebApplicationEnvironmentPostProcessor.postProcessEnvironment(DubboNonWebApplicationEnvironmentPostProcessor.java:100)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:188)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:206)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:117)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:74)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at net.chinafocus.dubbo.provider.ProApp.main(ProApp.java:19)
Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.config.spring.util.PropertySourcesUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:57019', transport: 'socket'

How Can I do?

**Comment by Eldon-Han** [comment]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-dubbo</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>
      
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>

**Comment by xiaochonzi** [comment]
使用2.0.3.RELEASE版本的spring-cloud-alibaba-dependencies

**Comment by yuhuangbin** [comment]
检查项目的Dubbo版本，是否自己修改了Dubbo版本？
