### ISSUE TITLE
关于spring-cloud-dubbo注册中心为zookeeper时，Monitor地址获取错误

### ISSUE THREAD

**Issue by houwen0** [alibaba/spring-cloud-alibaba#1850]
版本：
   spring-cloud-starter-dubbo:2.2.3.RELEASE
   dubbo:2.7.8
配置：
   
dubbo.protocols.dubbo.port=-1
dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.protocols.dubbo.name=dubbo
spring.cloud.zookeeper.enabled=true
spring.cloud.zookeeper.connect-string=127.0.0.1:2181
dubbo.registry.timeout=10000
dubbo.consumer.check=false
spring.main.allow-bean-definition-overriding=true
dubbo.monitor.protocol=registry

报错：
14:47:46.920 [DubboMonitorSendTimer-thread-1] ERROR o.a.dubbo.monitor.dubbo.DubboMonitor -  [DUBBO] Unexpected error occur at send statistic, cause: No provider available from registry localhost:9090 for service org.apache.dubbo.monitor.MonitorService on consumer 10.4.104.81 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist)., dubbo version: 2.7.8, current host: 10.4.104.81
org.apache.dubbo.rpc.RpcException: No provider available from registry localhost:9090 for service org.apache.dubbo.monitor.MonitorService on consumer 10.4.104.81 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:599)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:74)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:292)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:257)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:88)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
	at org.apache.dubbo.common.bytecode.proxy3.collect(proxy3.java)
	at org.apache.dubbo.monitor.dubbo.DubboMonitor.send(DubboMonitor.java:122)
	at org.apache.dubbo.monitor.dubbo.DubboMonitor.lambda$new$0(DubboMonitor.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by theonefx** [comment]
请问，升级到 2.2.5.RC2 还有这个问题吗？
