### ISSUE TITLE
socket shutdown exception

### ISSUE THREAD

**Issue by ReactorReddog** [alibaba/spring-cloud-alibaba#1869]
2020-12-15 22:58:54.751 ERROR 9330 --- [g.push.receiver] com.alibaba.nacos.client.naming          : [NA] error while receiving push data

java.net.SocketException: Socket closed
	at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:181) ~[na:na]
	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:864) ~[na:na]
	at com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:83) ~[nacos-client-1.3.3.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

这个不知是bug还是小弟我操作异常 但是小弟我愿意试试

**Comment by theonefx** [comment]
please provide more details.

**Comment by HeyChiang** [comment]
**I have the same problem，this is my bootstrap.yml**
`spring:
  cloud:
    nacos:
      config:
        password: nacos
        username: nacos
        context-path: /nacos
        server-addr: 127.0.0.1:8848
        file-extension: yml
  application:
    name: gateway
  profiles:
    active: dev`

**this is gateway-dev.yml in nacos config**
![image](https://user-images.githubusercontent.com/12081334/145504178-b04a9e94-8d3a-41b6-a96c-72ec4bce5df8.png)

my pom.xml
`<properties>
        <java.version>11</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.version>2.3.7.RELEASE</spring-boot.version>
        <spring-cloud-alibaba.version>2.2.2.RELEASE</spring-cloud-alibaba.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>`
