### ISSUE TITLE
org.apache.dubbo.rpc.RpcException: No provider available in XXXXXX

### ISSUE THREAD

**Issue by cxdhefei** [alibaba/spring-cloud-alibaba#1895]
**Which Component**
 nacos-server: 1.3.1
 spring-boot: 2.2.6.RELEASE
 spring-cloud-alibaba: 2.2.1.RELEASE (dubbo: 2.7.6、nacos-client: 1.2.1)
 spring-cloud: Hoxton.SR4

**Describe the bug**
服务提供者重启后，消费者无法发现服务提供者，出现如下错误（**这个问题是偶现的**）：
After the service provider restarts, the consumer cannot find the service provider, and the following error occurs(**This problem is occasional**)：

```
2021-01-04 13:40:00.088 ERROR [http-nio-2130-exec-5] com.xy.sdx.common.web.handler.GlobalExceptionHandler:116 [e251b3e36b154c68bb289f5ce06d1a46] No provider available in [invoker :interface com.xy.sdx.admin.api.RpcUserService -> spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?anyhost=true&application=sdx-manage-uaa&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.xy.sdx.admin.api.RpcUserService&methods=removeById,addUser,lambdaQuery,modifyStatus,removeByMap,findAppUserListByKeywordsAndAppCode,listByIds,saveUserRoleRelationship,removeUser,findListByRoleRegion,updateBatchById,modifyUserAddRoleRegionRelationship,findAppUserListByPage,saveUserRoleRegionRelationship,saveOrUpdate,removeRecordById,findByIds,query,findUserAppResource,count,listObjs,findByIdCard,list,getMap,getById,getOne,page,saveUserRoleBranchRelationship,findListByOperableRoles,save,update,getObj,saveOrUpdateBatch,remove,getBaseMapper,findListByPage,removeByIds,findPageListByRegion,findUserRoleBrandApp,findById,lambdaUpdate,modifyUserAddRoleBranchRelationship,listMaps,forgetPwd,updatePwd,saveBatch,modifyUserAddRoleRelationship,checkUserMobile,modifyUserRoleBranchRelationship,verifyPwd,updateById,pageMaps,modifyUserRoleRegionRelationship,findAppUserPageListByRegionAndAppCode,resetPwd,findAppUserListByRoleRegionAndAppCode,findByUsername,listByMap,findAppUserListByOperableRolesAndAppCode,findListByKeywords&pid=35713&qos.enable=false&register.ip=192.168.3.16&release=2.7.6&remote.application=sdx-admin&retries=0&service.filter=-exception&side=consumer&sticky=false&timeout=60000&timestamp=1609729666751,directory: org.apache.dubbo.registry.integration.RegistryDirectory@1fab0394, invoker :interface com.xy.sdx.admin.api.RpcUserService -> nacos://localhost:8848/org.apache.dubbo.registry.RegistryService?anyhost=true&application=sdx-manage-uaa&category=providers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.xy.sdx.admin.api.RpcUserService&methods=removeById,addUser,lambdaQuery,modifyStatus,removeByMap,findAppUserListByKeywordsAndAppCode,listByIds,saveUserRoleRelationship,removeUser,findListByRoleRegion,updateBatchById,modifyUserAddRoleRegionRelationship,findAppUserListByPage,saveUserRoleRegionRelationship,saveOrUpdate,removeRecordById,findByIds,query,findUserAppResource,count,listObjs,findByIdCard,list,getMap,getById,getOne,page,saveUserRoleBranchRelationship,findListByOperableRoles,save,update,getObj,saveOrUpdateBatch,remove,getBaseMapper,findListByPage,removeByIds,findPageListByRegion,findUserRoleBrandApp,findById,lambdaUpdate,modifyUserAddRoleBranchRelationship,listMaps,forgetPwd,updatePwd,saveBatch,modifyUserAddRoleRelationship,checkUserMobile,modifyUserRoleBranchRelationship,verifyPwd,updateById,pageMaps,modifyUserRoleRegionRelationship,findAppUserPageListByRegionAndAppCode,resetPwd,findAppUserListByRoleRegionAndAppCode,findByUsername,listByMap,findAppUserListByOperableRolesAndAppCode,findListByKeywords&path=com.xy.sdx.admin.api.RpcUserService&pid=35713&protocol=dubbo&qos.enable=false&register.ip=192.168.3.16&release=2.7.6&remote.application=sdx-admin&retries=0&service.filter=-exception&side=consumer&sticky=false&timeout=60000&timestamp=1609729666751,directory: org.apache.dubbo.registry.integration.RegistryDirectory@2a191f83]
org.apache.dubbo.rpc.RpcException: No provider available in [invoker :interface com.xy.sdx.admin.api.RpcUserService -> spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?anyhost=true&application=sdx-manage-uaa&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.xy.sdx.admin.api.RpcUserService&methods=removeById,addUser,lambdaQuery,modifyStatus,removeByMap,findAppUserListByKeywordsAndAppCode,listByIds,saveUserRoleRelationship,removeUser,findListByRoleRegion,updateBatchById,modifyUserAddRoleRegionRelationship,findAppUserListByPage,saveUserRoleRegionRelationship,saveOrUpdate,removeRecordById,findByIds,query,findUserAppResource,count,listObjs,findByIdCard,list,getMap,getById,getOne,page,saveUserRoleBranchRelationship,findListByOperableRoles,save,update,getObj,saveOrUpdateBatch,remove,getBaseMapper,findListByPage,removeByIds,findPageListByRegion,findUserRoleBrandApp,findById,lambdaUpdate,modifyUserAddRoleBranchRelationship,listMaps,forgetPwd,updatePwd,saveBatch,modifyUserAddRoleRelationship,checkUserMobile,modifyUserRoleBranchRelationship,verifyPwd,updateById,pageMaps,modifyUserRoleRegionRelationship,findAppUserPageListByRegionAndAppCode,resetPwd,findAppUserListByRoleRegionAndAppCode,findByUsername,listByMap,findAppUserListByOperableRolesAndAppCode,findListByKeywords&pid=35713&qos.enable=false&register.ip=192.168.3.16&release=2.7.6&remote.application=sdx-admin&retries=0&service.filter=-exception&side=consumer&sticky=false&timeout=60000&timestamp=1609729666751,directory: org.apache.dubbo.registry.integration.RegistryDirectory@1fab0394, invoker :interface com.xy.sdx.admin.api.RpcUserService -> nacos://localhost:8848/org.apache.dubbo.registry.RegistryService?anyhost=true&application=sdx-manage-uaa&category=providers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.xy.sdx.admin.api.RpcUserService&methods=removeById,addUser,lambdaQuery,modifyStatus,removeByMap,findAppUserListByKeywordsAndAppCode,listByIds,saveUserRoleRelationship,removeUser,findListByRoleRegion,updateBatchById,modifyUserAddRoleRegionRelationship,findAppUserListByPage,saveUserRoleRegionRelationship,saveOrUpdate,removeRecordById,findByIds,query,findUserAppResource,count,listObjs,findByIdCard,list,getMap,getById,getOne,page,saveUserRoleBranchRelationship,findListByOperableRoles,save,update,getObj,saveOrUpdateBatch,remove,getBaseMapper,findListByPage,removeByIds,findPageListByRegion,findUserRoleBrandApp,findById,lambdaUpdate,modifyUserAddRoleBranchRelationship,listMaps,forgetPwd,updatePwd,saveBatch,modifyUserAddRoleRelationship,checkUserMobile,modifyUserRoleBranchRelationship,verifyPwd,updateById,pageMaps,modifyUserRoleRegionRelationship,findAppUserPageListByRegionAndAppCode,resetPwd,findAppUserListByRoleRegionAndAppCode,findByUsername,listByMap,findAppUserListByOperableRolesAndAppCode,findListByKeywords&path=com.xy.sdx.admin.api.RpcUserService&pid=35713&protocol=dubbo&qos.enable=false&register.ip=192.168.3.16&release=2.7.6&remote.application=sdx-admin&retries=0&service.filter=-exception&side=consumer&sticky=false&timeout=60000&timestamp=1609729666751,directory: org.apache.dubbo.registry.integration.RegistryDirectory@2a191f83]
	at org.apache.dubbo.rpc.cluster.support.registry.ZoneAwareClusterInvoker.doInvoke(ZoneAwareClusterInvoker.java:101)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
	at org.apache.dubbo.common.bytecode.proxy3.findByUsername(proxy3.java)
	at com.xy.sdx.uaa.service.UserServiceImpl.login(UserServiceImpl.java:92)
	at com.xy.sdx.uaa.controller.LoginController.login(LoginController.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.xy.sdx.common.web.filter.TraceIdHttpFilter.doFilter(TraceIdHttpFilter.java:64)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cxdhefei** [comment]
![image](https://user-images.githubusercontent.com/16495772/103506260-42a3ee80-4e97-11eb-8e3f-a19858af7231.png)
这里返回的是false，client.isConnected() 是false

**Comment by theonefx** [comment]
#1805

**Comment by mostcool** [comment]
> #1805 seems like same issue

@theonefx 这个问题官方有计划解决吗？

**Comment by theonefx** [comment]
already fixed
