### ISSUE TITLE
nacos-1.4.1 autoRefresh  Error

### ISSUE THREAD

**Issue by jmdonghao** [alibaba/spring-cloud-alibaba#1942]
当我使用nacos1.4.1版本作为注册和配置中心,客户端启动后,从配置中心拉取配置正常,但是当我在nacos后台修改配置之后,客户端能获取到当前修改的内容,客户端项目就抛出异常，无法获取后续修改内容,异常信息如下 :
When I use Nacos version 1.4.1 as the registration and configuration center, after the client starts up, it is normal to pull the configuration from the configuration center. However, when I modify the configuration in the background of Nacos, the client can get the current modified content, and the client project throws an exception, and cannot get the subsequent modified content. The exception information is as follows:

longPolling error : 

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@72619195 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7f107c6c[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 82]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

14:23:36.871 nacos [com.alibaba.nacos.client.Worker.longPolling.fixed-127.0.0.1_8848-public] ERROR c.a.n.c.config.impl.ClientWorker
                - longPolling error : 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@72619195 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7f107c6c[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 82]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

nacos-client   bootstrap.yml:
     spring:
         application:
             name: nacos-config

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        namespace: public

logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: info

nacos-client   pom:
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

local  version: 
mac os:  10.14.6
nacos :1.4.1 
springboot:    2.3.2.RELEASE
springcloud:     Hoxton.SR8
springcloud-alibaba : 2.2.4.RELEASE

**Comment by theonefx** [comment]
请升级到 2.2.5.RC2 再试一下

**Comment by jmdonghao** [comment]
> 请升级到 2.2.5.RC2 再试一下

 刚刚做了测试,2.2.5.RC2版本没有问题,感谢
