### ISSUE TITLE
 spring-cloud-alibaba-2.2.4.RELEASE RejectedExecutionException

### ISSUE THREAD

**Issue by Hello-0000** [alibaba/spring-cloud-alibaba#1954]
Relying on SpringCloud-Alibaba 2.2.4, the release configuration console reported an error when nacos modified the configuration.

Error message:
`longPolling error : 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@73810e06 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@340c0442[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 3]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) ~[na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) ~[na:1.8.0_282]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]`

Change SpringCloud-Alibaba version to 2.2.3 and there will be no error message.

The situation indicating the error can be reproduced.

**Comment by theonefx** [comment]
pls use 2.2.5.RC2
