### ISSUE TITLE
在k8s环境下，升级nacos1.4.1和1.4.2客户端偶尔会出域名解析报错(IPv4 address("xxx") is incorrect)，导致服务丢失

### ISSUE THREAD

**Issue by manonba** [alibaba/spring-cloud-alibaba#2117]
**Which Component**
eg. Nacos1.4.1 & Nacos1.4.2

**Version**
<spring-boot.version>2.3.2.RELEASE</spring-boot.version>
<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
<alibaba-cloud.version>2.2.5.RELEASE</alibaba-cloud.version>

**Describe the bug**
在k8s环境下，升级nacos到1.4.1和1.4.2后，客户端时常会出现IPv4解析报错，
报了该错误之后，应用就与nacos server失去连接，从nacos server上面也看不到该服务的注册信息。重启应用后解决。
此问题发生后尝试在pod中ping域名其实是可以ping通的。

```java
2021-06-16 12:05:27.405  --- [com.alibaba.nacos.client.naming.updater] : [NA] failed to update serviceName: DEFAULT_GROUP@@system 
java.lang.IllegalArgumentException: The IPv4 address("nacos-server.global") is incorrect. 
	at com.alibaba.nacos.common.utils.IPUtil.splitIPPortStr(IPUtil.java:152) 
	at com.alibaba.nacos.common.utils.IPUtil.containsPort(IPUtil.java:119) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:595) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) 
	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) 
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
	at java.lang.Thread.run(Thread.java:748) 
```

![image-20210618092955676](https://tva1.sinaimg.cn/large/008i3skNgy1grm5y9totpj32ag0okn0f.jpg)

**Comment by theonefx** [comment]
nacos-client 1.4.1 是有这个问题，1.4.2 应该是解决这个问题了。刚才跟 nacos 那边的同学确认了

**Comment by theonefx** [comment]
可以看下这个 issue : https://github.com/alibaba/nacos/issues/5291

**Comment by manonba** [comment]
找到原因了，spring-alibaba-cloud 2.2.5 版本管理中的nacos-client版本还是1.4.1，麻烦官方及时更新一下最新稳定的版本信息

![image-20210618135154417](https://tva1.sinaimg.cn/large/008i3skNgy1grmdiuzdjjj314r0u0qbt.jpg)

> nacos-client 1.4.1 是有这个问题，1.4.2 应该是解决这个问题了。刚才跟 nacos 那边的同学确认了

**Comment by theonefx** [comment]
> 找到原因了，spring-alibaba-cloud 2.2.5 版本管理中的nacos-client版本还是1.4.1，麻烦官方及时更新一下最新稳定的版本信息
> 
> ![image-20210618135154417](https://camo.githubusercontent.com/783539b12a31c218e6ad07e0e87f7568c62e417e5a4a79e127e63de6c23159d3/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f3030386933736b4e67793167726d6469757a646a6a6a333134723075307162742e6a7067)
> 
> > nacos-client 1.4.1 是有这个问题，1.4.2 应该是解决这个问题了。刚才跟 nacos 那边的同学确认了

嗯，下一个版本会升级掉的，目前可能需要你这边先排除再单独引入

**Comment by zhangran2616** [comment]
> > 找到原因了，spring-alibaba-cloud 2.2.5 版本管理中的nacos-client版本还是1.4.1，麻烦官方及时更新一下最新稳定的版本信息
> > ![image-20210618135154417](https://camo.githubusercontent.com/783539b12a31c218e6ad07e0e87f7568c62e417e5a4a79e127e63de6c23159d3/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f3030386933736b4e67793167726d6469757a646a6a6a333134723075307162742e6a7067)
> > > nacos-client 1.4.1 是有这个问题，1.4.2 应该是解决这个问题了。刚才跟 nacos 那边的同学确认了
> 
> 嗯，下一个版本会升级掉的，目前可能需要你这边先排除再单独引入

啥时候发布

**Comment by theonefx** [comment]
这个月会发布的

**Comment by solvaysphere** [comment]
升级下k8s的网络flannel插件

**Comment by qyqcswill** [comment]
> alibaba/nacos#5291

你好，我们目前也出现了这个问题，1.4.1和1.4.2的版本都有这个问题，都是业务运行正常，突然一段时间之后，报错，导致业务掉线
