### ISSUE TITLE
feign error

### ISSUE THREAD

**Issue by davidwangmb** [alibaba/spring-cloud-alibaba#2122]
last new version  , server at starting report error:
version info:
 spring cloud alibaba  2021.1   spring cloud  2020.0.0  spring boot 2.4.2
 

Caused by: java.lang.NullPointerException: null
	at com.alibaba.cloud.sentinel.feign.SentinelFeign$Builder$1.create(SentinelFeign.java:92)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:64)
	at feign.Feign$Builder.target(Feign.java:269)
	at org.springframework.cloud.openfeign.DefaultTargeter.target(DefaultTargeter.java:30)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:306)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:335)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:315)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
	... 31 common frames omitted

**Comment by HaojunRen** [comment]
参考这个issue:
https://github.com/alibaba/spring-cloud-alibaba/issues/2137

是否可以提供一个可以单独运行且确定能重现该问题的简单示例给我们？

**Comment by zhouwei517** [comment]
同样碰到了这个问题，需要等待新版本发布吗？
