### ISSUE TITLE
UnknownHostException: nacos-provider

### ISSUE THREAD

**Issue by skyjilygao** [alibaba/spring-cloud-alibaba#2138]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

Why does the 2021.1 version of "spring-cloud-starter-alibaba-nacos-discovery" cannot find the ribbon, which results in a prompt that the provider cannot be obtained in "this.getLoadBalancer(serviceId)"

version: 
```
        <spring-boot.version>2.4.2</spring-boot.version>
        <spring-cloud.version>2020.0.3</spring-cloud.version>
        <spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
```

error:
```
java.net.UnknownHostException: nacos-provider
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_211]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_211]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_211]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_211]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_211]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_211]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_211]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_211]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_211]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_211]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_211]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[na:1.8.0_211]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_211]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_211]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[na:1.8.0_211]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:775) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:333) ~[spring-web-5.3.3.jar:5.3.3]
	at cn.sky.cloud.alibaba.controller.TestController.sayHello(TestController.java:34) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_211]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.3.jar:5.3.3]
```

There is no problem when using the following versions：
```
        <spring-boot.version>2.3.2</spring-boot.version>
        <spring-cloud.version>Hoxton.SR8</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>
```

**Comment by skyjilygao** [comment]
已经解决了。
2020版本就已经不再使用netflix，自然也就没有了ribbon。怎么办？使用`Spring Cloud Load Balancer`代替
1. pom.xml add dependency:
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-loadbalancer</artifactId>
</dependency>
```
2. application.yml下增加禁用ribbon配置
```yaml
spring:
  application:
    name: nacos-client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
```
这里我的各个版本是：
|组件|版本|
|:--|:--|
|spring-boot|2.5.2|
|spring-cloud|2020.0.2|
|spring-cloud-alibaba|2021.1|

**Comment by wangchuanluoshui** [comment]
same issues, use this solution fix it. thanks

**Comment by xiaoluxiang** [comment]
Thanks too!

**Comment by hw15101305** [comment]
我的版本是:
        <spring.cloud.alibaba.version>2021.0.1.0</spring.cloud.alibaba.version>
        <spring.boot.version>2.6.3</spring.boot.version>
        <spring.cloud.version>2021.0.1</spring.cloud.version>

没有以下配置并且调用没问题，估计官网直接默认摒弃以下操作
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

**Comment by riner-e-wo** [comment]
Thanks bro ^_^
