### ISSUE TITLE
nacos 更改配置发布就报线程池问题。是版本没有对应好吗

### ISSUE THREAD

**Issue by 734311568** [alibaba/spring-cloud-alibaba#2186]
使用nacos 作为配置中心的时候。 本地的配置也弄读取，但是在登入nacos 更改配置就发布之后就后台就会报错线程池问题。

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@248a3025 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2c2dc0a9[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) ~[na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) ~[na:1.8.0_291]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_291]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_291]
	at

**Comment by yuhuangbin** [comment]
给出详细的信息，版本，错误堆栈等

**Comment by 734311568** [comment]
版本这个
![image](https://user-images.githubusercontent.com/48379702/126949748-22f759ab-805f-4809-8ac8-43cb43c1903d.png)

![image](https://user-images.githubusercontent.com/48379702/126948476-015003bf-a5e3-44a7-8ed6-396a0e27b0d2.png)



![image](https://user-images.githubusercontent.com/48379702/126948609-e80b5be3-5089-4aef-bc85-331182d7b113.png)

![image](https://user-images.githubusercontent.com/48379702/126948743-a2ff088e-b724-42d0-a77f-adf679df5736.png)
后台报这样
![image](https://user-images.githubusercontent.com/48379702/126949202-23c39730-657e-440e-b1b6-d7cf58631648.png)
后面部分延长截图
![image](https://user-images.githubusercontent.com/48379702/126949470-dce6bfcd-07c5-4e91-b354-45c3c5dbdab7.png)
这是后台打印的错误信息
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1e00848 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6f0e2cf8[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) ~[na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) ~[na:1.8.0_291]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_291]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_291]

**Comment by yuhuangbin** [comment]
方便提供复现的demo项目吗？

**Comment by 734311568** [comment]
可以的  https://github.com/734311568/YesMall.git

**Comment by yuhuangbin** [comment]
2.2.4.RELEASE 版本不推荐使用，升级至2.2.6.RELEASE版本

**Comment by 734311568** [comment]
好的，谢谢您
