### ISSUE TITLE
When will dubbo upgrade to 3.0

### ISSUE THREAD

**Issue by thousmile** [alibaba/spring-cloud-alibaba#2290]
When will the dubbo components be upgraded to version 3.0? Are there any plans?

**Comment by steverao** [comment]
了解一下大家对社区快速支持dubbo 3.0的原因方面说一下嘛？现在大家的生产环境难道都开始逐渐使用dubbo 3.0版本了？

**Comment by gundamff** [comment]
> 了解一下大家对社区快速支持dubbo 3.0的原因方面说一下嘛？现在大家的生产环境难道都开始逐渐使用dubbo 3.0版本了？

思考的顺序反了, 是本项目要先支持, 大家才可能会考虑升级3.0

**Comment by steverao** [comment]
> > 了解一下大家对社区快速支持dubbo 3.0的原因方面说一下嘛？现在大家的生产环境难道都开始逐渐使用dubbo 3.0版本了？
> 
> 思考的顺序反了, 是本项目要先支持, 大家才可能会考虑升级3.0

想问的是大家为什么对社区支持dubbo 3.0意愿这么强烈哈？我们想了解一下这些呼声背后的原因

**Comment by steverao** [comment]
> > 了解一下大家对社区快速支持dubbo 3.0的原因方面说一下嘛？现在大家的生产环境难道都开始逐渐使用dubbo 3.0版本了？
> 
> 思考的顺序反了, 是本项目要先支持, 大家才可能会考虑升级3.0

Spring Cloud Alibaba本身不负责Dubbo开源的，只是提供了实现Spring Cloud与Dubbo互通调用组件，大家是对Spring Cloud与Dubbo 3.0互通调用有比较强述求吗？

**Comment by Sivan757** [comment]
Dubbo3.0 提供的应用级服务发现、Triple协议（兼容grpc over HTTP2 ）的支持是我目前比较关注的点。

应用级服务发现这里，目前 dubbo2.0 的接口级服务发现，在Spring-Cloud-Alibaba-Dubbo可以看到很多适配处理，需要记录很多信息到config-center，这个层面可能对适配上会简化些，对于服务上下线的状态检测可能更精准吧？（猜测..之前遇到过服务上下线，消费者感应不及时的问题）

新的协议Triple，提供了通用的 [triple_wrapper](https://github.com/apache/dubbo/blob/3.0/dubbo-rpc/dubbo-rpc-triple/src/main/proto/triple_wrapper.proto)，可以快速的升级很多旧接口，预计可以提升不少性能。虽然这种大范围的改动可能会带来未知影响，不过目前 Spring-Cloud-Alibaba-Dubbo 也提供了 Feign -> Dubbo2 的支持，体验上是非常好的。（所以 Feign -> Dubbo3 应该会更好😂）
另外，基于HTTP2可以在一些中间层（sidecar）基于header做拓展处理（看到 Dubbo issue 中有基于 header 做转发的相关需求）
总的来说会更“云”？

> 大家是对Spring Cloud与Dubbo 3.0互通调用有比较强述求吗？
我们实际场景上在脱离 springcloud 转向 springboot+k8s，这个过程中也会希望有更好的异构语言rpc调用的能力，之后可能是跨语言调用与 SpringCloud 的互通调用

这些也只是我看到比较感兴趣的点，目前知识局限性比较大；是否合适、是否兼容互通调用，还是得辛苦开源大佬😂

**Comment by dafuge** [comment]
现在是不兼容吗?

**Comment by WindBruce** [comment]
现在集成了吗？我尝试用Spring Cloud Alibaba 2.2.8 集成dubbo 3.0.7，加Nacos，一直启动失败，只能降级到2.7版本吗？

~~~log
[36mo.s.boot.SpringApplication:834[0;39m              [1;31m- Application run failed
[0;39mjava.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name dubbo, no related exception was found, please check whether related SPI module is missing.
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:747)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:754)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:548)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:523)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:393)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:242)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:641)
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:619)
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:578)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:410)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:396)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:361)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:233)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:341)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:313)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at com.lg.edu.OmsInterfaceApplication.main(OmsInterfaceApplication.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
~~~

**Comment by dafuge** [comment]
没在关注这个事,不好意思

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月15日 17:35
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [alibaba/spring-cloud-alibaba] When will dubbo upgrade to 3.0 (Issue #2290)


现在集成了吗？我尝试用Spring Cloud Alibaba 2.2.8 集成dubbo 3.0.7，加Nacos，一直启动失败，只能降级到2.7版本吗？

�[36mo.s.boot.SpringApplication:834�[0;39m              �[1;31m- Application run failed



�[0;39mjava.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name dubbo, no related exception was found, please check whether related SPI module is missing.



        at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:747)



        at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:754)



        at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:548)



        at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:523)



        at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)



        at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:393)



        at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:242)



        at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)



        at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74)



        at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)



        at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)



        at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)



        at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:641)



        at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:619)



        at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:578)



        at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:410)



        at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:396)



        at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:361)



        at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:233)



        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:341)



        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:313)



        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)



        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)



        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)



        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)



        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)



        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)



        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)



        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)



        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)



        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)



        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)



        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)



        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)



        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)



        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)



        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)



        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)



        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)



        at com.lg.edu.OmsInterfaceApplication.main(OmsInterfaceApplication.java:45)



        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)



        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)



        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)



        at java.lang.reflect.Method.invoke(Method.java:498)



        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
