### ISSUE TITLE
Caused by: org.apache.rocketmq.client.exception.MQClientException: The producer group[calcCallbackGroup] has been created before, specify another name please.

### ISSUE THREAD

**Issue by wuxingyun** [alibaba/spring-cloud-alibaba#2307]
Caused by: org.apache.rocketmq.client.exception.MQClientException: The producer group[calcCallbackGroup] has been created before, specify another name please.
See http://rocketmq.apache.org/docs/faq/ for further details.
at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:203)
at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:183)
at org.apache.rocketmq.client.producer.DefaultMQProducer.start(DefaultMQProducer.java:277)
at org.apache.rocketmq.spring.core.RocketMQTemplate.afterPropertiesSet(RocketMQTemplate.java:454)
at com.alibaba.cloud.stream.binder.rocketmq.integration.RocketMQMessageHandler.start(RocketMQMessageHandler.java:106)
... 12 common frames omitted

**Comment by pandaapo** [comment]
Can you describe in detail how to reproduce this exception and which version of dependency you use? （能否详细描述一下怎么重现该错误？使用的spring cloud alibaba哪个版本？）

**Comment by cloudX2019** [comment]
使用StreamBridge.send(topicName,Message)方法发送消息时，应用中使用到的topic超过10个会报这个错误。是因为StreamBridge中会默认缓存10个SubscribableChannel，超过后会将之前的移除掉。而再次发送消息到移除掉的topic会重新创建RocketMQTemplate导致报错
