### ISSUE TITLE
引入sentinel后报“ClassNotFoundException: com.alibaba.nacos.client.logging.NacosLogging”

### ISSUE THREAD

**Issue by wisekingokok** [alibaba/spring-cloud-alibaba#2356]
在引入sentinel之前，项目可以正常启动，build.gradle如下：

Before sentinel is introduced, the project can start normally, build.gradle is as follows:

```
plugins {
    id 'org.springframework.boot' version '2.3.7.RELEASE'
    id 'io.spring.dependency-management' version '1.0.10.RELEASE'
    id 'java'
}

......
......
......

ext {
    set('springCloudVersion', "Hoxton.SR9")
}

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')

    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2.2.6.RELEASE'

    implementation 'cn.dashulin.lib:lib-core:0.0.5'

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
```

在引入sentinel之后，build.gradle如下：

After introducing sentinel, build Gradle is as follows:

```
plugins {
    id 'org.springframework.boot' version '2.3.7.RELEASE'
    id 'io.spring.dependency-management' version '1.0.10.RELEASE'
    id 'java'
}

......
......
......

ext {
    set('springCloudAlibabaVersion', "2.2.2.RELEASE")
    set('springCloudVersion', "Hoxton.SR9")
}

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')

    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2.2.6.RELEASE'

    implementation 'cn.dashulin.lib:lib-core:0.0.5'

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}

dependencyManagement {
    imports {
        mavenBom "com.alibaba.cloud:spring-cloud-alibaba-dependencies:${springCloudAlibabaVersion}"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
```

此时项目无法启动，报错信息如下：

At this time, the project cannot be started, and the error information is as follows:

```
java.lang.NoClassDefFoundError: com/alibaba/nacos/client/logging/NacosLogging
	at com.alibaba.cloud.nacos.discovery.logging.NacosLoggingListener.onApplicationEvent(NacosLoggingListener.java:46) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	......
	......
	......
```

请问这个问题如何解决呢？

How to solve this problem?

**Comment by yuhuangbin** [comment]
ext {
    set('springCloudAlibabaVersion', "2.2.2.RELEASE")
    set('springCloudVersion', "Hoxton.SR9")
}

implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2.2.6.RELEASE'

保持版本一致?

**Comment by wisekingokok** [comment]
@yuhuanbin It is fixed, Thank you
