### ISSUE TITLE
"java.lang.NoSuchFieldError: logger" in RocketMQProducerMessageHandler

### ISSUE THREAD

**Issue by frlzk** [alibaba/spring-cloud-alibaba#2366]
**spring-cloud-starter-stream-rocketmq**

**Describe the bug**
`
java.lang.NoSuchFieldError: logger
	at com.alibaba.cloud.stream.binder.rocketmq.integration.outbound.RocketMQProducerMessageHandler.start(RocketMQProducerMessageHandler.java:120) ~[spring-cloud-starter-stream-rocketmq-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:248) ~[spring-cloud-stream-3.1.4.jar:3.1.4]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:91) ~[spring-cloud-stream-3.1.4.jar:3.1.4]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:152) ~[spring-cloud-stream-3.1.4.jar:3.1.4]
	at org.springframework.cloud.stream.binding.BindingService.doBindProducer(BindingService.java:320) ~[spring-cloud-stream-3.1.4.jar:3.1.4]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:285) ~[spring-cloud-stream-3.1.4.jar:3.1.4]
	at org.springframework.cloud.stream.function.StreamBridge.resolveDestination(StreamBridge.java:256) ~[spring-cloud-stream-3.1.4.jar:3.1.4]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:202) ~[spring-cloud-stream-3.1.4.jar:3.1.4]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:156) ~[spring-cloud-stream-3.1.4.jar:3.1.4]
`

**Screenshots**
In file com.alibaba.cloud.stream.binder.rocketmq.integration.outbound.RocketMQProducerMessageHandler line 120
`
if (extendedProducerProperties.getPartitionCount() != messageQueues
						.size()) {
					logger.info(String.format(
							"The partition count of topic '%s' will change from '%s' to '%s'",
							destination.getName(),
							extendedProducerProperties.getPartitionCount(),
							messageQueues.size()));
					extendedProducerProperties.setPartitionCount(messageQueues.size());
					// may be npe!
					partitioningInterceptor.setPartitionCount(
							extendedProducerProperties.getPartitionCount());
				}
`
The field "logger" is not defined.

**Additional context**
Java8 、spring-cloud-starter-stream-rocketmq-2.2.7.RELEASE.jar  spring-cloud-stream-3.1.4.jar

**Comment by yang-xiaobai** [comment]
此问题我将跟踪解决
