### ISSUE TITLE
2021.0.1.0  搭配nacos 2.0.4报错

### ISSUE THREAD

**Issue by jianhao2010303** [alibaba/spring-cloud-alibaba#2431]
java.lang.NoSuchMethodError: com.alibaba.nacos.common.utils.StringUtils.isBlank(Ljava/lang/String;)Z
at com.alibaba.cloud.nacos.configdata.NacosConfigDataLocationResolver.getUri(NacosConfigDataLocationResolver.java:176)
at com.alibaba.cloud.nacos.configdata.NacosConfigDataLocationResolver.loadConfigDataResources(NacosConfigDataLocationResolver.java:158)
at com.alibaba.cloud.nacos.configdata.NacosConfigDataLocationResolver.resolveProfileSpecific(NacosConfigDataLocationResolver.java:151)
at org.springframework.boot.context.config.ConfigDataLocationResolvers.lambda$resolve$2(ConfigDataLocationResolvers.java:120)
at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:126)
at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:119)
at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:107)
at org.springframework.boot.context.config.ConfigDataImporter.resolve(ConfigDataImporter.java:105)
at org.springframework.boot.context.config.ConfigDataImporter.resolve(ConfigDataImporter.java:97)
at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:85)
at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:116)
at org.springframework.boot.context.config.ConfigDataEnvironment.processWithProfiles(ConfigDataEnvironment.java:311)
at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:232)
at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:338)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
at cn.com.xuct.calendar.gateway.GatewayApplication.main(GatewayApplication.java:32)

**Comment by iPisces77** [comment]
我记得这个是优先适配的1.x版本的

**Comment by jianhao2010303** [comment]
还望群主大大给与支持。现在线上使用的2.*的版本。

**Comment by HaojunRen** [comment]
看了一下源码，Nacos 2.x比1.x，StringUtils.isBlank构造方法，从String改成了Charsequence，按理应该兼容的

**Comment by jianhao2010303** [comment]
> 

可以使用使用nacos 2.0.4试一试。确实报错了。

**Comment by HaojunRen** [comment]
我尝试启动一下，没有问题。如图所示：
![图片](https://user-images.githubusercontent.com/42354711/156691843-575b0242-9661-4b90-a9ce-41fce4ead935.png)
![图片](https://user-images.githubusercontent.com/42354711/156691761-318bc7da-0a86-4904-b987-dd92daa6c95a.png)

**Comment by HaojunRen** [comment]
是否存在这个问题：classpath下，既有1.4.3，又有2.0.4的nacos包

**Comment by jianhao2010303** [comment]
结贴。鉴定完毕：自己low了。###

**Comment by jianhao2010303** [comment]
使用 spring.config.import方式导入，去掉bootstrap starter启动会出错。

**Comment by ossworker** [comment]
是有这个问题 
```
<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>2.0.4</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.alibaba.nacos</groupId>
					<artifactId>nacos-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```


***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.alibaba.cloud.nacos.configdata.NacosConfigDataLocationResolver.getUri(NacosConfigDataLocationResolver.java:176)

The following method did not exist:

    com.alibaba.nacos.common.utils.StringUtils.isBlank(Ljava/lang/String;)Z

The calling method's class, com.alibaba.cloud.nacos.configdata.NacosConfigDataLocationResolver, was loaded from the following location:

    jar:file:/home/workoss/.m2/repository/com/alibaba/cloud/spring-cloud-starter-alibaba-nacos-config/2021.0.1.0/spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/com/alibaba/cloud/nacos/configdata/NacosConfigDataLocationResolver.class

The called method's class, com.alibaba.nacos.common.utils.StringUtils, is available from the following locations:

    jar:file:/home/workoss/.m2/repository/com/alibaba/nacos/nacos-client/2.0.4/nacos-client-2.0.4.jar!/com/alibaba/nacos/common/utils/StringUtils.class

The called method's class hierarchy was loaded from the following locations:

    com.alibaba.nacos.common.utils.StringUtils: file:/home/*/.m2/repository/com/alibaba/nacos/nacos-client/2.0.4/nacos-client-2.0.4.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.alibaba.cloud.nacos.configdata.NacosConfigDataLocationResolver and com.alibaba.nacos.common.utils.StringUtils

**Comment by HaojunRen** [comment]
> 使用 spring.config.import方式导入，去掉bootstrap starter启动会出错。

那么，是否已经确定，不是包升级的问题，而是使用上可能带来的问题？

**Comment by HaojunRen** [comment]
Spring Boot 2.6，有不少底层机制都有变动，有些问题，Spring Cloud & Spring Boot可能未必也考虑到了，例如：在低版本使用的方式在高版本未必能用。这个，我们也在探索中

**Comment by jianhao2010303** [comment]
Action:  CharSequence 与 String 参数不一致。Override了方法之后启动正常。
 
  public static boolean isBlank(final CharSequence cs) {
        int strLen;
        if (cs == null || (strLen = cs.length()) == 0) {
            return true;
        }
        for (int i = 0; i < strLen; i++) {
            if (!Character.isWhitespace(cs.charAt(i))) {
                return false;
            }
        }
        return true;
    }

**Comment by DanielLiu1123** [comment]
这里应该是一个失误，使用到了nacos的 StringUtil :-)

**Comment by jianhao2010303** [comment]
期待大大们赶紧修复下，现在引用如果不自己重写类就无法启动。

**Comment by DanielLiu1123** [comment]
Fixed.

**Comment by DanielLiu1123** [comment]
nacos 客户端版本大于等于 2.0.3 时会出现该问题，使用 2021.0.1.0 版本时，nacos-client 版本要在 2.0.3 以下

**Comment by HaojunRen** [comment]
> Action: CharSequence 与 String 参数不一致。Override了方法之后启动正常。
> 
> public static boolean isBlank(final CharSequence cs) { int strLen; if (cs == null || (strLen = cs.length()) == 0) { return true; } for (int i = 0; i < strLen; i++) { if (!Character.isWhitespace(cs.charAt(i))) { return false; } } return true; }

老版本：public static boolean isBlank(final String cs)
新版本：public static boolean isBlank(final CharSequence cs)

其实这两个方法是同一回事，String是CharSequence的接口实现
```public final class String
    implements java.io.Serializable, Comparable<String>, CharSequence```

BTW：我反复尝试了，都没发现你提到的问题

**Comment by melin** [comment]
这样一些方法，尽量使用common-langs，避免兼容性问题
