### ISSUE TITLE
Unable to load config data from 'optional:nacos:test.yaml?group=DEFAULT_GROUP'

### ISSUE THREAD

**Issue by sk142857** [alibaba/spring-cloud-alibaba#2448]
https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-2.4.x-example/readme-zh.md

```
11:03:25.556 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Unable to load config data from 'optional:nacos:test.yaml?group=DEFAULT_GROUP'
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:141)
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:126)
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.resolve(StandardConfigDataLocationResolver.java:119)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.lambda$resolve$1(ConfigDataLocationResolvers.java:115)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:126)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:115)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:107)
	at org.springframework.boot.context.config.ConfigDataImporter.resolve(ConfigDataImporter.java:105)
	at org.springframework.boot.context.config.ConfigDataImporter.resolve(ConfigDataImporter.java:97)
	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:85)
	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:116)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:240)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:227)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:297)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at com.hy.sofa.cloud.gateway.GatewayApplication.main(GatewayApplication.java:40)
Caused by: java.lang.IllegalStateException: File extension is not known to any PropertySourceLoader. If the location is meant to reference a directory, it must end in '/' or File.separator
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferencesForFile(StandardConfigDataLocationResolver.java:229)
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:138)
	... 31 common frames omitted

Process finished with exit code 1

```

**Comment by DanielLiu1123** [comment]
你使用的是 example 启动还是自己搭建时出现的问题？

**Comment by sk142857** [comment]
> 你使用的是 example 启动还是自己搭建时出现的问题？

自己搭建的。

正常：`optional:nacos:test.yaml`
异常：`optional:nacos:test.yaml?group=DEFAULT_GROUP`

```
<spring-boot.version>2.6.4</spring-boot.version>
<spring-cloud.version>2021.0.1</spring-cloud.version>
<spring-cloud-alibaba.version>2021.0.1.0</spring-cloud-alibaba.version>
<nacos-client.version>2.0.4</nacos-client.version>
```

**Comment by DanielLiu1123** [comment]
尝试 nacos-client 降到 2.0.3以下，或者可以给个demo重现问题吗

**Comment by zhadan142857** [comment]
> 尝试 nacos-client 降到 2.0.3以下，或者可以给个demo重现问题吗

降级没有用。demo很简单。

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.4</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>17</java.version>
		<spring-cloud.version>2021.0.1</spring-cloud.version>
		<spring-cloud-alibaba.version>2021.0.1.0</spring-cloud-alibaba.version>
<!--		<nacos-client.version>2.0.3</nacos-client.version>-->
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<!-- Alibaba Nacos Config -->
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
			<exclusions>
				<exclusion>
						<groupId>com.alibaba.nacos</groupId>
						<artifactId>nacos-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.alibaba.nacos</groupId>
					<artifactId>nacos-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.alibaba.nacos/nacos-client -->
		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>2.0.2</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>${spring-cloud-alibaba.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by DanielLiu1123** [comment]
Spring Boot version greater than 2.6.

**Comment by zhadan142857** [comment]
> Spring Boot version greater than 2.6.

https://github.com/DanielLiu1123/cloud-env

你这个例子也是一样的，后面加 ?group=DEFAULT_GROUP 就报错，不知道官方例子为啥这样写。

**Comment by DanielLiu1123** [comment]
> https://github.com/DanielLiu1123/cloud-env
> 
> 你这个例子也是一样的，后面加 ?group=DEFAULT_GROUP 就报错，不知道官方例子为啥这样写。

这是个人的测试用例，我还是没有复现你说的情况

**Comment by zhadan142857** [comment]
> > https://github.com/DanielLiu1123/cloud-env
> > 你这个例子也是一样的，后面加 ?group=DEFAULT_GROUP 就报错，不知道官方例子为啥这样写。
> 
> 这是个人的测试用例，我还是没有复现你说的情况

搞定

> > https://github.com/DanielLiu1123/cloud-env
> > 你这个例子也是一样的，后面加 ?group=DEFAULT_GROUP 就报错，不知道官方例子为啥这样写。
> 
> 这是个人的测试用例，我还是没有复现你说的情况

降级到 2.0.2 可以了。

**Comment by sk142857** [comment]
> > https://github.com/DanielLiu1123/cloud-env
> > 你这个例子也是一样的，后面加 ?group=DEFAULT_GROUP 就报错，不知道官方例子为啥这样写。
> 
> 这是个人的测试用例，我还是没有复现你说的情况

降级到 2.0.2 可以了。

**Comment by bangiao** [comment]
我写了个小demo也遇到了这个问题
暂时改用 bootstrap extension-configs 多文件方案 （公司肯定不敢玩这么新）
原因应该是springboot版本太新了，当初设计的时候强绑定springboot2.4 spring.config.import功能，没做好防腐
version：spring boot 2.7.3 nacos 2.1.1

**Comment by youngledo** [comment]
这个问题的解决方案是这样吗？
1. 升级Spring Boot版本到2.6以上？
2. 降级nacos-client到2.0.2吗？

没有其它方法？
