### ISSUE TITLE
启动过程中，出现Service not found:com.alibaba.cloud.dubbo.service.DubboMetadataService, getMetadataInfo

### ISSUE THREAD

**Issue by megatronyy** [alibaba/spring-cloud-alibaba#2472]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
 <spring.boot.version>2.3.12.RELEASE</spring.boot.version>
<spring-boot-admin.version>2.3.0</spring-boot-admin.version>
<spring.cloud.version>Hoxton.SR12</spring.cloud.version>
<spring.context.support.version>1.0.11</spring.context.support.version>
<alibaba.cloud.version>2.2.7.RELEASE</alibaba.cloud.version>
<dubbo.version>2.7.13</dubbo.version>
<nacos.client.version>2.0.3</nacos.client.version>

**Describe the bug**
程序启动过程中，出现了Service not found:com.alibaba.cloud.dubbo.service.DubboMetadataService, getMetadataInfo，为什么会在DubboMetadataService里找getMetadataInfo方法呢

**Expected behavior**
2022-03-18 14:49:29  [ DubboServerHandler-192.168.206.110:20880-thread-198:1031550 ] - [ WARN ] org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:86)  [DUBBO] Decode rpc invocation failed: Service not found:com.alibaba.cloud.dubbo.service.DubboMetadataService, getMetadataInfo, dubbo version: 2.7.13, current host: 192.168.206.110
java.lang.IllegalArgumentException: Service not found:com.alibaba.cloud.dubbo.service.DubboMetadataService, getMetadataInfo
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:146)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:83)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:748)

**Additional context**
  win10 java8

请帮忙解决，或者给点思路，非常感谢！

用之前issue给的方案，引用后未解决
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-registry-nacos</artifactId>
    <version>${dubbo-registry-nacos.version}</version>
</dependency>

**Comment by steverao** [comment]
We don't recommend to use Spring Cloud Dubbo in production environment. Specific discussion see #2398

**Comment by steverao** [comment]
We don't maintain the component of Spring Cloud Dubbo, please see #2398
