### ISSUE TITLE
When 2021.0.1 of  SpringCloudAlibaba is used, the undertow server reports ‘java.lang.IllegalStateException: UT015023: This Context has been already destroyed'

### ISSUE THREAD

**Issue by ArchieSean-YH** [alibaba/spring-cloud-alibaba#2652]
```
java.lang.IllegalStateException: UT015023: This Context has been already destroyed
	at io.undertow.servlet.spec.ServletContextImpl.getDeploymentInfo(ServletContextImpl.java:211)
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames(ServletContextImpl.java:449)
	at org.springframework.web.context.support.ServletContextPropertySource.getPropertyNames(ServletContextPropertySource.java:41)
	at com.alibaba.spring.util.PropertySourcesUtils.getPropertyNames(PropertySourcesUtils.java:130)
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:103)
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:57)
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.enrichNacosDiscoveryProperties(NacosDiscoveryProperties.java:657)
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.getNacosProperties(NacosDiscoveryProperties.java:651)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:175)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.destroy(NacosWatch.java:206)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:213)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1163)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1156)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:596)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
```

**Comment by ArchieSean-YH** [comment]
nacos 1.4.2

**Comment by sollhui** [comment]
这是启动遇到的问题吗？还是什么情况，如果可以，可以简述一下遇到的问题方便或者提供复现问题的demo方便我们排查

**Comment by ArchieSean-YH** [comment]
代码发邮件附件？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月13日 08:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [alibaba/spring-cloud-alibaba] When 2021.0.1 of  SpringCloudAlibaba is used, the undertow server reports ‘java.lang.IllegalStateException: UT015023: This Context has been already destroyed' (Issue #2652) |

这是启动遇到的问题吗？还是什么情况，如果可以，可以简述一下遇到的问题方便或者提供复现问题的demo方便我们排查

**Comment by sollhui** [comment]
可以考虑放在github或者gitee等账户中，提供一个连接，方便其他人也可以看见并排查

**Comment by ArchieSean-YH** [comment]
代码地址： https://github.com/ArchieSean-YH/sean-parent.git；

nacos更改为了127.0.0.1，nacos的配置在nacos.yaml当中，复现请查看snowflake服务（sean-service模块当中）

**Comment by ArchieSean-YH** [comment]
> 还是什么情况，如果可以，可以简单描述一下现在遇到的问题的方便性或者提供复查的演示方便我们排行吗？

这个是启动的时候出现的，能注册到nacos，但是控制台报错，idea项目关闭正在运行项目失败。查了下资料问题可能是nacos销毁服务失败。

**Comment by ArchieSean-YH** [comment]
这个问题已解决，请忽略。现

**Comment by sollhui** [comment]
@ArchieSean-YH refer ：https://github.com/alibaba/spring-cloud-alibaba/pull/2603

**Comment by ArchieSean-YH** [comment]
有时候会出现这个问题，偶尔又是正常的

**Comment by steverao** [comment]
We fixed it and it won't appear in the next release.
