### ISSUE TITLE
Error in using Spring Cloud Dubbo

### ISSUE THREAD

**Issue by pannifengxing** [alibaba/spring-cloud-alibaba#2669]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

old：
spring-cloud-alibaba-dependencies.version 2.2.1.RELEASE
spring-cloud-dependencies.version Hoxton.SR8
after upgrade  
now:
spring-cloud-alibaba-dependencies.version 2.2.6.RELEASE
spring-cloud-dependencies.version Hoxton.SR9

服务器启动后报
16:21:38.383 [main] ERROR c.a.c.d.s.DubboMetadataServiceInvocationHandler - [invoke,53] - Failed to invoke the method $invoke in the service org.apache.dubbo.rpc.service.GenericService. No provider available for the service military-buffalo/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0 from registry 172.16.3.251:8848 on the consumer 172.16.3.251 using the dubbo version 2.7.8. Please check if the providers have been started and registered.
org.apache.dubbo.rpc.RpcException: Failed to invoke the method $invoke in the service org.apache.dubbo.rpc.service.GenericService. No provider available for the service military-buffalo/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0 from registry 172.16.3.251:8848 on the consumer 172.16.3.251 using the dubbo version 2.7.8. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:283)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:59)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:260)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:88)
	at org.apache.dubbo.rpc.cluster.support.registry.ZoneAwareClusterInvoker.doInvoke(ZoneAwareClusterInvoker.java:91)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:260)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
	at org.apache.dubbo.common.bytecode.proxy0.$invoke(proxy0.java)
	at com.alibaba.cloud.dubbo.service.DubboMetadataServiceInvocationHandler.invoke(DubboMetadataServiceInvocationHandler.java:48)
	at com.sun.proxy.$Proxy145.getExportedURLs(Unknown Source)

但是对应的服务提供者是启动的， 具体报的也不是业务的服务接口

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by steverao** [comment]
Don't use component of Spring Cloud Dubbo and remove relevant dependency, we remove the component in new version, you can see discussion #2398
