### ISSUE TITLE
spring.config.import nacos config stuck at listening config:

### ISSUE THREAD

**Issue by venson** [alibaba/spring-cloud-alibaba#2733]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

Nacos config

**Describe the bug**

```
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.6.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2021.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2021.0.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>

```

application.yml
```
spring:
  config:
    import:
      - optional:nacos:common-mysql.yml
      - optional:nacos:common-redis.yml

```

**To Reproduce**
1. can run normal in IDEA
2. mvn clean package
3. java -jar jarfile
4. stuck at listening config:

after mvn 

**Expected behavior**

**Screenshots**
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-08-27 23:12:23.290  WARN 70103 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[service-acl] & group[DEFAULT_GROUP]
2022-08-27 23:12:23.294  WARN 70103 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[service-acl.properties] & group[DEFAULT_GROUP]
2022-08-27 23:12:23.297  WARN 70103 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[service-acl-dev.properties] & group[DEFAULT_GROUP]
2022-08-27 23:12:23.298  INFO 70103 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-service-acl-dev.properties,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-service-acl.properties,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-service-acl,DEFAULT_GROUP'}]
2022-08-27 23:12:23.308  INFO 70103 --- [           main] com.venson.AclApplication                : The following profiles are active: dev
2022-08-27 23:12:24.481  INFO 70103 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2022-08-27 23:12:24.485  INFO 70103 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2022-08-27 23:12:24.526  INFO 70103 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 19 ms. Found 0 Redis repository interfaces.
2022-08-27 23:12:24.958  INFO 70103 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=a30af628-b9a1-3e6b-b11e-6bed3dd977fb
2022-08-27 23:12:25.588  INFO 70103 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8009 (http)
2022-08-27 23:12:25.597  INFO 70103 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-08-27 23:12:25.597  INFO 70103 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.56]
2022-08-27 23:12:25.658  INFO 70103 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-08-27 23:12:25.658  INFO 70103 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2322 ms
2022-08-27 23:12:25.814  WARN 70103 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2022-08-27 23:12:25.814  INFO 70103 --- [           main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2022-08-27 23:12:25.849  INFO 70103 --- [           main] c.netflix.config.DynamicPropertyFactory  : DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@4c2bb6e0
Logging initialized using 'class org.apache.ibatis.logging.stdout.StdOutImpl' adapter.
Property 'mapperLocations' was not specified.
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.5.2 
2022-08-27 23:12:26.800  INFO 70103 --- [           main] o.s.c.openfeign.FeignClientFactoryBean   : For 'service-msm' URL not provided. Will try picking an instance via load-balancing.
2022-08-27 23:12:27.724  INFO 70103 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@47a86fbb, org.springframework.security.web.context.SecurityContextPersistenceFilter@63fdab07, org.springframework.security.web.header.HeaderWriterFilter@1755e85b, org.springframework.security.web.authentication.logout.LogoutFilter@54d18072, com.venson.security.filter.TokenLoginFilter@f478a81, com.venson.security.filter.TokenAuthenticationFilter@19553973, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@1c3146bc, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@5553d0f5, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@14dda234, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@7bb6ab3a, org.springframework.security.web.session.SessionManagementFilter@2371aaca, org.springframework.security.web.access.ExceptionTranslationFilter@2e9fda69, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@b7838a9]
2022-08-27 23:12:27.749  WARN 70103 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2022-08-27 23:12:27.749  INFO 70103 --- [           main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2022-08-27 23:12:29.611  WARN 70103 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
2022-08-27 23:12:29.624  INFO 70103 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-08-27 23:12:29.787  INFO 70103 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8009 (http) with context path ''
2022-08-27 23:12:29.798  INFO 70103 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, DEFAULT_GROUP service-acl 192.168.1.183:8009 register finished
2022-08-27 23:12:29.819  INFO 70103 --- [           main] com.venson.AclApplication                : Started AclApplication in 7.732 seconds (JVM running for 8.229)
2022-08-27 23:12:29.864  INFO 70103 --- [           main] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=service-acl, group=DEFAULT_GROUP
2022-08-27 23:12:29.865  INFO 70103 --- [           main] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=common-mysql.yml, group=DEFAULT_GROUP
2022-08-27 23:12:29.865  INFO 70103 --- [           main] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=service-acl.properties, group=DEFAULT_GROUP
2022-08-27 23:12:29.865  INFO 70103 --- [           main] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=service-acl-dev.properties, group=DEFAULT_GROUP
2022-08-27 23:12:29.866  INFO 70103 --- [           main] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=common-redis.yml, group=DEFAULT_GROUP


```
**Additional context**
mac os, archlinux
nacos 2.11. 2.10
java8

**Comment by steverao** [comment]
I didn't see error logs and everything seems to right.

**Comment by spidersq** [comment]
> I didn't see error logs and everything seems to right.

`13:37:16.047 [main] DEBUG org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - Application failed to start due to an exception
org.springframework.boot.context.config.ConfigDataResourceNotFoundException: Config data resource 'NacosConfigDataResource{properties=NacosConfigProperties{serverAddr='xxxxx:8848', encode='null', group='DEV_GROUP', prefix='nul
l', fileExtension='yml', timeout=3000, maxRetry='null', configLongPollTimeout='null', configRetryTime='null', enableRemoteSyncConfig=false, endpoint='null', namespace='1d70a448-8aaf-40eb-9119-0540c8eaaade', accessKey='null', secretK
ey='null', ramRoleName='null', contextPath='null', clusterName='null', name='null'', shares=null, extensions=null, refreshEnabled=true}, optional=false, profiles=[Profiles@35d176f7 active = '[dev]', default = '[default]', accepted = '[dev]'], config=NacosItemConfig{group='DEV_GROUP', dataId='aaa.yml', suffix='yml', refreshEnabled=true}}' via location 'nacos:aaa.yml' cannot be found
        at org.springframework.boot.context.config.ConfigDataResourceNotFoundException.withLocation(ConfigDataResourceNotFoundException.java:97)
        at org.springframework.boot.context.config.ConfigDataImporter.handle(ConfigDataImporter.java:145)
        at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:136)
        at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:86)
        at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:116)
        at org.springframework.boot.context.config.ConfigDataEnvironment.processWithProfiles(ConfigDataEnvironment.java:311)
        at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:232)
        at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
        at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at com.org.Application.main(Application.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1198)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:213)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155)
        at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:93)
        at org.yaml.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:124)
        at org.yaml.snakeyaml.Yaml$1.hasNext(Yaml.java:509)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:198)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166)
        at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
        at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
        at com.alibaba.cloud.nacos.parser.NacosDataParserHandler.parseNacosData(NacosDataParserHandler.java:92)
        at com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader.pullConfig(NacosConfigDataLoader.java:101)
        at com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader.doLoad(NacosConfigDataLoader.java:72)
        at com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader.load(NacosConfigDataLoader.java:59)
        at com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader.load(NacosConfigDataLoader.java:48)
        at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:107)
        at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:128)
        ... 31 common frames omitted
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
***************************

Description:

Config data resource 'NacosConfigDataResource{properties=NacosConfigProperties{serverAddr='xxxx:8848', encode='null', group='DEV_GROUP', prefix='null', fileExtension='yml', timeout=3000, maxRetry='null', configLongPollTimeout='null', configRetryTime='null', enableRemoteSyncConfig=false, endpoint='null', namespace='1d70a448-8aaf-40eb-9119-0540c8e8aade', accessKey='null', secretKey='null', ramRoleName='null', contextPath='null', clusterName='null', name='null'', shares=null, extensions=null, refreshEnabled=true}, optional=false, profiles=[Profiles@35d176f7 active = '[dev]', default = '[default]', accepted = '[dev]'], config=NacosItemConfig{group='DEV_GROUP', dataId='aaa.yml', suffix='yml', refreshEnabled=true}}' via location 'nacos:aaa.yml' does not exist

Action:

Check that the value 'nacos:aaa.yml' at class path resource [application-dev.yml] from myjar.jar - 34:9 is correct, or prefix it with 'optional:'
`

我遇到了同样的问题，我来帮他补充异常信息吧。
在idea中启动没问题，但是打jar包后，运行就报异常了。
