### ISSUE TITLE
Receiving messages via spring-cloud-starter-stream-rocketmq reports an error

### ISSUE THREAD

**Issue by coderzcr** [alibaba/spring-cloud-alibaba#2739]
**Which Component**

**spring-cloud-starter-stream-rocketmq 2.2.5.RELEASE**

**Describe the bug**

Receiving messages via spring-cloud-starter-stream-rocketmq reports an error

```
2022-08-30 16:17:19.048 ERROR 27712 --- [MessageThread_1] .a.c.s.b.r.s.JacksonRocketMQHeaderMapper : Could not decode json type: {"type":"application","subtype":"json","parameters":{},"charset":null,"concrete":true,"wildcardType":false,"wildcardSubtype":false} for key: accept

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.springframework.util.MimeType` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"type":"application","subtype":"json","parameters":{},"charset":null,"concrete":true,"wildcardType":false,"wildcardSubtype":false}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1455) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1332) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.alibaba.cloud.stream.binder.rocketmq.support.JacksonRocketMQHeaderMapper.decodeValue(JacksonRocketMQHeaderMapper.java:191) ~[spring-cloud-starter-stream-rocketmq-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.alibaba.cloud.stream.binder.rocketmq.support.JacksonRocketMQHeaderMapper.lambda$toHeaders$1(JacksonRocketMQHeaderMapper.java:128) ~[spring-cloud-starter-stream-rocketmq-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at java.base/java.util.HashMap.forEach(HashMap.java:1336) ~[na:na]
	at com.alibaba.cloud.stream.binder.rocketmq.support.JacksonRocketMQHeaderMapper.toHeaders(JacksonRocketMQHeaderMapper.java:111) ~[spring-cloud-starter-stream-rocketmq-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.alibaba.cloud.stream.binder.rocketmq.consuming.RocketMQListenerBindingContainer.convertToSpringMessage(RocketMQListenerBindingContainer.java:406) ~[spring-cloud-starter-stream-rocketmq-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.alibaba.cloud.stream.binder.rocketmq.consuming.RocketMQListenerBindingContainer.access$100(RocketMQListenerBindingContainer.java:71) ~[spring-cloud-starter-stream-rocketmq-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.alibaba.cloud.stream.binder.rocketmq.consuming.RocketMQListenerBindingContainer$DefaultMessageListenerConcurrently.consumeMessage(RocketMQListenerBindingContainer.java:420) ~[spring-cloud-starter-stream-rocketmq-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:417) ~[rocketmq-client-4.4.0.jar:4.4.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-08-30 16:17:19.054  INFO 27712 --- [MessageThread_1] o.s.i.h.s.MessagingMethodInvokerHelper   : Overriding default instance of MessageHandlerMethodFactory with provided one.
```

**To Reproduce**
Producer Code
```
@Autowired
    private StreamBridge streamBridge;

    // 测试登录，浏览器访问： http://localhost:28089/producer/producer
    @GetMapping("producer")
    public String producer() {
        Map<String, Object> headers = new HashMap<>();
        Message<SimpleMsg> msg = new GenericMessage(
                new SimpleMsg("Hello RocketMQ."), headers);
        streamBridge.send("producer-out-0", msg);
        return "发送成功";
    }
```

Cousumer Code
```
@Bean
    public Consumer<Message<SimpleMsg>> consumer() {
        return msg -> {
            System.out.println(Thread.currentThread().getName() + " Receive New Messages: "
                    + msg.getPayload().getMsg());
            try {
                Thread.sleep(100);
            } catch (InterruptedException ignored) {
            }
        };
    }
```
An error will be reported when consuming，But it can be consumed successfully

**Expected behavior**

Consumption is successful, but no error is reported

**Screenshots**
![image](https://user-images.githubusercontent.com/37607051/187387771-7c303ab4-dad2-45c1-8ca1-f1409d046e22.png)

**Additional context**
java8
springboot 2.3.2.RELEASE
spring cloud Hoxton.SR8
spring cloud alibaba 2.2.5.RELEASE

**Comment by ruansheng8** [comment]
see #1960
