### ISSUE TITLE
nacos register support ipv6

### ISSUE THREAD

**Issue by wxjin** [alibaba/spring-cloud-alibaba#2740]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Discovery ipv6
version: 2.2.8.RELEASE

**Describe what problem you have encountered**
1、using ipv4 is normal and ipv6 is ibnormal; 
and telnet -6 ipv6 8848 is nomal.
2、config: spring.cloud.nacos.discovery.server-addr=[fe80::35ba:6827:c5ff:d161%11]:8848

3、 nacos register fail
2022-08-25 17:27:44.269 ERROR 24636 --- [ main] c.a.cloud.nacos.discovery.NacosWatch : namingService subscribe failed, properties:NacosDiscoveryProperties{serverAddr='[fe80::35ba:6827:c5ff:d161%11]:8848', endpoint='', namespace='6a3cda73-1e13-4ef9-b018-3be63387a30d', watchDelay=30000, logName='', service='ser-module', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='172.19.88.99', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, failFast=true}

com.alibaba.nacos.api.exception.NacosException: Request nacos server failed:
at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288) ~[nacos-client-2.1.0.jar:na]
at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:229) ~[nacos-client-2.1.0.jar:na]
at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:214) ~[nacos-client-2.1.0.jar:na]
at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:147) ~[nacos-client-2.1.0.jar:na]
at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:393) ~[nacos-client-2.1.0.jar:na]
at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:134) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.8.RELEASE.jar:2.2.8.RELEASE]

4、 Is there any document with nacos using ipv6

**Comment by sollhui** [comment]
you should use spring.cloud.nacos.discovery.ip-type=IPv6 first,and the reason of this error is that if do not config it,it would be consider the address as ipv4 defaultly

**Comment by wxjin** [comment]
> you should use spring.cloud.nacos.discovery.ip-type=IPv6 first,and the reason of this error is that if do not config it,it would be consider the address as ipv4 defaultly
 there is not the word "ip-type" in 2.2.8.RELEASE

**Comment by sollhui** [comment]
refer the example :https://github.com/alibaba/spring-cloud-alibaba/blob/2.2.x/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/src/main/resources/application.properties
and the word was defined in https://github.com/alibaba/spring-cloud-alibaba/blob/2.2.x/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java

**Comment by wxjin** [comment]
c.a.cloud.nacos.discovery.NacosWatch : namingService subscribe failed, properties:NacosDiscoveryProperties{serverAddr='[fe80::35ba:6827:c5ff:d161%11]:8848', endpoint='', namespace='6a3cda73-1e13-4ef9-b018-3be63387a30d', watchDelay=30000, logName='', service='ser-module', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='172.19.88.99', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, failFast=true}
1、NacosDiscoveryProperties does not ipType
2、And the code that change the tag with 2.2.8.RELEASE is not defined with ipType, the refer is
https://github.com/alibaba/spring-cloud-alibaba/blob/2.2.8.RELEASE/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java

**Comment by sollhui** [comment]
Sorry,it my mistake. 2.2.x version has not been released yet.2.2.8 version temporarily not supported the function and you can use it in next version.

**Comment by wxjin** [comment]
> when does the next version release ?  Can you tell me the plan?

**Comment by HHoflittlefish777** [comment]
it  need discussion，I will rely to you later.

**Comment by sollhui** [comment]
maybe @steverao can reply to you

**Comment by sollhui** [comment]
if you can't wait to use it ,you can refer the pr:https://github.com/alibaba/spring-cloud-alibaba/pull/2728

**Comment by wxjin** [comment]
>Thanks, if the new version is released, please tell me.

**Comment by steverao** [comment]
Please take care of informations of community, we plan to release new version in next week that can support IPv6 address registration.

**Comment by sollhui** [comment]
@wxjin hi, new version has released

**Comment by wxjin** [comment]
update the version and use spring.cloud.nacos.discovery.ip-type=IPv6 
however, the problem still exists.

2022-09-19 10:29:07.355 ERROR 32168 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, emdp-ftp register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='[fe80::35ba:6822:c5fe:d161%10]:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='emdp-ftp', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='[fe80:0:0:0:35ba:6822:c5fe:d161]', networkInterface='', port=7073, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, failFast=true}},

com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:128) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:114) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232) [spring-cloud-commons-3.1.0.jar:3.1.0]
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) [spring-cloud-starter-alibaba-nacos-discovery-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133) [spring-cloud-commons-3.1.0.jar:3.1.0]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98) [spring-cloud-commons-3.1.0.jar:3.1.0]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:86) [spring-cloud-commons-3.1.0.jar:3.1.0]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) [spring-cloud-commons-3.1.0.jar:3.1.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:46) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) [spring-context-5.3.15.jar:5.3.15]
	at java.lang.Iterable.forEach(Unknown Source) ~[na:1.8.0_171]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar:2.6.3]
	at com.cmcc.emdp.EmdpFtpApplication.main(EmdpFtpApplication.java:24) ~[classes/:na]
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:651) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:631) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:278) ~[nacos-client-2.1.0.jar:na]
	... 32 common frames omitted

**Comment by HHoflittlefish777** [comment]
it seem NacosDiscoveryProperties does not ipType info. NacosDiscoveryProperties{serverAddr='[fe80::35ba:6822:c5fe:d161%10]:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='emdp-ftp', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='[fe80:0:0:0:35ba:6822:c5fe:d161]', networkInterface='', port=7073, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, failFast=true}},

**Comment by HHoflittlefish777** [comment]
look at this  ip='[fe80:0:0:0:35ba:6822:c5fe:d161]',ipv6 address has been registered succussfully, is error happen when request？

**Comment by sollhui** [comment]
can you show your config properties?

**Comment by wxjin** [comment]
> can you show your config properties?

#\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
spring.cloud.nacos.discovery.ip-type=IPv6
spring.cloud.nacos.discovery.server-addr=[fe80::35ba:6822:c5fe:d161%10]:8848
#nacos\u8BBF\u95EE\u5730\u5740\u7684\u7528\u6237\u540D
spring.cloud.nacos.discovery.username=nacos
#nacos\u8BBF\u95EE\u5730\u5740\u7684\u5BC6\u7801ftpEcscommcarAddress
spring.cloud.nacos.discovery.password=nacos

**Comment by sollhui** [comment]
change spring.cloud.nacos.discovery.server-addr=[fe80::35ba:6822:c5fe:d161%10]:8848 to [fe80:0:0:0:35ba:6822:c5fe:d16]:8848 and try again

**Comment by wxjin** [comment]
> it is still the same error

**Comment by sollhui** [comment]
I don't know whether naocs support Ipv6 or not,how about change to 127.0.0.1:8848 or Ipv4 address?
