### ISSUE TITLE
Register a invalid IPv6 address 

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2802]
**Which Component**
eg. Nacos Discovery

**Describe the bug**
If I use `spring.cloud.inetutils.preferred-networks=00` to filter the invalid IPv6 address, it will return [127.0.0.1], that is a invalid IPv6 address.

![image](https://user-images.githubusercontent.com/25423978/192125318-78be0f59-5227-4021-af4e-a939efb3ce96.png)

If I call the service by [127.0.0.1], it will print error information like below:
```
java.net.URISyntaxException: Malformed IPv6 address at index 8: http://[127.0.0.1]:20003/c
	at java.net.URI$Parser.fail(URI.java:2845) ~[na:1.8.0_291]
	at java.net.URI$Parser.parseIPv6Reference(URI.java:3466) ~[na:1.8.0_291]
	at java.net.URI$Parser.parseServer(URI.java:3216) ~[na:1.8.0_291]
	at java.net.URI$Parser.parseAuthority(URI.java:3152) ~[na:1.8.0_291]
	at java.net.URI$Parser.parseHierarchical(URI.java:3094) ~[na:1.8.0_291]
	at java.net.URI$Parser.parse(URI.java:3050) ~[na:1.8.0_291]
	at java.net.URI.<init>(URI.java:673) ~[na:1.8.0_291]
```
So, I think if we can't find a valid IPv6 address, we should register a valid IPv4.

**Comment by pandaapo** [comment]
**I agree with you on "if we can't find a valid IPv6 address, we should register a valid IPv4".** I intend to modify code according to your opinion.

Additionally, I think method `findIPv6Address()` should not return IPv4,  which means method `findFirstNonLoopbackHostInfo()`(in class InetIPv6Util) should not. Otherwise, the result may contradict the method name and confuse developers.
