### ISSUE TITLE
org.springframework.context.annotation.AnnotationConfigApplicationContext has been closed already

### ISSUE THREAD

**Issue by SevenBlue2018** [alibaba/spring-cloud-alibaba#2848]
环境：
项目接入spring-cloud-starter-config 1.4.3.RELEASE，spring-cloud-alibaba-starter-nacos-discovery 1.5.1.RELEASE，spring-cloud-alibaba-starter-nacos-config 1.5.1.RELEASE
问题：
项目启动正常，当修改nacos配置中心的配置后，程序就会抛出AnnotationConfigApplicationContext has been closed already异常，具体信息如下：
`java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@301d5cec has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1064)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1079)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:283)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:177)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:140)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.nacosServicesWatch(NacosWatch.java:125)
	at com.alibaba.cloud.nacos.discovery.NacosWatch$1.run(NacosWatch.java:99)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`
代码跟进查看后，是nacos注册中心NacosWatch定时发布HeartbeatEvent事件，spring-cloud-config中DiscoveryClientConfigServiceBootstrapConfiguration类中注册了对HeartEvent事件的监听。当修改配置后，DiscoveryClientConfigServiceBootstrapConfiguration原本对应Context被关闭，导致抛出该异常

**Comment by steverao** [comment]
Nacos Watch logic caused the problem, `spring.cloud.nacos.discovery.watch.enabled=false` can help close the function. This is a old version problem and we solved in new version.
