### ISSUE TITLE
DefaultClusterServerInitFunc could not be instantiated

### ISSUE THREAD

**Issue by majestyjun** [alibaba/spring-cloud-alibaba#2898]
sentinel-dashboard  1.8.3
spring-cloud-starter-alibaba-sentinel 2021.0.1.0

客户端启动时报错：
RROR com.alibaba.csp.sentinel.cluster.server.init.DefaultClusterServerInitFunc could not be instantiated
2022-11-09 19:35:49.745 WARNING [InitExecutor] WARN: Initialization failed
com.alibaba.csp.sentinel.spi.SpiLoaderException: [com.alibaba.csp.sentinel.init.InitFunc]com.alibaba.csp.sentinel.cluster.server.init.DefaultClusterServerInitFunc could not be instantiated
        at com.alibaba.csp.sentinel.spi.SpiLoader.fail(SpiLoader.java:525)
        at com.alibaba.csp.sentinel.spi.SpiLoader.createInstance(SpiLoader.java:488)
        at com.alibaba.csp.sentinel.spi.SpiLoader.createInstance(SpiLoader.java:460)
        at com.alibaba.csp.sentinel.spi.SpiLoader.createInstanceList(SpiLoader.java:442)
        at com.alibaba.csp.sentinel.spi.SpiLoader.loadInstanceListSorted(SpiLoader.java:171)
        at com.alibaba.csp.sentinel.init.InitExecutor.doInit(InitExecutor.java:46)
        at com.alibaba.cloud.sentinel.custom.SentinelAutoConfiguration.init(SentinelAutoConfiguration.java:134)

偶发性报错，本地项目是好的，放到docker里面就会报，请问下这个原因有哪些？

**Comment by steverao** [comment]
It may be related to your environment, and we have not encountered it before.
