### ISSUE TITLE
No such extension org.apache.dubbo.metadata.report.MetadataReportFactory by name spring-cloud

### ISSUE THREAD

**Issue by maolicheng** [alibaba/spring-cloud-alibaba#2900]
environment：
alibaba-cloud 2.2.7.RELEASE
dubbo: 2.7.13

dubbo.registry.address=spring-cloud://localhost

issue detail:
java.lang.IllegalStateException: No such extension org.apache.dubbo.metadata.report.MetadataReportFactory by name spring-cloud, no related exception was found, please check whether related SPI module is missing.
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:649) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:656) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:445) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:429) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.metadata.report.MetadataReportFactory$Adaptive.getMetadataReport(MetadataReportFactory$Adaptive.java) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.metadata.report.MetadataReportInstance.init(MetadataReportInstance.java:60) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.startMetadataCenter(DubboBootstrap.java:647) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.initialize(DubboBootstrap.java:528) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:881) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70) ~[dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63) ~[dubbo-2.7.13.jar:2.7.13]
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52) ~[spring-context-support-1.0.11.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at com.mlc.ProjectServiceApplication.main(ProjectServiceApplication.java:18) [classes/:na]

**Comment by steverao** [comment]
We don't recommend to use Spring  Cloud Dubbo, you can export your dubbo interface by RESTful API.
