### ISSUE TITLE
When spring-boot application context closed sentinel still has some not closed  non-daemons  thread  

### ISSUE THREAD

**Issue by tobrainto** [alibaba/spring-cloud-alibaba#2920]
**Which Component**

spring-cloud-starter-alibaba-sentinel

**Describe the bug**

when I use `spring-cloud-starter-alibaba-sentine:2.2.9.RELEASE` with `sentinel-transport-netty-http` in my spring-boot application , the jvm can not exit when I call `actuator/shutdown` endpoint such as exec `curl -X POST http://ip:port/actuator/shutdown`.

This is because of `com.alibaba.csp.sentinel.transport.command.netty.HttpServer` thread has not closed  when the application context closed.

**To Reproduce**
1. run you local sentinel dashboard on port 8080
2. clone a simple demo such as `git clone git@github.com:tobrainto/sentinel-demo.git`
3. Run it in Intelllij IDEA  with  args 
```
-Dcsp.sentinel.dashboard.server=localhost:8080
-Dcsp.sentinel.api.port=8729
-Dproject.name=sentinel-demo
```
![image](https://user-images.githubusercontent.com/71546831/202891885-87390b64-702f-4177-b07c-c53affe45452.png)

4. exec `curl -X GET http://localhost:8090/hello` to trigger some init for sentinel 
5. exec  `curl -X POST http://localhost:8090/actuator/shutdown` to shutdown the application
6. you cannot find the info which mean the  process finished as blow.
```
Disconnected from the target VM, address: '127.0.0.1:59120', transport: 'socket'

Process finished with exit code 0
```
and you can see some non-daemon thread still alive
 ![image](https://user-images.githubusercontent.com/71546831/202894150-c4b1fd91-2576-4f27-b016-c91d1d401d2e.png)

**Expected behavior**
Process finished with exit code 0

**Additional context**
Java11 、spring-cloud-starter-alibaba-sentine:2.2.9.RELEASEE 、spring-boot:2.6.6

** Try fixed**
[I try to fixed it like this](https://github.com/alibaba/spring-cloud-alibaba/compare/2021.x...tobrainto:spring-cloud-alibaba:fix-sentinel-shutdown) 

```
@PreDestroy
private void destroy() {
    // Shutdown CommandCenter
    CommandCenter commandCenter = CommandCenterProvider.getCommandCenter();
    if (commandCenter != null) {
	    try {
		    commandCenter.stop();
	    }
	    catch (Exception e) {
		    log.warn("Sentinel CommandCenter shutdown error :", e);
	    }
    }
}
```
it work well except for a exception trace print 

```
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:328)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:253)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:404)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
	at com.alibaba.csp.sentinel.transport.command.netty.HttpServer.start(HttpServer.java:86)
	at com.alibaba.csp.sentinel.transport.command.NettyHttpCommandCenter$1.run(NettyHttpCommandCenter.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
so at the some  I think `channel.closeFuture().sync();` may need a try catch to ingore the unnecessary exception trace print 

 ![image](https://user-images.githubusercontent.com/71546831/202911890-11dfcd08-10e0-4dbc-bcef-e40375717e23.png)

thanks!

**Comment by yuhuangbin** [comment]
Maybe you can report it to the Sentinel community.

**Comment by tobrainto** [comment]
OK,Thanks @yuhuangbin 。If I don't care the exception trace print of `channel.closeFuture().sync();`, i try to fixed it in **spring-cloud-starter-alibaba-sentinel** like [this](https://github.com/alibaba/spring-cloud-alibaba/compare/2021.x...tobrainto:spring-cloud-alibaba:fix-sentinel-shutdown) 。

You don't think it's appropriate?

**Comment by yuhuangbin** [comment]
> OK,Thanks @yuhuangbin 。If I don't care the exception trace print of `channel.closeFuture().sync();`, i try to fixed it in **spring-cloud-starter-alibaba-sentinel** like [this](https://github.com/alibaba/spring-cloud-alibaba/compare/2021.x...tobrainto:spring-cloud-alibaba:fix-sentinel-shutdown) 。
> 
> You don't think it's appropriate?

This is not a good idea.
