### ISSUE TITLE
Graceful Shutdown Throw Exception

### ISSUE THREAD

**Issue by dczz** [alibaba/spring-cloud-alibaba#3093]
When using spring-cloud-stream-rocketmq, the version is 2021.1
Send System.exit(1); to report the stack, causing the program to delay exit.
After investigation, it is found that the Rocket-Client client has registered the ShutdownHook of jvm.

But the spring application will perform smartLifecycle.stop() when reclaiming resources. Repeatedly calling RocketMQListenerBindingContainer.stop()
Hope to optimize

使用spring-cloud-stream-rocketmq，版本为2021.1时 
发送System.exit(1);报出一下堆栈，导致程序延迟退出。
经过排查发现Rocket-Client客户端已经注册了jvm的ShutdownHook。

但是spring应用回收资源时会进行smartLifecycle.stop().重复调用了RocketMQListenerBindingContainer.stop()
希望优化一下

java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82) ~[na:na]
	at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:245) ~[na:na]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.removeShutdownHook(AsyncTraceDispatcher.java:202) ~[classes/:4.4.0]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.shutdown(AsyncTraceDispatcher.java:175) ~[classes/:4.4.0]
	at org.apache.rocketmq.client.consumer.DefaultMQPushConsumer.shutdown(DefaultMQPushConsumer.java:598) ~[rocketmq-client-4.4.0.jar:4.4.0]
	at com.alibaba.cloud.stream.binder.rocketmq.consuming.RocketMQListenerBindingContainer.stop(RocketMQListenerBindingContainer.java:193) ~[spring-cloud-starter-stream-rocketmq-2021.1.jar:2021.1]
	at com.alibaba.cloud.stream.binder.rocketmq.integration.RocketMQInboundChannelAdapter.doStop(RocketMQInboundChannelAdapter.java:129) ~[spring-cloud-starter-stream-rocketmq-2021.1.jar:2021.1]
	at org.springframework.integration.endpoint.AbstractEndpoint.stop(AbstractEndpoint.java:173) ~[spring-integration-core-5.5.14.jar:5.5.14]
	at org.springframework.cloud.stream.binder.DefaultBinding.stop(DefaultBinding.java:141) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:349) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindInputs(AbstractBindableProxyFactory.java:156) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:66) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:234) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1067) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145) ~[spring-boot-2.7.2.jar:2.7.2]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114) ~[spring-boot-2.7.2.jar:2.7.2]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by dczz** [comment]
org.apache.rocketmq.client.trace.AsyncTraceDispatcher  
  public void shutdown() {
        this.stopped = true;
        this.traceExecuter.shutdown();
        if (isStarted.get()) {
            traceProducer.shutdown();
        }
        this.removeShutdownHook();  //I think here just need to wait for the client to close, or catch and ignore the remove exception
    }

**Comment by yuluo-yx** [comment]
![72df1eae3819c211202fd6ef8c6d2987](https://user-images.githubusercontent.com/77964041/217136953-a30edb23-7503-4fc6-b254-f81f175e30a6.png)
![4875a6632190f7de3914d8165a8d50aa](https://user-images.githubusercontent.com/77964041/217137016-4703acea-3a18-4e36-b5c4-5ccef274a688.png)
这个地方返回的是true，Spring的DefaultLifecycleProcessor会认为这个SmartLifecycle没有stop完成，等待30s，但是这个类实现了SmartLifecycle和RocketMQListenerContainer接口,分别实现了stop()和destroy()方法， 进行双重关闭，如果和destroy()先执行了，则将running设置为false，不在执行stop()。
