### ISSUE TITLE
use spring-data-redis & nacos with the latest version error

### ISSUE THREAD

**Issue by pupupupu1** [alibaba/spring-cloud-alibaba#3158]
Hi:
    when i use the srping-data-redis:3.0.1 or spring-cloud-starter-alibaba-nacos-discovery:2022.0.0.0-RC1 ,their can work for mvn -Pnative clean spring-boot:build-image.
    but when i both to use them,native-image will throw error :
_[INFO]     [creator]     Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.netty.channel.nio.AbstractNioChannel.<init>(io.netty.channel.Channel, java.nio.channels.SelectableChannel, int)
[INFO]     [creator]     Parsing context:
[INFO]     [creator]        at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:80)
[INFO]     [creator]        at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
[INFO]     [creator]
[INFO]     [creator]            at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
[INFO]     [creator]            at com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:61)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
[INFO]     [creator]            at com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
[INFO]     [creator]            at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
[INFO]     [creator]            at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[INFO]     [creator]     Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of ch.qos.logback.classic.Logger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=ch.qos.logback.classic.Logger.
[INFO]     [creator]            at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:132)
[INFO]     [creator]            at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:595)
[INFO]     [creator]            at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:177)
[INFO]     [creator]            at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:148)
[INFO]     [creator]            at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:100)
[INFO]     [creator]            at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:79)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil$1.readValue(ConstantFoldUtil.java:55)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.spi.JavaConstantFieldProvider.readConstantField(JavaConstantFieldProvider.java:78)
[INFO]     [creator]            at com.oracle.svm.hosted.ameta.AnalysisConstantFieldProvider.readConstantField(AnalysisConstantFieldProvider.java:72)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil.tryConstantFold(ConstantFoldUtil.java:51)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.LoadFieldNode.asConstant(LoadFieldNode.java:178)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.LoadFieldNode.canonical(LoadFieldNode.java:144)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.LoadFieldNode.canonical(LoadFieldNode.java:135)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.LoadFieldNode.canonical(LoadFieldNode.java:72)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.spi.Canonicalizable$Unary.canonical(Canonicalizable.java:101)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.SimplifyingGraphDecoder.canonicalizeFixedNode(SimplifyingGraphDecoder.java:214)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.canonicalizeFixedNode(PEGraphDecoder.java:1572)
[INFO]     [creator]            at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.canonicalizeFixedNode(InlineBeforeAnalysis.java:192)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.SimplifyingGraphDecoder.handleFixedNode(SimplifyingGraphDecoder.java:193)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:821)
[INFO]     [creator]            at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:240)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:548)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:833)
[INFO]     [creator]            at com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:98)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:179)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
[INFO]     [creator]            ... 13 more
[INFO]     [creator]     --------------------------------------------------------------------------------
[INFO]     [creator]         1.6s (2.7% of total time) in 21 GCs | Peak RSS: 3.06GB | CPU load: 3.36
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     Failed generating '/layers/paketo-buildpacks_native-image/native-image/com.pjm.boot3demo1.Boot3Demo1Application' after 57.9s.
[INFO]     [creator]     Error: Image build request failed with exit status 1
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1_

    i find the nacos-client.jar and netty.jar,the /META-INF/native-image maybe was a conflict，but i can not understand it, i need yours help ,thanks!

    this is my example project url: https://github.com/pupupupu1/boot3-demo1
    
    my java version is 
`root@pjmpjmpjm:/mnt/d/ybs/stream/boot3-demo1# java -version
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07, mixed mode, sharing)`

简而言之我单独集成spring-data-redis或者spring-cloud-alibaba-nacos是可以成功打包编译发布的，但是一起集成会编译失败，目前只能知道是netty模块的问题。

**Comment by ruansheng8** [comment]
See #3141 , this issue may solve your problem.

**Comment by pupupupu1** [comment]
> See #3141 , this issue may solve your problem.

i see it,but i it still can not work,
`<plugin>`
           ` <groupId>org.graalvm.buildtools</groupId>`
            `<artifactId>native-maven-plugin</artifactId>`
            `<configuration>`
            `  <buildArgs>`
              `  --verbose`
                `--exclude-config nacos-client.*.jar META-INF/native-image/.*.properties`
              `</buildArgs>`
            `</configuration>`
          `</plugin>`
update the  native-image configuration can not take effect ，i have searched issues for a week hahah

**Comment by pupupupu1** [comment]
> See #3141 , this issue may solve your problem.

i find that when i use netty:4.1.85 and nacos-client:2.2.1-RC, native-image will not compile the nacos-client code.

**com.alibaba.nacos.api.exception.NacosException: com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public void com.alibaba.nacos.api.remote.response.Response.setMessage(java.lang.String)
        at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:690) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:619) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:356) ~[na:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:310) ~[na:na]
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForSubscribe(RedoScheduledTask.java:127) ~[na:na]
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForSubscribes(RedoScheduledTask.java:108) ~[na:na]
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.run(RedoScheduledTask.java:52) ~[na:na]
        at java.base@17.0.6/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base@17.0.6/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at java.base@17.0.6/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base@17.0.6/java.lang.Thread.run(Thread.java:833) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203) ~[na:na]
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public void com.alibaba.nacos.api.remote.response.Response.setMessage(java.lang.String)
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
        at java.base@17.0.6/java.lang.reflect.Method.acquireMethodAccessor(Method.java:76) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:566) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141) ~[na:na]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[com.pjm.boot3demo2.Boot3Demo2Application:2.14.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[com.pjm.boot3demo2.Boot3Demo2Application:2.14.1]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[com.pjm.boot3demo2.Boot3Demo2Application:2.14.1]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730) ~[com.pjm.boot3demo2.Boot3Demo2Application:2.14.1]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3714) ~[com.pjm.boot3demo2.Boot3Demo2Application:2.14.1]
        at com.alibaba.nacos.common.utils.JacksonUtils.toObj(JacksonUtils.java:125) ~[na:na]
        at com.alibaba.nacos.common.remote.client.grpc.GrpcUtils.parse(GrpcUtils.java:126) ~[na:na]
        at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection.request(GrpcConnection.java:81) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:641) ~[com.pjm.boot3demo2.Boot3Demo2Application:na]
        ... 14 common frames omitted**

**Comment by steverao** [comment]
From your error log information, it seems you don't provide hints configuration files. You can refer to [document](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.using-the-tracing-agent.launch) to generate relevant files.

**Comment by pupupupu1** [comment]
> From your error log information, it seems you don't provide hints configuration files. You can refer to [document](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.using-the-tracing-agent.launch) to generate relevant files.

Hi Bro,It Can Work With mvn -Pnative native:compile，But can not work with mvn -Pnative springboot:build-image,Look like 
/META-INF/native-images/files not loaded in building time. The error log from springboot:build-image T_T

**Comment by pupupupu1** [comment]
@steverao @ruansheng8 
Hi All:
     finally i use spring-data-redis exclude lettuce and import jedis，it worked! thanks.
     i think the nacos-client can not compatible with netty at native compile env.
