### ISSUE TITLE
SCA Sentinel OpenFeign support AOT compilation by using GraalVM

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3174]
**Which Component**
eg. Sentinel

**Is your feature request related to a problem? Please describe.**
Support static compilation by using GraalVM 

**Describe the solution you'd like**
OpenFeign client support AOT compilation in GraalVM 

**Describe alternatives you've considered**
I am dealing with related ability adaptation. I have encountered some problems. Interested students can come in and see how to solve them. Steps to reproduce related problems:

1. Enter the example module of sentinel-openfeign-example in branch of 2022.x. type the following command `mvn clean -Pnative spring-boot:run` to scanning the application so order to get hint files.
2. Enter following command `while true;do curl 127.0.0.1:18087/get; sleep 0.1;echo "";done;` in your terminal to request the service.  Everything is alright, you can see the result like below, it means Flow Control from Sentinel is work!
![image](https://user-images.githubusercontent.com/25423978/218256825-cc52caa9-d20e-4d0f-82cd-02300d404e38.png)
3. Finally, please enter following command `mvn clean -Pnative native:compile` to static compile the code. it will report error information like below:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testController': Unsatisfied dependency expressed through field 'httpbinClient': Error creating bean with name 'com.alibaba.cloud.examples.configuration.HttpbinClient': Post-processing of FactoryBean's singleton object failed
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveValue(AutowiredFieldValueResolver.java:195) ~[na:na]
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveAndSet(AutowiredFieldValueResolver.java:167) ~[na:na]
        at com.alibaba.cloud.examples.controller.TestController__Autowiring.apply(TestController__Autowiring.java:14) ~[na:na]
        at org.springframework.beans.factory.support.InstanceSupplier$1.get(InstanceSupplier.java:82) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[sentinel-openfeign-example:3.0.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[sentinel-openfeign-example:3.0.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[sentinel-openfeign-example:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[sentinel-openfeign-example:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[sentinel-openfeign-example:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[sentinel-openfeign-example:3.0.0]
        at com.alibaba.cloud.examples.OpenFeignApplication.main(OpenFeignApplication.java:34) ~[sentinel-openfeign-example:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.cloud.examples.configuration.HttpbinClient': Post-processing of FactoryBean's singleton object failed
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:108) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1823) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1265) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:259) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1628) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1585) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1368) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveValue(AutowiredFieldValueResolver.java:189) ~[na:na]
        ... 22 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface com.alibaba.cloud.examples.configuration.HttpbinClient, interface java.io.Serializable] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:171) ~[na:na]
        at java.base@17.0.5/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:47) ~[sentinel-openfeign-example:na]
        at java.base@17.0.5/java.lang.reflect.Proxy.getProxyClass(Proxy.java:398) ~[sentinel-openfeign-example:na]
        at org.springframework.util.ClassUtils.createCompositeInterface(ClassUtils.java:783) ~[na:na]
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.getTargetShadowMatch(AspectJExpressionPointcut.java:432) ~[na:na]
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.matches(AspectJExpressionPointcut.java:290) ~[na:na]
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:251) ~[na:na]
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:288) ~[na:na]
        at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:320) ~[na:na]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:128) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:97) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:78) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:366) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:318) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:435) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1866) ~[sentinel-openfeign-example:6.0.2]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:105) ~[sentinel-openfeign-example:6.0.2]
        ... 32 common frames omitted

```
By the way, I found it contains the configuration of `com.alibaba.cloud.examples.configuration.HttpbinClient` in proxy-config.json. I also found if I remove below dependency, the example can be static compiled correctly. So the problem may be caused by JDK dynamic proxy in it.
```
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
</dependency>

```

**Comment by steverao** [comment]
We solved it in #3184 and close now.
