### ISSUE TITLE
Spring Cloud Config ERROR：NacosPropertySourceBuilder parse data from Nacos error

### ISSUE THREAD

**Issue by zhengwe** [alibaba/spring-cloud-alibaba#3213]
Spring Boot Version: 2.6.3
Spring Cloud Version: 2021.0.1
Spring Cloud Alibaba Version: 2021.0.1.0
Nacos Server Version: 2.1.2

Application launch specified utf-8，The application reads the configuration file and reports the error as follows：
ERROR 1 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : parse data from Nacos error,dataId:xxx.yml,data:spring:
**** The log here prints the application configuration file details ****
java.lang.ArrayIndexOutOfBoundsException: -1
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:634) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.29.jar!/:na]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:135) ~[snakeyaml-1.29.jar!/:na]
        at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:514) ~[snakeyaml-1.29.jar!/:na]
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:198) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at com.alibaba.cloud.nacos.parser.NacosDataParserHandler.parseNacosData(NacosDataParserHandler.java:92) ~[spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:97) [spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:73) [spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) [spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) [spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:141) [spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103) [spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) [spring-cloud-context-3.1.1.jar!/:3.1.1]
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) [spring-cloud-context-3.1.1.jar!/:3.1.1]
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) [spring-cloud-context-3.1.1.jar!/:3.1.1]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:612) [spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:380) [spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) [spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.6.3.jar!/:2.6.3]
        at com.lianlian.channel.syn.product.server.ProductSynApp.main(ProductSynApp.java:19) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_345]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_345]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_345]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_345]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app.jar:na]

**Comment by zhengwe** [comment]
Nacos Server display pull ok！

**Comment by steverao** [comment]
For your error logs, this problem is related to your configuration content, is it convenient to post your configuration content?

**Comment by zhengwe** [comment]
this is my configuration content:
spring:
  config:
    activate:
      on-profile:
        - prod
  application:
    name: xxx
  cloud:
    nacos:
      config:
        server-addr: xxx
        namespace: xxx
        file-extension: yaml
        group: DEFAULT_GROUP
        prefix: xxx.yml
        refresh-enabled: true
