### ISSUE TITLE
java.lang.RuntimeException: ErrCode:-400, ErrMsg:Could not initialize class com.alibaba.nacos.client.naming.remote.http.NamingHttpClientManager

### ISSUE THREAD

**Issue by a496046961** [alibaba/spring-cloud-alibaba#3215]
springcloud alibaba 版本是2021.0.4.0
nacos 版本是NACOS 2.2.0
springboot版本是2.6.11

配置了以后启动项目老是报上面这个错是什么原因

java.lang.RuntimeException: ErrCode:-400, ErrMsg:Could not initialize class com.alibaba.nacos.client.naming.remote.http.NamingHttpClientManager

Caused by: com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:61)
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77)
	at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:99)
	... 27 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59)
	... 29 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.nacos.client.naming.remote.http.NamingHttpClientManager
	at com.alibaba.nacos.client.naming.core.ServerListManager.<init>(ServerListManager.java:59)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:70)
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:95)
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:81)
	... 34 common frames omitted

org.springframework.context.ApplicationContextException: Failed to start bean 'nacosWatch'; nested exception is java.lang.RuntimeException: ErrCode:-400, ErrMsg:org.apache.http.nio.reactor.IOReactorException

**Comment by steverao** [comment]
Can you provide a simplest demo to help us reproduce the problem?
