### ISSUE TITLE
spring-cloud-alibaba-sidecar-nacos-example test failed in 2022.x

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3257]
**Which Component**
integrated-example spring-cloud-alibaba-sidecar-nacos-example

**Describe the bug**
In starting the example of `node - service. js heterogeneous service` and `DemoApplication`, after visiting `http://127.0.0.1:8070/node-service/health.json` no results.And the browser reports a 503 exception.
![image](https://user-images.githubusercontent.com/77964041/230772504-2766227e-9bb1-4815-9f18-01713ed24a3b.png)
The check URL for the heterogeneous service is available.
![image](https://user-images.githubusercontent.com/77964041/230772569-daab1b19-1f36-4976-b4ca-4b485539d339.png)

**Simplest demo**
https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples

**To Reproduce**
Refer to the [readme](https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/readme-zh.md) documentation

**Screenshots**
Service successfully registered with nacos.
The heterogeneous service is started successfully.
![image](https://user-images.githubusercontent.com/77964041/230772370-18e0e7d7-defc-4313-85f3-c3e4945c14b3.png)
![image](https://user-images.githubusercontent.com/77964041/230772357-35c525bf-cad0-46d0-82f9-d8d79f765b76.png)

**Additional context**
Spring Cloud Alibaba 2022.x nacos 2.2.x, win10, node.js16.16.0

**Comment by dong-xin** [comment]
遇到相同的问题：

**步骤1**：Spring boot服务启动
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/52731595/231976234-bd63c3bd-bb30-4e5b-8e27-eeed711c7c01.png">

**步骤2**：验证node服务
访问http://localhost:8060/后，可以正常返回{"index":"已进入首页"}，表明node-service.js启动成功。
![image](https://user-images.githubusercontent.com/52731595/231975333-6bd4e239-18e9-4ee8-b52d-fe2812525925.png)

**步骤3**：验证Spring boot服务
访问http://localhost:8090/，浏览器显示404。
![image](https://user-images.githubusercontent.com/52731595/231975984-36593bfc-0764-435c-b148-1a113ee2523f.png)
访问http://localhost:8090/sidecar-service/，浏览器显示503。
![image](https://user-images.githubusercontent.com/52731595/231982151-8d898167-3acb-49b7-83d4-0cab783c8327.png)

问题排查：
服务注册到nacos的是以sidecar.ip和sidecar.port的形式，非spring bootd的server.port注册，导致访问8090端口出错。
![image](https://user-images.githubusercontent.com/52731595/231977915-1e13e9a7-229b-476d-bd9f-8068a187eeb3.png)

application.yml配置文件：
<img width="552" alt="image" src="https://user-images.githubusercontent.com/52731595/231978764-3148a762-3063-44c8-af4f-f28f4395d588.png">

运行环境：
Spring Cloud Alibaba 2021.0.5.0、Spring Boot 2.6.13、Nacos 2.0.3、MacOS Big Sur 11.1

**Comment by yuluo-yx** [comment]
> 遇到相同的问题：
> 
> **步骤1**：Spring boot服务启动 <img alt="image" width="1032" src="https://user-images.githubusercontent.com/52731595/231976234-bd63c3bd-bb30-4e5b-8e27-eeed711c7c01.png">
> 
> **步骤2**：验证node服务 访问[http://localhost:8060/后，可以正常返回{"index":"已进入首页"}，表明node-service.js启动成功。](http://localhost:8060/%E5%90%8E%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%BF%94%E5%9B%9E%7B%22index%22:%22%E5%B7%B2%E8%BF%9B%E5%85%A5%E9%A6%96%E9%A1%B5%22%7D%EF%BC%8C%E8%A1%A8%E6%98%8Enode-service.js%E5%90%AF%E5%8A%A8%E6%88%90%E5%8A%9F%E3%80%82) ![image](https://user-images.githubusercontent.com/52731595/231975333-6bd4e239-18e9-4ee8-b52d-fe2812525925.png)
> 
> **步骤3**：验证Spring boot服务 访问[http://localhost:8090/，浏览器显示404。](http://localhost:8090/%EF%BC%8C%E6%B5%8F%E8%A7%88%E5%99%A8%E6%98%BE%E7%A4%BA404%E3%80%82) ![image](https://user-images.githubusercontent.com/52731595/231975984-36593bfc-0764-435c-b148-1a113ee2523f.png) 访问[http://localhost:8090/sidecar-service/，浏览器显示503。](http://localhost:8090/sidecar-service/%EF%BC%8C%E6%B5%8F%E8%A7%88%E5%99%A8%E6%98%BE%E7%A4%BA503%E3%80%82) ![image](https://user-images.githubusercontent.com/52731595/231982151-8d898167-3acb-49b7-83d4-0cab783c8327.png)
> 
> 问题排查： 服务注册到nacos的是以sidecar.ip和sidecar.port的形式，非spring bootd的server.port注册，导致访问8090端口出错。 ![image](https://user-images.githubusercontent.com/52731595/231977915-1e13e9a7-229b-476d-bd9f-8068a187eeb3.png)
> 
> application.yml配置文件： <img alt="image" width="552" src="https://user-images.githubusercontent.com/52731595/231978764-3148a762-3063-44c8-af4f-f28f4395d588.png">
> 
> 运行环境： Spring Cloud Alibaba 2021.0.5.0、Spring Boot 2.6.13、Nacos 2.0.3、MacOS Big Sur 11.1

You can try running sidecar-example for the 2.2.x branch. He works fine.
![image](https://user-images.githubusercontent.com/77964041/232005356-89c87874-1a05-43f1-a4bc-35d51886e3dd.png)
![image](https://user-images.githubusercontent.com/77964041/232005408-0f5dfd87-f74f-4fb0-b872-b75755361f26.png)

**Comment by dong-xin** [comment]
感谢您的回复，但目前的正在运行服务版本都是基于spring boot 2.x、java 1.8，要升级到2022.x，需要将Spring boot 升为3.0、java 17+，最终还是希望能够修复此版本的问题，谢谢。

**Comment by yuluo-yx** [comment]
2021.x 也存在此问题！

**Comment by yuluo-yx** [comment]
@dong-xin 问题已经修复，可以参考 #3266

**Comment by dong-xin** [comment]
> @dong-xin 问题已经修复，可以参考 #3266

感谢，刚按照您的Pull Request代码，现已调试成功，辛苦！赞👍

**Comment by yuluo-yx** [comment]
> > @dong-xin 问题已经修复，可以参考 #3266
> 
> 感谢，刚按照您的Pull Request代码，现已调试成功，辛苦！赞👍

I'm glad to help you!

**Comment by Lzzzii10** [comment]
您好，我根据https://github.com/alibaba/spring-cloud-alibaba/pull/3266 改过之后，再次运行 出现此错误，请教一下，十分感谢

2024-01-02T10:28:40.257096446Z 
2024-01-02T10:28:40.257193842Z   .   ____          _            __ _ _
2024-01-02T10:28:40.257202504Z  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2024-01-02T10:28:40.257208584Z ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2024-01-02T10:28:40.257214130Z  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2024-01-02T10:28:40.257219432Z   '  |____| .__|_| |_|_| |_\__, | / / / /
2024-01-02T10:28:40.257224734Z  =========|_|==============|___/=/_/_/_/
2024-01-02T10:28:40.258848571Z  :: Spring Boot ::                (v2.4.2)
2024-01-02T10:28:40.258887250Z 
2024-01-02T10:28:40.402020208Z 2024-01-02 10:28:40.397  INFO 1 --- [           main] com.mx.teldxboot.TelDxBootApplication    : Starting TelDxBootApplication v0.0.1-SNAPSHOT using Java 1.8.0_111 on 2a9f7384ce14 with PID 1 (/tel-dx-boot-0.0.1-SNAPSHOT.jar started by root in /)
2024-01-02T10:28:40.402719817Z 2024-01-02 10:28:40.402  INFO 1 --- [           main] com.mx.teldxboot.TelDxBootApplication    : No active profile set, falling back to default profiles: default
2024-01-02T10:28:41.608527750Z 2024-01-02 10:28:41.607 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2024-01-02T10:28:41.608565972Z 
2024-01-02T10:28:41.608570244Z java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.autoconfigure.RefreshAutoConfiguration.refreshScope
2024-01-02T10:28:41.608574278Z 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608579020Z 	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608582887Z 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:193) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608586946Z 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:153) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608591135Z 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608594958Z 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:348) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608598767Z 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:252) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608614459Z 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:285) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608618897Z 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:99) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608624886Z 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608628688Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608632288Z 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608636580Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608640128Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608643473Z 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608646893Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608650206Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608654134Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608657572Z 	at com.mx.teldxboot.TelDxBootApplication.main(TelDxBootApplication.java:13) [classes!/:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.608681209Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
2024-01-02T10:28:41.608686698Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
2024-01-02T10:28:41.608692384Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
2024-01-02T10:28:41.608697889Z 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
2024-01-02T10:28:41.608703512Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.608746730Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.608753642Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.608760387Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.608778928Z Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.alibaba.cloud.sidecar.SidecarAutoConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@41cf53f9]
2024-01-02T10:28:41.608785853Z 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608791843Z 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358) ~[spring-core-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608798218Z 	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414) ~[spring-core-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608804181Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:754) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608810394Z 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688) ~[na:1.8.0_111]
2024-01-02T10:28:41.608816200Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:753) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608822487Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:692) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608828661Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:663) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608834504Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608840451Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608846530Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608853830Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:238) ~[spring-boot-autoconfigure-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608860017Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:231) ~[spring-boot-autoconfigure-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608866161Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:221) ~[spring-boot-autoconfigure-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608871973Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:169) ~[spring-boot-autoconfigure-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608878000Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:144) ~[spring-boot-autoconfigure-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608888156Z 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.608894286Z 	... 26 common frames omitted
2024-01-02T10:28:41.608899597Z Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/health/HealthIndicator
2024-01-02T10:28:41.608905120Z 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_111]
2024-01-02T10:28:41.608910752Z 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_111]
2024-01-02T10:28:41.608916418Z 	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_111]
2024-01-02T10:28:41.608921910Z 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.608962954Z 	... 42 common frames omitted
2024-01-02T10:28:41.608969562Z Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.health.HealthIndicator
2024-01-02T10:28:41.608975361Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111]
2024-01-02T10:28:41.608981114Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]
2024-01-02T10:28:41.608986753Z 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.608992720Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]
2024-01-02T10:28:41.608998279Z 	... 46 common frames omitted
2024-01-02T10:28:41.609003564Z 
2024-01-02T10:28:41.618553742Z 2024-01-02 10:28:41.618  WARN 1 --- [           main] o.s.boot.SpringApplication               : Unable to close ApplicationContext
2024-01-02T10:28:41.618600661Z 
2024-01-02T10:28:41.618607884Z java.lang.IllegalStateException: Failed to introspect Class [com.alibaba.cloud.sidecar.SidecarAutoConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@41cf53f9]
2024-01-02T10:28:41.618614405Z 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618620656Z 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358) ~[spring-core-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618626559Z 	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414) ~[spring-core-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618632388Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:754) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618643245Z 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688) ~[na:1.8.0_111]
2024-01-02T10:28:41.618649272Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:753) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618712916Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:692) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618720813Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:663) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618726920Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618732827Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618798359Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618823635Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:667) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618834050Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659) ~[spring-beans-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618926754Z 	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1305) ~[spring-context-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.618944209Z 	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:899) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.618950396Z 	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:887) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.618956209Z 	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:874) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.618961895Z 	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:815) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.618973564Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:336) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.618979584Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.618985290Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.2.jar!/:2.4.2]
2024-01-02T10:28:41.618990912Z 	at com.mx.teldxboot.TelDxBootApplication.main(TelDxBootApplication.java:13) [classes!/:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.618998502Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
2024-01-02T10:28:41.619003894Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
2024-01-02T10:28:41.619048150Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
2024-01-02T10:28:41.619074871Z 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
2024-01-02T10:28:41.619080033Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.619083579Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.619086662Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.619090458Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.619093647Z Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/health/HealthIndicator
2024-01-02T10:28:41.619098975Z 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_111]
2024-01-02T10:28:41.619102220Z 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_111]
2024-01-02T10:28:41.619105234Z 	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_111]
2024-01-02T10:28:41.619109664Z 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.3.jar!/:5.3.3]
2024-01-02T10:28:41.619112844Z 	... 29 common frames omitted
2024-01-02T10:28:41.619117396Z Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.health.HealthIndicator
2024-01-02T10:28:41.621022224Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111]
2024-01-02T10:28:41.621319294Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]
2024-01-02T10:28:41.621331875Z 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[tel-dx-boot-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-01-02T10:28:41.621342284Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]
2024-01-02T10:28:41.621352303Z 	... 33 common frames omitted
2024-01-02T10:28:41.621358794Z

**Comment by wangliuliu1115** [comment]
> > @dong-xin 问题已经修复，可以参考 #3266
> 
> 感谢，刚按照您的Pull Request代码，现已调试成功，辛苦！赞 👍

上午好同学，请问你最终是怎么解决的呢，期待您的回复！

**Comment by wangliuliu1115** [comment]
> > > @dong-xin 问题已经修复，可以参考 #3266
> > 
> > 
> > 感谢，刚按照您的Pull Request代码，现已调试成功，辛苦！赞 👍
> 
> 上午好同学，请问你最终是怎么解决的呢，期待您的回复！

sidecar升级到2021.0.6.1版本后解决
