### ISSUE TITLE
Why can't SCS use binder.environment property to customize rokcetmq？

### ISSUE THREAD

**Issue by zwzdream** [alibaba/spring-cloud-alibaba#3273]
Why can't SCS use bindery.environment property to customize rokcetmq？

1.This is my configuration:
```
spring:
  cloud:
    stream:
      binders:
        rocketmqOne:
          type: rocketmq
          environment:
            spring:
              cloud:
                stream:
                  rocketmq:
                    binder:
                      name-server: 10.10.80.80:9876
      bindings:
        output: 
          destination: kafka-one 
          binder: rocketmqOne
        input: 
          destination: kafka-one  
          binder: rocketmqOne
          group: kafka-one-c0 
```
2.This is  startup log：
```
2023-04-19 20:56:52.378  INFO 37264 --- [tWorkerThread_4] RocketmqRemoting                         : NETTY CLIENT PIPELINE: CLOSE
2023-04-19 20:56:52.381  INFO 37264 --- [tWorkerThread_4] RocketmqRemoting                         : eventCloseChannel: the channel[null] has been removed from the channel table before
2023-04-19 20:56:52.382  INFO 37264 --- [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[] result: true
2023-04-19 20:56:52.382  WARN 37264 --- [ebalanceService] RocketmqClient                           : updateTopicRouteInfoFromNameServer Exception

org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to <null> failed
at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:392) ~[rocketmq-remoting-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1212) ~[rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1202) ~[rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:605) [rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:492) [rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.factory.MQClientInstance.findConsumerIdList(MQClientInstance.java:1069) [rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:262) [rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:225) [rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:994) [rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:959) [rocketmq-client-4.4.0.jar:4.4.0]
at org.apache.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:41) [rocketmq-client-4.4.0.jar:4.4.0]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]

2023-04-19 20:56:52.383  WARN 37264 --- [ebalanceService] RocketmqClient                           : doRebalance, kafka-one-c0, but the topic[kafka-one] not exist.
2023-04-19 20:56:52.383  INFO 37264 --- [ScheduledThread] RocketmqRemoting                         : new name server is chosen. OLD: 127.0.0.1:9876 , NEW: 127.0.0.1:9876. namesrvIndex = 93
2023-04-19 20:56:52.383  INFO 37264 --- [           main] RocketmqClient                           : Created a new client Instance, InstanceIndex:1, ClientID:2.0.0.1@PID_CLIENT_INNER_TRACE_PRODUCER_10.10.80.80:9876, ClientConfig:ClientConfig [namesrvAddr=10.10.80.80:9876, clientIP=2.0.0.1, instanceName=PID_CLIENT_INNER_TRACE_PRODUCER_10.10.80.80:9876, clientCallbackExecutorThreads=12, pollNameServerInterval=30000, heartbeatBrokerInterval=30000, persistConsumerOffsetInterval=5000, unitMode=false, unitName=null, vipChannelEnabled=false, useTLS=false, language=JAVA], ClientVersion:V4_4_0, SerializerType:JSON
2023-04-19 20:56:52.384  WARN 37264 --- [ebalanceService] RocketmqClient                           : doRebalance, kafka-one-c0 kafka-one, get consumer id list failed
2023-04-19 20:56:52.384  INFO 37264 --- [           main] RocketmqClient                           : Created new MQClientInstance for clientId:[2.0.0.1@PID_CLIENT_INNER_TRACE_PRODUCER_10.10.80.80:9876]
2023-04-19 20:56:53.405  INFO 37264 --- [ScheduledThread] RocketmqRemoting                         : createChannel: begin to connect remote host[127.0.0.1:9876] asynchronously
2023-04-19 20:56:53.407  INFO 37264 --- [ebalanceService] RocketmqClient                           : RebalanceService service started
2023-04-19 20:56:53.407  INFO 37264 --- [lMessageService] RocketmqClient                           : PullMessageService service started
2023-04-19 20:56:54.005  INFO 37264 --- [tWorkerThread_1] RocketmqRemoting                         : NETTY CLIENT PIPELINE: CONNECT  UNKNOWN => 127.0.0.1:9876
2023-04-19 20:56:54.005  INFO 37264 --- [           main] RocketmqClient                           : the producer [CLIENT_INNER_PRODUCER] start OK. sendMessageWithVIPChannel=false
2023-04-19 20:56:54.005  INFO 37264 --- [ScheduledThread] RocketmqRemoting                         : new name server is chosen. OLD: null , NEW: 10.10.80.80:9876. namesrvIndex = 172
2023-04-19 20:56:54.006  INFO 37264 --- [           main] RocketmqClient                           : the client factory [2.0.0.1@PID_CLIENT_INNER_TRACE_PRODUCER_10.10.80.80:9876] start OK
2023-04-19 20:56:54.006  INFO 37264 --- [           main] RocketmqClient                           : the producer [_INNER_TRACE_PRODUCER] start OK. sendMessageWithVIPChannel=false
2023-04-19 20:56:54.008  INFO 37264 --- [ScheduledThread] RocketmqRemoting                         : createChannel: begin to connect remote host[10.10.80.80:9876] asynchronously
2023-04-19 20:56:54.013  INFO 37264 --- [tWorkerThread_1] RocketmqRemoting                         : NETTY CLIENT PIPELINE: CONNECT  UNKNOWN => 10.10.80.80:9876
2023-04-19 20:56:54.013  INFO 37264 --- [           main] s.b.r.c.RocketMQListenerBindingContainer : running container: RocketMQListenerBindingContainer{consumerGroup='kafka-one-c0', nameServer='[10.10.80.80:9876]', topic='kafka-one', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='null', messageModel=CLUSTERING}
2023-04-19 20:56:54.014  INFO 37264 --- [           main] .c.s.b.r.i.RocketMQInboundChannelAdapter : started com.alibaba.cloud.stream.binder.rocketmq.integration.RocketMQInboundChannelAdapter@646d810b
2023-04-19 20:56:54.040  INFO 37264 --- [ScheduledThread] RocketmqRemoting                         : createChannel: connect remote host[10.10.80.80:9876] success, AbstractBootstrap$PendingRegistrationPromise@7cae1c10(success)
2023-04-19 20:56:54.131  INFO 37264 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
```
Why are there two channels instead of coverage?And when  sending messages, always use the default configuration : new name server is chosen. OLD: 127.0.0.1:9876

**Comment by LeBW** [comment]
Please use the configuration that we recommend in the document.
for example:
```
spring:
  application:
    name: rocketmq-broadcast-consumer1-example
  cloud:
    stream:
      function:
        definition: consumer;
      rocketmq:
        binder:
          name-server: rmq-cn-49829aza.cn-hangzhou.rmq.aliyuncs.com:8080
      bindings:
        consumer-in-0:
          destination: pollable
          group: broadcast-consumer
```
