### ISSUE TITLE
RocketMQ throw a NoClassDefException sometimes

### ISSUE THREAD

**Issue by LeBW** [alibaba/spring-cloud-alibaba#3278]
**Which Component**
RocketMQ
spring-boot-dependencies：2.3.7.RELEASE
spring-cloud-alibaba-dependencies：2.2.9.RELEASE
```
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
    <version>2.2.9.RELEASE</version>
</dependency>
```

**Describe the bug**
When  using rocketmq-stream component, An exception may occur sometimes.
The exception comes from a RocketMQ user, and can't be reproduced in my computer.
We believe it's relevant to a bug in JDK,   https://bugs.openjdk.org/browse/JDK-8148560
Maybe we can change the lambda expression to inner class. It will not influence the functionality, but has better compatibility.

Below is the exception message
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR][2023-03-14 13:45:45] [traceId-] [main-org.springframework.boot.SpringApplication--837 line]  - Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.NoClassDefFoundError: com/alibaba/cloud/stream/binder/rocketmq/integration/inbound/RocketMQInboundChannelAdapter$$Lambda$1104
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.easypay.tianlu.sp.Application.main(Application.java:37)
Caused by: java.lang.NoClassDefFoundError: com/alibaba/cloud/stream/binder/rocketmq/integration/inbound/RocketMQInboundChannelAdapter$$Lambda$1104
	at com.alibaba.cloud.stream.binder.rocketmq.integration.inbound.RocketMQInboundChannelAdapter$$Lambda$1104/271923493.get$Lambda(Unknown Source)
	at com.alibaba.cloud.stream.binder.rocketmq.integration.inbound.RocketMQInboundChannelAdapter.onInit(RocketMQInboundChannelAdapter.java:122)
	at org.springframework.integration.context.IntegrationObjectSupport.afterPropertiesSet(IntegrationObjectSupport.java:214)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:412)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:91)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:176)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:133)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.alibaba.cloud.stream.binder.rocketmq.integration.inbound.RocketMQInboundChannelAdapter$$Lambda$1104
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 28 common frames omitted
```

**Comment by steverao** [comment]
I can't reproduced it too. Thanks for reporting the problem, let's see if there are any others who have encountered it, and then see if it can be reproduced and find the root cause later.

**Comment by LeBW** [comment]
> I can't reproduced it too. Thanks for reporting the problem, let's see if there are any others who have encountered it, and then see if it can be reproduced and find the root cause later.

Maybe we can change the lambda expression to inner class in the code. It will not affect the functionality, but has better compatibility.

**Comment by steverao** [comment]
> 

I suggest we don't be in such a hurry to modify immediately. Because, we can't reproduced it now, it's hard to exclude the problem that whether it is caused by user themselves. It's better to wait and see, because no one in the community can reproduce it so far, and it isn't so strong of the reason to modify it directly according to the user's statement.

**Comment by steverao** [comment]
> > I can't reproduced it too. Thanks for reporting the problem, let's see if there are any others who have encountered it, and then see if it can be reproduced and find the root cause later.
> 
> Maybe we can change the lambda expression to inner class in the code. It will not affect the functionality, but has better compatibility.

I suggest we don't be in such a hurry to modify immediately. Because, we can't reproduced it now, it's hard to exclude the problem that whether it is caused by user themselves. It's better to wait and see, because no one in the community can reproduce it so far, and it isn't so strong of the reason to modify it directly according to the user's statement.
