### ISSUE TITLE
Enabling authentication in Nacos, the user not found! exception appears in the health check of the Spring Cloud application. I want to know how to solve it.

### ISSUE THREAD

**Issue by BennettChina** [alibaba/spring-cloud-alibaba#3291]
title: Nacos 开启鉴权后在Spring Cloud应用的健康检查中出现`user not found!`异常，想知道怎么解决。

**Which Component**

`Spring Cloud Nacos` and version is `2.2.9 RELEASE`.

Other info:

`spring-cloud:Hoxton.SR12`
`spring-boot:2.3.12.RELEASE`

`nacos-server:2.2.2`

**Describe what problem you have encountered**

```
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed:
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.getServiceList(NamingGrpcClientProxy.java:201)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.getServiceList(NamingClientProxyDelegate.java:136)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:440)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:428)
	at com.alibaba.cloud.nacos.discovery.NacosServiceDiscovery.getServices(NacosServiceDiscovery.java:69)
	at com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient.getServices(NacosDiscoveryClient.java:67)
	at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getServices(CompositeDiscoveryClient.java:67)
	at org.springframework.cloud.client.discovery.health.DiscoveryClientHealthIndicator.health(DiscoveryClientHealthIndicator.java:74)
	at org.springframework.cloud.client.discovery.health.DiscoveryCompositeHealthContributor.lambda$asHealthIndicator$0(DiscoveryCompositeHealthContributor.java:77)
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:91)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:225)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.nacos.api.exception.NacosException: user not found!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:280)
	... 19 common frames omitted
```

**Describe what information you have read**
I have read the reference doc of Nacos.

I use this config:

```yaml
spring:
  cloud:
    nacos:
      config:
        namespace: dev
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: DEFAULT_GROUP
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        cluster-name: DEFAULT
      username: nacos
      password: nacos
```

**Comment by steverao** [comment]
Please check the username and password is correct or not.

**Comment by BennettChina** [comment]
> Please check the username and password is correct or not.

There is no problem, the service can start normally, and this problem only occurs occasionally during health checks.

**Comment by steverao** [comment]
> > Please check the username and password is correct or not.
> 
> There is no problem, the service can start normally, and this problem only occurs occasionally during health checks.

From your description above, This problem seems to be closely related to Nacos itself. It is recommended to raise an issue to the Nacos community.

**Comment by jiangxiaoqiang** [comment]
> > Please check the username and password is correct or not.
> 
> There is no problem, the service can start normally, and this problem only occurs occasionally during health checks.

post your code.
