### ISSUE TITLE
NacosWatch still start when set watch.enable=false

### ISSUE THREAD

**Issue by zt9788** [alibaba/spring-cloud-alibaba#3312]
Sometimes I use the Nacos client to register a servce by myself
I do not want the NacosWatch start ,so I set `spring.cloud.nacos.discovery.watch.enable=false` (`spring.cloud.nacos.discovery.enable=false`) and `@EnableDiscoveryClient(autoRegister = false)` 

But NacosWatch always start and set the `NacosDiscoveryProperties` by default (`127.0.0.1`)  when not set namespace and server-addr .

env:
JDK17,alibaba-cloud-2022.0.0.RC2,springcloud2022.0.2 springboot3.0.6
```
ERROR c.a.c.n.d.NacosWatch.start(98): - namingService subscribe failed, properties:NacosDiscoveryProperties{serverAddr='127.0.0.1:8848', username='', password='', endpoint='', namespace='', watchDelay=30000, logName='', service='demo-service', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={IPv6=null, preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='10.x.x.x', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTimeout=null, failFast=true}
com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:643) ~[nacos-client-2.2.2.jar:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:623) ~[nacos-client-2.2.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:357) ~[nacos-client-2.2.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:311) ~[nacos-client-2.2.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:296) ~[nacos-client-2.2.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:173) ~[nacos-client-2.2.2.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:405) ~[nacos-client-2.2.2.jar:?]
	at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:94) ~[spring-cloud-starter-alibaba-nacos-discovery-2022.0.0.0-RC2.jar:2022.0.0.0-RC2]
   
....
```

**Comment by 123liuziming** [comment]
I cannot reproduce your problem, NacosWatch is not initialized after I set `spring.cloud.nacos.discovery.watch.enabled` to false, and the autoRegister logic is not executed when autoRegister is false. Can you give me a minimalist demo that reproduces your problem?

**Comment by zt9788** [comment]
sorry ,sorry ,It is a invalid issue 
when Springboot3 release i try to use nacoscloud in 2021.0.x, so i create bean in config by myself.
and now i change the verstion to 2022.0.0.RC2 ,but i forget delete my config
I'm very sorry for wasting your time
