### ISSUE TITLE
after native-image builded, spring-cloud-alibaba-examples\seata-example\storage-service  run failed.

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#3356]
spring-cloud-alibaba-2022.0.0.0-RC2\spring-cloud-alibaba-examples\seata-example\storage-service

java.lang.InstantiationException: com.alibaba.nacos.common.notify.DefaultPublisher
	at java.base@17.0.7/java.lang.Class.newInstance(DynamicHub.java:639) ~[storage-service:na]
	at com.alibaba.nacos.common.notify.NotifyCenter.lambda$static$0(NotifyCenter.java:89) ~[na:na]
	at com.alibaba.nacos.common.notify.EventPublisherFactory.apply(EventPublisherFactory.java:26) ~[storage-service:na]
	at com.alibaba.nacos.common.utils.MapUtil.computeIfAbsent(MapUtil.java:156) ~[na:na]
	at com.alibaba.nacos.common.notify.NotifyCenter.registerToPublisher(NotifyCenter.java:347) ~[na:na]
	at com.alibaba.nacos.common.notify.NotifyCenter.registerToPublisher(NotifyCenter.java:328) ~[na:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:99) ~[na:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:85) ~[na:na]
	at java.base@17.0.7/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[storage-service:na]
	at java.base@17.0.7/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[storage-service:na]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[na:na]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[na:na]
	at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:99) ~[storage-service:2022.0.0.0-RC2]
	at com.alibaba.cloud.nacos.NacosServiceManager.buildNamingService(NacosServiceManager.java:90) ~[storage-service:2022.0.0.0-RC2]
	at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:46) ~[storage-service:2022.0.0.0-RC2]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.namingService(NacosServiceRegistry.java:193) ~[storage-service:2022.0.0.0-RC2]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:68) ~[storage-service:2022.0.0.0-RC2]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:264) ~[storage-service:4.0.0]
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) ~[storage-service:2022.0.0.0-RC2]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:156) ~[storage-service:4.0.0]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:119) ~[storage-service:4.0.0]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:49) ~[storage-service:4.0.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[na:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[na:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[storage-service:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[storage-service:6.0.4]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:47) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[storage-service:6.0.4]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[na:na]
	at java.base@17.0.7/java.lang.Iterable.forEach(Iterable.java:75) ~[storage-service:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[storage-service:6.0.4]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[storage-service:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:932) ~[storage-service:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587) ~[storage-service:6.0.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[storage-service:3.0.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[storage-service:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[storage-service:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[storage-service:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[storage-service:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[storage-service:3.0.2]
	at com.alibaba.cloud.examples.StorageApplication.main(StorageApplication.java:30) ~[storage-service:na]
Caused by: java.lang.NoSuchMethodException: com.alibaba.nacos.common.notify.DefaultPublisher.<init>()
	at java.base@17.0.7/java.lang.Class.getConstructor0(DynamicHub.java:3585) ~[storage-service:na]
	at java.base@17.0.7/java.lang.Class.newInstance(DynamicHub.java:626) ~[storage-service:na]
	... 41 common frames omitted

**Comment by ruansheng8** [comment]
Before running `build`, you need to make sure you have generated the relevant native configuration files correctly.
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/33607534-168c-4826-9198-812c261ac750)


You can use the `tracing agent` to generate native configuration files, see: https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.using-the-tracing-agent

**Comment by ruansheng8** [comment]
Or here is another way :
1. Setting up the maven plugin: 
```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>
                        -agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/
                    </jvmArguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
2. Run `mvn -Pnative spring-boot:run`

**Comment by imgoby** [comment]
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/27885492/df8e6899-e5c5-4f35-9bc4-7304cf514af8)

Yes,this config is added default in the spring cloud alibaba source project.
It likes missing the class setting: com.alibaba.nacos.common.notify.DefaultPublisher

If you are author of the project.you can  make a test in this dir: spring-cloud-alibaba-examples\seata-example\storage-service

**Comment by ruansheng8** [comment]
Check that the `/resources/reflect-config.json` file in your project contains the following JSON configuration
```json
{
  "name":"com.alibaba.nacos.common.notify.DefaultPublisher",
  "methods":[{"name":"<init>","parameterTypes":[] }]
}
```
These configurations are automatically generated with `mvn -Pnative spring-boot:run`

**Comment by ruansheng8** [comment]
Perhaps you could describe your implementation steps in more detail, the problem you're experiencing should be caused by not generating the native resource file correctly

**Comment by imgoby** [comment]
Thank you for your answer. I previously only used this command: 
`mvn -Pnative native:compile -DskipTests`

, but found that the generated file does not include: com.alibaba.nacos.common.notify.DefaultPublisher. Now I have used 
`mvn -Pnative spring-boot:run`
 and found that it was included.

I don't understand the difference between them, could you tell me?
but first I try to run 
`mvn -Pnative spring-boot:run`
, and then run
`mvn -Pnative native:compile -DskipTests`

Then it will pass.

**Comment by ruansheng8** [comment]
- GraalVM is not directly aware of dynamic elements of your code and must be told about reflection, resources, serialization, and dynamic proxies. 
- There is no lazy class loading, everything shipped in the executables will be loaded in memory on startup.

The rationale for this is described in the Spring documentation: [Understanding Spring Ahead-of-Time Processing](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.introducing-graalvm-native-images.understanding-aot-processing).

**Comment by ruansheng8** [comment]
Spring AOT is still in its early stages, most frameworks do not have built-in AOT configurations, such as reflection, serialization, so we need to be generated manually.

We can know the support of each framework for `GraalVM Meatadata` from the project https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata

**Comment by yuluo-yx** [comment]
You can add the following configuration to the three modules other than business-servicer to ensure that the native compilation passes.
```json
{
  "name":"com.alibaba.nacos.shaded.com.google.protobuf.Any",
  "methods":[
    {"name":"getTypeUrl","parameterTypes":[] }, 
    {"name":"getTypeUrlBytes","parameterTypes":[] }, 
    {"name":"getValue","parameterTypes":[] }, 
    {"name":"newBuilder","parameterTypes":[] }
  ]
},
{
  "name":"com.alibaba.nacos.shaded.com.google.protobuf.Any$Builder",
  "methods":[
    {"name":"clearTypeUrl","parameterTypes":[] }, 
    {"name":"clearValue","parameterTypes":[] }, 
    {"name":"getTypeUrl","parameterTypes":[] }, 
    {"name":"getTypeUrlBytes","parameterTypes":[] }, 
    {"name":"getValue","parameterTypes":[] }, 
    {"name":"setTypeUrl","parameterTypes":["java.lang.String"] }, 
    {"name":"setTypeUrlBytes","parameterTypes":["com.alibaba.nacos.shaded.com.google.protobuf.ByteString"] }, 
    {"name":"setValue","parameterTypes":["com.alibaba.nacos.shaded.com.google.protobuf.ByteString"] }
  ]
},

{
  "name":"com.alibaba.nacos.common.notify.DefaultPublisher",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},

{
  "name":"com.alibaba.nacos.api.naming.pojo.Instance",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[
    {"name":"<init>","parameterTypes":[] }, 
    {"name":"getClusterName","parameterTypes":[] }, 
    {"name":"getInstanceHeartBeatInterval","parameterTypes":[] }, 
    {"name":"getInstanceHeartBeatTimeOut","parameterTypes":[] }, 
    {"name":"getInstanceId","parameterTypes":[] }, 
    {"name":"getInstanceIdGenerator","parameterTypes":[] }, 
    {"name":"getIp","parameterTypes":[] }, 
    {"name":"getIpDeleteTimeout","parameterTypes":[] }, 
    {"name":"getMetadata","parameterTypes":[] }, 
    {"name":"getPort","parameterTypes":[] }, 
    {"name":"getServiceName","parameterTypes":[] }, 
    {"name":"getWeight","parameterTypes":[] }, 
    {"name":"isEnabled","parameterTypes":[] }, 
    {"name":"isEphemeral","parameterTypes":[] }, 
    {"name":"isHealthy","parameterTypes":[] }, 
    {"name":"setClusterName","parameterTypes":["java.lang.String"] }, 
    {"name":"setEnabled","parameterTypes":["boolean"] }, 
    {"name":"setEphemeral","parameterTypes":["boolean"] }, 
    {"name":"setHealthy","parameterTypes":["boolean"] }, 
    {"name":"setInstanceId","parameterTypes":["java.lang.String"] }, 
    {"name":"setIp","parameterTypes":["java.lang.String"] }, 
    {"name":"setMetadata","parameterTypes":["java.util.Map"] }, 
    {"name":"setPort","parameterTypes":["int"] }, 
    {"name":"setServiceName","parameterTypes":["java.lang.String"] }, 
    {"name":"setWeight","parameterTypes":["double"] }
  ]
},
{
  "name":"com.alibaba.nacos.api.naming.pojo.ServiceInfo",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[
    {"name":"<init>","parameterTypes":[] }, 
    {"name":"getCacheMillis","parameterTypes":[] }, 
    {"name":"getChecksum","parameterTypes":[] }, 
    {"name":"getClusters","parameterTypes":[] }, 
    {"name":"getGroupName","parameterTypes":[] }, 
    {"name":"getHosts","parameterTypes":[] }, 
    {"name":"getLastRefTime","parameterTypes":[] }, 
    {"name":"getName","parameterTypes":[] }, 
    {"name":"isAllIPs","parameterTypes":[] }, 
    {"name":"isReachProtectionThreshold","parameterTypes":[] }, 
    {"name":"isValid","parameterTypes":[] }, 
    {"name":"setAllIPs","parameterTypes":["boolean"] }, 
    {"name":"setCacheMillis","parameterTypes":["long"] }, 
    {"name":"setChecksum","parameterTypes":["java.lang.String"] }, 
    {"name":"setClusters","parameterTypes":["java.lang.String"] }, 
    {"name":"setGroupName","parameterTypes":["java.lang.String"] }, 
    {"name":"setHosts","parameterTypes":["java.util.List"] }, 
    {"name":"setLastRefTime","parameterTypes":["long"] }, 
    {"name":"setName","parameterTypes":["java.lang.String"] }, 
    {"name":"setReachProtectionThreshold","parameterTypes":["boolean"] }
  ]
},
{
  "name":"com.alibaba.nacos.api.naming.remote.request.AbstractNamingRequest",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "methods":[
    {"name":"getGroupName","parameterTypes":[] }, 
    {"name":"getModule","parameterTypes":[] }, 
    {"name":"getNamespace","parameterTypes":[] }, 
    {"name":"getServiceName","parameterTypes":[] }
  ]
},
{
  "name":"com.alibaba.nacos.api.naming.remote.request.InstanceRequest",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[
    {"name":"getInstance","parameterTypes":[] }, 
    {"name":"getType","parameterTypes":[] }
  ]
},
{
  "name":"com.alibaba.nacos.api.naming.remote.request.NotifySubscriberRequest",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[
    {"name":"<init>","parameterTypes":[] }, 
    {"name":"setServiceInfo","parameterTypes":["com.alibaba.nacos.api.naming.pojo.ServiceInfo"] }
  ]
},
{
  "name":"com.alibaba.nacos.api.naming.remote.request.SubscribeServiceRequest",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[
    {"name":"getClusters","parameterTypes":[] }, 
    {"name":"isSubscribe","parameterTypes":[] }
  ]
},
{
  "name":"com.alibaba.nacos.api.naming.remote.response.InstanceResponse",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[
    {"name":"<init>","parameterTypes":[] }, 
    {"name":"setType","parameterTypes":["java.lang.String"] }
  ]
},
{
  "name":"com.alibaba.nacos.api.naming.remote.response.NotifySubscriberResponse",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true
},
{
  "name":"com.alibaba.nacos.api.naming.remote.response.SubscribeServiceResponse",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[
    {"name":"<init>","parameterTypes":[] }, 
    {"name":"setServiceInfo","parameterTypes":["com.alibaba.nacos.api.naming.pojo.ServiceInfo"] }
  ]
}
```
The following json entry configuration needs to be added in business-service
```json

{
  "name":"com.github.benmanes.caffeine.cache.BLCHeader$DrainStatusRef",
  "fields":[{"name":"drainStatus"}]
},
{
  "name":"com.github.benmanes.caffeine.cache.BaseMpscLinkedArrayQueueColdProducerFields",
  "fields":[{"name":"producerLimit"}]
},
{
  "name":"com.github.benmanes.caffeine.cache.BaseMpscLinkedArrayQueueConsumerFields",
  "fields":[{"name":"consumerIndex"}]
},
{
  "name":"com.github.benmanes.caffeine.cache.BaseMpscLinkedArrayQueueProducerFields",
  "fields":[{"name":"producerIndex"}]
},
{
  "name":"com.github.benmanes.caffeine.cache.BoundedLocalCache",
  "fields":[{"name":"refreshes"}]
},
{
  "name":"com.github.benmanes.caffeine.cache.Cache"
},
{
  "name":"com.github.benmanes.caffeine.cache.Caffeine"
},
{
  "name":"com.github.benmanes.caffeine.cache.PD",
  "fields":[{"name":"value"}]
},
{
  "name":"com.github.benmanes.caffeine.cache.PDW",
  "fields":[{"name":"writeTime"}],
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.github.benmanes.caffeine.cache.SIW",
  "methods":[{"name":"<init>","parameterTypes":["com.github.benmanes.caffeine.cache.Caffeine","com.github.benmanes.caffeine.cache.AsyncCacheLoader","boolean"] }]
},
{
  "name":"com.github.benmanes.caffeine.cache.StripedBuffer",
  "fields":[{"name":"tableBusy"}]
},
{
  "name":"com.github.benmanes.caffeine.cache.UnboundedLocalCache",
  "fields":[{"name":"refreshes"}]
}
```
In addition, the community will release the official version of 2022 in the near future, which will better support the static compilation function.

**Comment by karl-chanel** [comment]
mark

**Comment by karl-chanel** [comment]
mark
