### ISSUE TITLE
mvn 打包 一直OutOfMemoryError

### ISSUE THREAD

**Issue by zhouxingfako** [alibaba/spring-cloud-alibaba#3426]
mvn 版本3.3.9 
根目录 mvn clean install  -Dmaven.test.skip=true 

mvn里 set MAVEN_OPTS= -Xms512m -Xmx1024m -XX:PermSize=128M -XX:MaxPermSize=256M
一直报内存溢出，
[DEBUG] Extension realms for project com.alibaba.cloud:spring-cloud-alibaba-examples:pom:2.2.10-RC1: (none)
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
[ERROR] GC overhead limit exceeded -> [Help 1]
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:149)
	at java.lang.StringCoding.decode(StringCoding.java:193)
	at java.lang.String.<init>(String.java:426)
	at org.codehaus.plexus.util.xml.XmlReader.getXmlProlog(XmlReader.java:716)
	at org.codehaus.plexus.util.xml.XmlReader.doRawStream(XmlReader.java:461)
	at org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:180)
	at org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:143)
	at org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:86)
	at org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:104)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:86)
	at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:81)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:533)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1045)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:800)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:329)
	at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:1226)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:455)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:421)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:411)
	at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:1226)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:455)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:421)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:411)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:161)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119)
	at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:679)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:623)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:626)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:626)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:411)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError

**Comment by steverao** [comment]
你是Spring Cloud Alibaba项目打包吗？你把设置堆内存的那样配置删除是否可以正常打包呢？

**Comment by kimmking** [comment]
内存太小了。
