### ISSUE TITLE
 Property or field 'serviceId' cannot be found on object of type 'com.alibaba.cloud.nacos.NacosServiceInstance'

### ISSUE THREAD

**Issue by xiaoproject** [alibaba/spring-cloud-alibaba#3451]
**Which Component**
- Springboot 3.0.2
- Springcloud 2022.0.0
- Springcloud 2022.0.0.0
- GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14) 

**Describe the bug**
Native 打包后启动报错
```
2023-09-12 11:52:43.745 [%PARSER_ERROR[X]] [boundedElastic-4] ERROR o.s.c.g.route.CachingRouteLocator -Refresh routes error !!!
org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'serviceId' cannot be found on object of type 'com.alibaba.cloud.nacos.NacosServiceInstance' - maybe not public or not valid?
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:217)
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104)
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:92)
        at org.springframework.expression.spel.ast.OpPlus.getValueInternal(OpPlus.java:85)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:376)
        at org.springframework.cloud.gateway.discovery.DiscoveryClientRouteDefinitionLocator.buildRouteDefinition(DiscoveryClientRouteDefinitionLocator.java:135)
        at org.springframework.cloud.gateway.discovery.DiscoveryClientRouteDefinitionLocator.lambda$getRouteDefinitions$5(DiscoveryClientRouteDefinitionLocator.java:103)
```

**Comment by yuluo-yx** [comment]
查看下是添加了 `com.alibaba.cloud.nacos.NacosServiceInstance` 这条元数据配置，在项目适配的时候只是对 example 中用到的元数据做了补充，你可以提交pr去补充完善元数据列表。

**Comment by karl-chanel** [comment]
i got the same issue when i try to use it with spring cloud gateway @yuluo-yx

**Comment by karl-chanel** [comment]
当设置了    
gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
时，编译的native镜像启动时就会报上面的错，去掉后启动不报错，但配置的服务转发依旧不能用，报java.lang.IllegalArgumentException: Object of class [org.springframework.context.support.GenericApplicationContext] must be an instance of interface org.springframework.context.annotation.AnnotationConfigRegistry
