### ISSUE TITLE
Nacos version issue causing fastJSON to parse JSON strings abnormally

### ISSUE THREAD

**Issue by tanxiujiang** [alibaba/spring-cloud-alibaba#3486]
GroupId is com.alibaba.cloud and artifactId is spring-cloud-starter-alibaba-nacos-config Upgrade from previous 1.5.1. RELEASE to 2.2.3.RELEASE。JSONObject jsonObject=JSONObject. parseObject (jsonStr); This code reported an error。JsonStr is pulled from nacos and configured by @value, the value is {\"orgNo\":\"[\\\\-——\\\\-]\"}.  The fastJson version is 1.2.83.
The error message is as follows：
com.alibaba.fastjson.JSONException: illegal identifier : \pos 1, line 1, column 2{\"orgNo\":\"[\\\\-——\\\\-]\"}
        at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbolUnQuoted(JSONLexerBase.java:834)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:298)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1430)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
        at com.alibaba.fastjson.JSON.parse(JSON.java:181)
        at com.alibaba.fastjson.JSON.parse(JSON.java:191)
        at com.alibaba.fastjson.JSON.parse(JSON.java:147)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)

**Comment by yuluo-yx** [comment]
Exceptions aside, is it possible that your json format is wrong? you can check.

**Comment by tanxiujiang** [comment]
Json format is not wrong. Same string, rollback version to 1.5.1 RELEASE, there is no error reported.

**Comment by tanxiujiang** [comment]
> Exceptions aside, is it possible that your json format is wrong? you can check.

Json format is not wrong. Same string, rollback version to 1.5.1 RELEASE, there is no error reported.

**Comment by yuluo-yx** [comment]
okay, Can you provider a simaple demo  project? Easy to reproduce and solve problems?
