### ISSUE TITLE
endpoint is blank

### ISSUE THREAD

**Issue by enticejin** [alibaba/spring-cloud-alibaba#3495]
when I use nacos config spring cloud,  endpoint is blank. this is my running log; please help me, thanks!
I have added bootstrap.properties, and the nacos server is running!

"F:\Program Files\Java\jdk-17\bin\java.exe" -XX:TieredStopAtLevel=1 -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2022.2.3\lib\idea_rt.jar=55793:D:\Program Files\JetBrains\IntelliJ IDEA 2022.2.3\bin" -Dfile.encoding=UTF-8 -classpath D:\projects\java\gulimall\gulimall-coupon\target\classes;D:\maven\LocalRepository\org\springframework\boot\spring-boot-starter-web\2.7.17\spring-boot-starter-web-2.7.17.jar;D:\maven\LocalRepository\org\springframework\boot\spring-boot-starter\2.7.17\spring-boot-starter-2.7.17.jar;D:\maven\LocalRepository\org\springframework\boot\spring-boot\2.7.17\spring-boot-2.7.17.jar;D:\maven\LocalRepository\org\springframework\boot\spring-boot-autoconfigure\2.7.17\spring-boot-autoconfigure-2.7.17.jar;D:\maven\LocalRepository\org\springframework\boot\spring-boot-starter-logging\2.7.17\spring-boot-starter-logging-2.7.17.jar;D:\maven\LocalRepository\ch\qos\logback\logback-classic\1.2.12\logback-classic-1.2.12.jar;D:\maven\LocalRepository\ch\qos\logback\logback-core\1.2.12\logback-core-1.2.12.jar;D:\maven\LocalRepository\org\apache\logging\log4j\log4j-to-slf4j\2.17.2\log4j-to-slf4j-2.17.2.jar;D:\maven\LocalRepository\org\apache\logging\log4j\log4j-api\2.17.2\log4j-api-2.17.2.jar;D:\maven\LocalRepository\org\slf4j\jul-to-slf4j\1.7.36\jul-to-slf4j-1.7.36.jar;D:\maven\LocalRepository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;D:\maven\LocalRepository\org\yaml\snakeyaml\1.30\snakeyaml-1.30.jar;D:\maven\LocalRepository\org\springframework\boot\spring-boot-starter-json\2.7.17\spring-boot-starter-json-2.7.17.jar;D:\maven\LocalRepository\com\fasterxml\jackson\core\jackson-databind\2.13.5\jackson-databind-2.13.5.jar;D:\maven\LocalRepository\com\fasterxml\jackson\core\jackson-annotations\2.13.5\jackson-annotations-2.13.5.jar;D:\maven\LocalRepository\com\fasterxml\jackson\core\jackson-core\2.13.5\jackson-core-2.13.5.jar;D:\maven\LocalRepository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.13.5\jackson-datatype-jdk8-2.13.5.jar;D:\maven\LocalRepository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.13.5\jackson-datatype-jsr310-2.13.5.jar;D:\maven\LocalRepository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.13.5\jackson-module-parameter-names-2.13.5.jar;D:\maven\LocalRepository\org\springframework\boot\spring-boot-starter-tomcat\2.7.17\spring-boot-starter-tomcat-2.7.17.jar;D:\maven\LocalRepository\org\apache\tomcat\embed\tomcat-embed-core\9.0.82\tomcat-embed-core-9.0.82.jar;D:\maven\LocalRepository\org\apache\tomcat\embed\tomcat-embed-el\9.0.82\tomcat-embed-el-9.0.82.jar;D:\maven\LocalRepository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.82\tomcat-embed-websocket-9.0.82.jar;D:\maven\LocalRepository\org\springframework\spring-web\5.3.30\spring-web-5.3.30.jar;D:\maven\LocalRepository\org\springframework\spring-beans\5.3.30\spring-beans-5.3.30.jar;D:\maven\LocalRepository\org\springframework\spring-webmvc\5.3.30\spring-webmvc-5.3.30.jar;D:\maven\LocalRepository\org\springframework\spring-aop\5.3.30\spring-aop-5.3.30.jar;D:\maven\LocalRepository\org\springframework\spring-context\5.3.30\spring-context-5.3.30.jar;D:\maven\LocalRepository\org\springframework\spring-expression\5.3.30\spring-expression-5.3.30.jar;D:\maven\LocalRepository\org\springframework\cloud\spring-cloud-starter-openfeign\3.1.8\spring-cloud-starter-openfeign-3.1.8.jar;D:\maven\LocalRepository\org\springframework\cloud\spring-cloud-starter\3.1.7\spring-cloud-starter-3.1.7.jar;D:\maven\LocalRepository\org\springframework\cloud\spring-cloud-context\3.1.7\spring-cloud-context-3.1.7.jar;D:\maven\LocalRepository\org\springframework\security\spring-security-rsa\1.0.11.RELEASE\spring-security-rsa-1.0.11.RELEASE.jar;D:\maven\LocalRepository\org\bouncycastle\bcpkix-jdk15on\1.69\bcpkix-jdk15on-1.69.jar;D:\maven\LocalRepository\org\bouncycastle\bcprov-jdk15on\1.69\bcprov-jdk15on-1.69.jar;D:\maven\LocalRepository\org\bouncycastle\bcutil-jdk15on\1.69\bcutil-jdk15on-1.69.jar;D:\maven\LocalRepository\org\springframework\cloud\spring-cloud-openfeign-core\3.1.8\spring-cloud-openfeign-core-3.1.8.jar;D:\maven\LocalRepository\org\springframework\boot\spring-boot-starter-aop\2.7.17\spring-boot-starter-aop-2.7.17.jar;D:\maven\LocalRepository\org\aspectj\aspectjweaver\1.9.7\aspectjweaver-1.9.7.jar;D:\maven\LocalRepository\io\github\openfeign\form\feign-form-spring\3.8.0\feign-form-spring-3.8.0.jar;D:\maven\LocalRepository\io\github\openfeign\form\feign-form\3.8.0\feign-form-3.8.0.jar;D:\maven\LocalRepository\commons-fileupload\commons-fileupload\1.5\commons-fileupload-1.5.jar;D:\maven\LocalRepository\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;D:\maven\LocalRepository\org\springframework\cloud\spring-cloud-commons\3.1.7\spring-cloud-commons-3.1.7.jar;D:\maven\LocalRepository\org\springframework\security\spring-security-crypto\5.7.11\spring-security-crypto-5.7.11.jar;D:\maven\LocalRepository\io\github\openfeign\feign-core\11.10\feign-core-11.10.jar;D:\maven\LocalRepository\io\github\openfeign\feign-slf4j\11.10\feign-slf4j-11.10.jar;D:\maven\LocalRepository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;D:\maven\LocalRepository\org\springframework\spring-core\5.3.30\spring-core-5.3.30.jar;D:\maven\LocalRepository\org\springframework\spring-jcl\5.3.30\spring-jcl-5.3.30.jar;D:\projects\java\gulimall\gulimall-common\target\classes;D:\maven\LocalRepository\com\baomidou\mybatis-plus-boot-starter\3.5.4.1\mybatis-plus-boot-starter-3.5.4.1.jar;D:\maven\LocalRepository\com\baomidou\mybatis-plus\3.5.4.1\mybatis-plus-3.5.4.1.jar;D:\maven\LocalRepository\com\baomidou\mybatis-plus-core\3.5.4.1\mybatis-plus-core-3.5.4.1.jar;D:\maven\LocalRepository\com\baomidou\mybatis-plus-annotation\3.5.4.1\mybatis-plus-annotation-3.5.4.1.jar;D:\maven\LocalRepository\com\baomidou\mybatis-plus-extension\3.5.4.1\mybatis-plus-extension-3.5.4.1.jar;D:\maven\LocalRepository\org\mybatis\mybatis\3.5.13\mybatis-3.5.13.jar;D:\maven\LocalRepository\com\github\jsqlparser\jsqlparser\4.6\jsqlparser-4.6.jar;D:\maven\LocalRepository\org\mybatis\mybatis-spring\2.1.1\mybatis-spring-2.1.1.jar;D:\maven\LocalRepository\com\baomidou\mybatis-plus-spring-boot-autoconfigure\3.5.4.1\mybatis-plus-spring-boot-autoconfigure-3.5.4.1.jar;D:\maven\LocalRepository\org\springframework\boot\spring-boot-starter-jdbc\2.7.17\spring-boot-starter-jdbc-2.7.17.jar;D:\maven\LocalRepository\com\zaxxer\HikariCP\4.0.3\HikariCP-4.0.3.jar;D:\maven\LocalRepository\org\springframework\spring-jdbc\5.3.30\spring-jdbc-5.3.30.jar;D:\maven\LocalRepository\org\springframework\spring-tx\5.3.30\spring-tx-5.3.30.jar;D:\maven\LocalRepository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\maven\LocalRepository\com\alibaba\fastjson\1.2.79\fastjson-1.2.79.jar;D:\maven\LocalRepository\org\apache\httpcomponents\httpcore\4.4.16\httpcore-4.4.16.jar;D:\maven\LocalRepository\mysql\mysql-connector-java\8.0.17\mysql-connector-java-8.0.17.jar;D:\maven\LocalRepository\com\google\protobuf\protobuf-java\3.6.1\protobuf-java-3.6.1.jar;D:\maven\LocalRepository\com\alibaba\cloud\spring-cloud-starter-alibaba-nacos-discovery\2.1.0.RELEASE\spring-cloud-starter-alibaba-nacos-discovery-2.1.0.RELEASE.jar;D:\maven\LocalRepository\com\alibaba\cloud\spring-cloud-alibaba-nacos-discovery\2.1.0.RELEASE\spring-cloud-alibaba-nacos-discovery-2.1.0.RELEASE.jar;D:\maven\LocalRepository\com\alibaba\nacos\nacos-client\1.1.1\nacos-client-1.1.1.jar;D:\maven\LocalRepository\com\alibaba\nacos\nacos-common\1.1.1\nacos-common-1.1.1.jar;D:\maven\LocalRepository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;D:\maven\LocalRepository\com\alibaba\nacos\nacos-api\1.1.1\nacos-api-1.1.1.jar;D:\maven\LocalRepository\com\google\guava\guava\19.0\guava-19.0.jar;D:\maven\LocalRepository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;D:\maven\LocalRepository\io\prometheus\simpleclient\0.15.0\simpleclient-0.15.0.jar;D:\maven\LocalRepository\io\prometheus\simpleclient_tracer_otel\0.15.0\simpleclient_tracer_otel-0.15.0.jar;D:\maven\LocalRepository\io\prometheus\simpleclient_tracer_common\0.15.0\simpleclient_tracer_common-0.15.0.jar;D:\maven\LocalRepository\io\prometheus\simpleclient_tracer_otel_agent\0.15.0\simpleclient_tracer_otel_agent-0.15.0.jar;D:\maven\LocalRepository\com\alibaba\cloud\spring-cloud-starter-alibaba-nacos-config\2.1.0.RELEASE\spring-cloud-starter-alibaba-nacos-config-2.1.0.RELEASE.jar;D:\maven\LocalRepository\com\alibaba\cloud\spring-cloud-alibaba-nacos-config\2.1.0.RELEASE\spring-cloud-alibaba-nacos-config-2.1.0.RELEASE.jar;D:\maven\LocalRepository\org\projectlombok\lombok\1.18.30\lombok-1.18.30.jar com.atguigu.gulimall.GulimallCouponApplication

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.17)

2023-11-14 19:41:19.335  INFO 18132 --- [           main] c.a.gulimall.GulimallCouponApplication   : Starting GulimallCouponApplication using Java 17.0.7 on Gejin with PID 18132 (D:\projects\java\gulimall\gulimall-coupon\target\classes started by Administrator in D:\projects\java\gulimall)
2023-11-14 19:41:19.337  INFO 18132 --- [           main] c.a.gulimall.GulimallCouponApplication   : No active profile set, falling back to 1 default profile: "default"
2023-11-14 19:41:20.058  INFO 18132 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=e1fa08c9-7bf3-3e1e-9b78-87ff1e206060
2023-11-14 19:41:20.351  INFO 18132 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 7000 (http)
2023-11-14 19:41:20.359  INFO 18132 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-11-14 19:41:20.359  INFO 18132 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.82]
2023-11-14 19:41:20.469  INFO 18132 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-11-14 19:41:20.469  INFO 18132 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1089 ms
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.5.4.1 
2023-11-14 19:41:21.566 ERROR 18132 --- [           main] c.a.cloud.nacos.NacosConfigProperties    : create config service error!properties=NacosConfigProperties{serverAddr='null', encode='null', group='DEFAULT_GROUP', prefix='null', fileExtension='properties', timeout=3000, endpoint='null', namespace='null', accessKey='null', secretKey='null', contextPath='null', clusterName='null', name='null', sharedDataids='null', refreshableDataids='null', extConfig=null},e=,

com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45) ~[nacos-api-1.1.1.jar:na]
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:43) ~[nacos-api-1.1.1.jar:na]
	at com.alibaba.cloud.nacos.NacosConfigProperties.configServiceInstance(NacosConfigProperties.java:346) ~[spring-cloud-alibaba-nacos-config-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.alibaba.cloud.nacos.NacosConfigAutoConfiguration.nacosContextRefresher(NacosConfigAutoConfiguration.java:64) ~[spring-cloud-alibaba-nacos-config-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.alibaba.cloud.nacos.NacosConfigAutoConfiguration$$EnhancerBySpringCGLIB$$3b57e7bc.CGLIB$nacosContextRefresher$2(<generated>) ~[spring-cloud-alibaba-nacos-config-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.alibaba.cloud.nacos.NacosConfigAutoConfiguration$$EnhancerBySpringCGLIB$$3b57e7bc$$FastClassBySpringCGLIB$$5f83989a.invoke(<generated>) ~[spring-cloud-alibaba-nacos-config-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.30.jar:5.3.30]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.30.jar:5.3.30]
	at com.alibaba.cloud.nacos.NacosConfigAutoConfiguration$$EnhancerBySpringCGLIB$$3b57e7bc.nacosContextRefresher(<generated>) ~[spring-cloud-alibaba-nacos-config-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:633) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:921) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[spring-boot-2.7.17.jar:2.7.17]
	at com.atguigu.gulimall.GulimallCouponApplication.main(GulimallCouponApplication.java:14) ~[classes/:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:42) ~[nacos-api-1.1.1.jar:na]
	... 33 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: endpoint is blank
	at com.alibaba.nacos.client.config.impl.ServerListManager.<init>(ServerListManager.java:154) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.<init>(ServerHttpAgent.java:244) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.<init>(NacosConfigService.java:83) ~[nacos-client-1.1.1.jar:na]
	... 39 common frames omitted

**Comment by ruansheng8** [comment]
According to the logs you provided, I found that you are using Spring Cloud Alibaba `2.2.x` , if you want to use Spring Boot `2.7.x`, please use Spring Cloud Alibaba `2021.x`
See: https://sca.aliyun.com/zh-cn/docs/next/overview/version-explain#2021x-%E5%88%86%E6%94%AF
