### ISSUE TITLE
spring cloud gateway run failed,while built with native-image

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#3751]
demo: https://github.com/imgoby/spring-cloud-alibaba-dubbo-native/tree/main/spring-cloud-alibaba-gateway

step 1:  mvn clean package native:compile
step 2: run application
step 3: visit page,then Exception was found.as follow.

`  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.9)

2024-06-03T16:23:23.189+08:00  INFO 20924 --- [           main] c.a.c.i.gateway.GatewayApplication       : Starting AOT-processed GatewayApplication using Java 17.0.11 with PID 20924 (/home/sail/app/spring-cloud-alibaba-gateway started by root in /home/sail/app)
2024-06-03T16:23:23.189+08:00  INFO 20924 --- [           main] c.a.c.i.gateway.GatewayApplication       : No active profile set, falling back to 1 default profile: "default"
2024-06-03T16:23:23.191+08:00  INFO 20924 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=19f8bcb4-897a-32d5-89ea-8b5693b4e704
2024-06-03T16:23:23.194+08:00  INFO 20924 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-06-03T16:23:23.194+08:00  INFO 20924 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'reactorDeferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-06-03T16:23:23.194+08:00  INFO 20924 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
INFO: Sentinel log output type is: file
INFO: Sentinel log charset is: utf-8
INFO: Sentinel log base directory is: /root/logs/csp/
INFO: Sentinel log name use pid is: false
INFO: Sentinel log level is: INFO
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [After]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Before]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Between]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Cookie]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Header]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Host]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Method]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Path]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Query]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [ReadBody]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [RemoteAddr]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [XForwardedRemoteAddr]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Weight]
2024-06-03T16:23:23.245+08:00  INFO 20924 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [CloudFoundryRouteService]
2024-06-03T16:23:23.263+08:00  WARN 20924 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
2024-06-03T16:23:23.269+08:00  INFO 20924 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 18000
2024-06-03T16:23:23.270+08:00  INFO 20924 --- [           main] o.s.c.c.s.ConsulServiceRegistry          : Registering service with consul: NewService{id='integrated-gateway-192-168-0-211-18000', name='integrated-gateway', tags=[], address='192.168.0.211', meta={secure=false}, port=18000, enableTagOverride=null, check=Check{script='null', dockerContainerID='null', shell='null', interval='10s', ttl='null', http='http://192.168.0.211:18000/actuator/info', method='null', header={}, tcp='null', timeout='null', deregisterCriticalServiceAfter='3m', tlsSkipVerify=null, status='null', grpc='null', grpcUseTLS=null}, checks=null}
2024-06-03T16:23:23.285+08:00  INFO 20924 --- [           main] c.a.c.i.gateway.GatewayApplication       : Started GatewayApplication in 0.111 seconds (process running for 0.114)
2024-06-03T16:23:27.664+08:00 ERROR 20924 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [16c9fb4b-1]  500 Server Error for HTTP GET "/admin/user/createCaptcha"

java.lang.IllegalArgumentException: Object of class [org.springframework.context.support.GenericApplicationContext] must be an instance of interface org.springframework.context.annotation.AnnotationConfigRegistry
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:713) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/admin/user/createCaptcha" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.util.Assert.instanceCheckFailed(Assert.java:713) ~[na:na]
		at org.springframework.util.Assert.isInstanceOf(Assert.java:613) ~[na:na]
		at org.springframework.util.Assert.isInstanceOf(Assert.java:644) ~[na:na]
		at org.springframework.cloud.context.named.NamedContextFactory.registerBeans(NamedContextFactory.java:143) ~[spring-cloud-alibaba-gateway:4.0.4]
		at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:137) ~[spring-cloud-alibaba-gateway:4.0.4]
		at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:122) ~[spring-cloud-alibaba-gateway:4.0.4]
		at org.springframework.cloud.context.named.NamedContextFactory.getInstances(NamedContextFactory.java:236) ~[spring-cloud-alibaba-gateway:4.0.4]
		at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.filter(ReactiveLoadBalancerClientFilter.java:114) ~[spring-cloud-alibaba-gateway:4.0.7]
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:137) ~[na:na]
		at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44) ~[spring-cloud-alibaba-gateway:4.0.7]
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:117) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at com.alibaba.csp.sentinel.adapter.reactor.MonoSentinelOperator.subscribe(MonoSentinelOperator.java:40) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[na:na]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerNext(FluxConcatMapNoPrefetch.java:258) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863) ~[na:na]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[na:na]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[na:na]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerNext(FluxConcatMapNoPrefetch.java:258) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863) ~[na:na]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[na:na]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[na:na]
		at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onNext(MonoFilterWhen.java:136) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.request(MonoFilterWhen.java:182) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[na:na]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2305) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2305) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[na:na]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2305) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[na:na]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2305) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201) ~[na:na]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[spring-cloud-alibaba-gateway:3.5.8]
		at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[na:na]
		at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:1052) ~[na:na]
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:710) ~[na:na]
		at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:481) ~[na:na]
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:647) ~[spring-cloud-alibaba-gateway:1.1.9]
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[spring-cloud-alibaba-gateway:1.1.9]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:238) ~[spring-cloud-alibaba-gateway:1.1.9]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[spring-cloud-alibaba-gateway:4.1.94.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[na:na]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[na:na]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
		at java.base@17.0.11/java.lang.Thread.run(Thread.java:842) ~[spring-cloud-alibaba-gateway:na]
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:885) ~[spring-cloud-alibaba-gateway:na]
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:860) ~[spring-cloud-alibaba-gateway:na]
`

**Comment by imgoby** [comment]
It was resolved. look here  https://github.com/spring-cloud/spring-cloud-openfeign/issues/837#issuecomment-2173675544

**Comment by WangJincheng4869** [comment]
@imgoby 您好！我遇见了同样的问题，是需要关闭自动刷新吗？但是这样对于 gateway 来说是致命的，添加新模块就要重新编译（我尝试用命令行传参但是失败了，没有识别我的参数）。

```
spring.cloud.refresh.enabled=false
spring.cloud.loadbalancer.eager-load.clients={microservice1},{microservice2
```
