### ISSUE TITLE
[notify-error] dataId=hc-erp-common-config.yaml, group=hc-erp-common,tenant=dev

### ISSUE THREAD

**Issue by SmallSeals** [alibaba/spring-cloud-alibaba#3863]
[notify-error] dataId=hc-erp-common-config.yaml, group=hc-erp-common,tenant=dev, md5=06253139a1ba54402d20894e082b521c, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@2bd4c873 tx=
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3347)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2454)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperties.getDeclaredMethods(JavaBeanBinder.java:140)
	at ...

**Comment by ruansheng8** [comment]
看着是数据格式错误导致的，检查下配置和对应Java类的字段格式是否正确

**Comment by SmallSeals** [comment]
调试代码后发现少了一个依赖包
commons-pool2
加入这个依赖就一切正常了
