### ISSUE TITLE
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers

### ISSUE THREAD

**Issue by magicsgxie** [alibaba/spring-cloud-alibaba#660]
when auth or business remote call /nacos/v1/ns/instance/list after all servers, then report IllegalStateException

detail exception like this:
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([192.168.15.125:8848]) tried: failed to req API:http://192.168.15.125:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@localhost
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_05]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
**Additional context**
Nacos cluster: centos 3

**Comment by magicsgxie** [comment]
spring cloud version:
 <spring-cloud.version>Greenwich.SR1</spring-cloud.version>
        <spring-platform.version>Cairo-SR8</spring-platform.version>
 <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>0.9.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

**Comment by magicsgxie** [comment]
I can't found where were from the "DEFAULT_GROUP@@localhost"? Can you help me ? Thanks

**Comment by fangjian0423** [comment]
Which Nacos Server Version are you using?

**Comment by brantroy** [comment]
I also encountered the same problem:
Nacos Server Version : 1.0.0
spring-cloud-alibaba-dependencies : 0.9.0.RELEASE or 0.2.2 RELEASE (I have tried both versions)

**Comment by brantroy** [comment]
solved for  me : ribbon.eureka.enabled=false
