### ISSUE TITLE
用spring-cloud-starter-alicloud-sms 发送短信失败

### ISSUE THREAD

**Issue by helongno1** [alibaba/spring-cloud-alibaba#785]
项目中用了spring-cloud-alibaba-dependencies 0.9.0.RELEASE 

在某模块引用以下依赖用来发短信和处理图片：

       <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alicloud-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alicloud-oss</artifactId>
        </dependency>

结果是报错：

15:52:18.854 ERROR org.springframework.boot.web.servlet.support.ErrorPageFilter 190 forwardToErrorPage - Forwarding to error page from request [/base/areacode/available] due to exception [Content has not been provided] java.lang.IllegalStateException: Content has not been provided
	at org.apache.http.util.Asserts.check(Asserts.java:34) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.entity.BasicHttpEntity.getContent(BasicHttpEntity.java:75) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.entity.BasicHttpEntity.writeTo(BasicHttpEntity.java:112) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.7.jar:4.5.7]
	at com.aliyuncs.http.clients.ApacheHttpClient.syncInvoke(ApacheHttpClient.java:246) ~[aliyun-java-sdk-core-4.0.1.jar:?]
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:272) ~[aliyun-java-sdk-core-4.0.1.jar:?]
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:209) ~[aliyun-java-sdk-core-4.0.1.jar:?]
	at com.aliyuncs.DefaultAcsClient.doAction(DefaultAcsClient.java:93) ~[aliyun-java-sdk-core-4.0.1.jar:?]
	at com.aliyuncs.DefaultAcsClient.getAcsResponse(DefaultAcsClient.java:137) ~[aliyun-java-sdk-core-4.0.1.jar:?]

请问是依赖的问题吗？

**Comment by helongno1** [comment]
自己的问题
