### ISSUE TITLE
The remote configuration is not in effect

### ISSUE THREAD

**Issue by lujiafa** [alibaba/spring-cloud-alibaba#795]
Describe the bug
The remote configuration is not in effect.
`spring.main.allow-bean-definition-overriding=true`

Exception:
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'cms.FeignClientSpecification' defined in null: Cannot register bean definition [Generic bean: class [org.springframework.cloud.openfeign.FeignClientSpecification]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'cms.FeignClientSpecification': There is already [Generic bean: class [org.springframework.cloud.openfeign.FeignClientSpecification]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:891) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerClientConfiguration(FeignClientsRegistrar.java:389) ~[spring-cloud-openfeign-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerFeignClients(FeignClientsRegistrar.java:216) ~[spring-cloud-openfeign-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerBeanDefinitions(FeignClientsRegistrar.java:144) ~[spring-cloud-openfeign-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:364) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$$Lambda$158/5142724.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) ~[?:1.8.0_45]

![Uploading image.png…]()
![问题](https://user-images.githubusercontent.com/19968671/62208540-cf589c00-b3c9-11e9-8938-327c832a9ca1.png)

**Comment by fangjian0423** [comment]
It seems the configuration item `spring.main.allow-bean-definition-overriding` loaded by `PropertySourceLocator` is not effect.

**Comment by echooymxq** [comment]
It not a bug, the remote properties will not override the local `spring.main**` properties because the 
`prepareEnvironment` method to bind `allowBeanDefinitionOverriding`  always execute before `prepareContext` method on pull remote configuration. You can set it directly in bootstrap.properties

**Comment by fangjian0423** [comment]
👍
