### ISSUE TITLE
dubbo consumer start regist fail

### ISSUE THREAD

**Issue by khiker007** [alibaba/spring-cloud-alibaba#834]
nacos is ready and provider is regist success,but the consumer start will print ERROR log on the console, the message like under;

 my config error?

2019-08-12 18:19:54.998  WARN 24000 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:19:55.008  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     :  [DUBBO] Register: consumer://10.0.75.1/com.fshares.chain.service.core.ICoinLimitAmountService?application=task-market&category=consumers&check=false&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICoinLimitAmountService&lazy=false&methods=deleteMappingCoinLimitAmount,refreshFscUnitLimitAmount,setFscUnitLimitAmount,getFscUnitLimitAmount,listMappingCoinLimitAmount,addMappingCoinLimitAmount,refreshAllMappingCoinLimitAmount,updateMappingCoinLimitAmount&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605194998, dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:19:55.008 DEBUG 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The URL[consumer://10.0.75.1/com.fshares.chain.service.core.ICoinLimitAmountService?application=task-market&category=consumers&check=false&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICoinLimitAmountService&lazy=false&methods=deleteMappingCoinLimitAmount,refreshFscUnitLimitAmount,setFscUnitLimitAmount,getFscUnitLimitAmount,listMappingCoinLimitAmount,addMappingCoinLimitAmount,refreshAllMappingCoinLimitAmount,updateMappingCoinLimitAmount&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605194998] should not be registered.
2019-08-12 18:19:55.008  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     :  [DUBBO] Subscribe: consumer://10.0.75.1/com.fshares.chain.service.core.ICoinLimitAmountService?application=task-market&category=providers,configurators,routers&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICoinLimitAmountService&lazy=false&methods=deleteMappingCoinLimitAmount,refreshFscUnitLimitAmount,setFscUnitLimitAmount,getFscUnitLimitAmount,listMappingCoinLimitAmount,addMappingCoinLimitAmount,refreshAllMappingCoinLimitAmount,updateMappingCoinLimitAmount&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605194998, dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:19:55.008  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The Dubbo Service URL[ID : consumer://10.0.75.1/com.fshares.chain.service.core.ICoinLimitAmountService] is being subscribed for service[name : service-market]
2019-08-12 18:19:55.010 DEBUG 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The subscribed URL[consumer://10.0.75.1/com.fshares.chain.service.core.ICoinLimitAmountService?application=task-market&category=providers,configurators,routers&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICoinLimitAmountService&lazy=false&methods=deleteMappingCoinLimitAmount,refreshFscUnitLimitAmount,setFscUnitLimitAmount,getFscUnitLimitAmount,listMappingCoinLimitAmount,addMappingCoinLimitAmount,refreshAllMappingCoinLimitAmount,updateMappingCoinLimitAmount&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605194998] will notify all URLs : []
2019-08-12 18:19:55.010  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The Dubbo Service URL[ID : consumer://10.0.75.1/com.fshares.chain.service.core.ICoinLimitAmountService] is being subscribed for service[name : service-core]
2019-08-12 18:19:55.013 DEBUG 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The subscribed URL[consumer://10.0.75.1/com.fshares.chain.service.core.ICoinLimitAmountService?application=task-market&category=providers,configurators,routers&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICoinLimitAmountService&lazy=false&methods=deleteMappingCoinLimitAmount,refreshFscUnitLimitAmount,setFscUnitLimitAmount,getFscUnitLimitAmount,listMappingCoinLimitAmount,addMappingCoinLimitAmount,refreshAllMappingCoinLimitAmount,updateMappingCoinLimitAmount&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605194998] will notify all URLs : [dubbo://192.168.211.89:8087?anyhost=true&application=service-core&bean.name=ServiceBean:com.fshares.chain.service.core.ICoinLimitAmountService&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.fshares.chain.service.core.ICoinLimitAmountService&methods=deleteMappingCoinLimitAmount,setFscUnitLimitAmount,getFscUnitLimitAmount,refreshFscUnitLimitAmount,listMappingCoinLimitAmount,addMappingCoinLimitAmount,refreshAllMappingCoinLimitAmount,updateMappingCoinLimitAmount&pid=9356&register=true&release=2.7.3&serialization=kryo&side=provider&status=server&timestamp=1565604127509]
2019-08-12 18:19:55.046  WARN 24000 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:19:55.057  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     :  [DUBBO] Register: consumer://10.0.75.1/com.fshares.chain.service.core.ICurrencyPairService?application=task-market&category=consumers&check=false&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICurrencyPairService&lazy=false&methods=getOneByBase,getByIds,getByChainSymbolId,getAll,addPair,getById,listByQuote,updateStatus,updatePair,listByBase,isExist&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605195046, dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:19:55.057 DEBUG 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The URL[consumer://10.0.75.1/com.fshares.chain.service.core.ICurrencyPairService?application=task-market&category=consumers&check=false&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICurrencyPairService&lazy=false&methods=getOneByBase,getByIds,getByChainSymbolId,getAll,addPair,getById,listByQuote,updateStatus,updatePair,listByBase,isExist&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605195046] should not be registered.
2019-08-12 18:19:55.058  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     :  [DUBBO] Subscribe: consumer://10.0.75.1/com.fshares.chain.service.core.ICurrencyPairService?application=task-market&category=providers,configurators,routers&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICurrencyPairService&lazy=false&methods=getOneByBase,getByIds,getByChainSymbolId,getAll,addPair,getById,listByQuote,updateStatus,updatePair,listByBase,isExist&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605195046, dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:19:55.058  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The Dubbo Service URL[ID : consumer://10.0.75.1/com.fshares.chain.service.core.ICurrencyPairService] is being subscribed for service[name : service-market]
2019-08-12 18:19:55.059 DEBUG 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The subscribed URL[consumer://10.0.75.1/com.fshares.chain.service.core.ICurrencyPairService?application=task-market&category=providers,configurators,routers&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICurrencyPairService&lazy=false&methods=getOneByBase,getByIds,getByChainSymbolId,getAll,addPair,getById,listByQuote,updateStatus,updatePair,listByBase,isExist&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605195046] will notify all URLs : []
2019-08-12 18:19:55.060  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The Dubbo Service URL[ID : consumer://10.0.75.1/com.fshares.chain.service.core.ICurrencyPairService] is being subscribed for service[name : service-core]
2019-08-12 18:19:55.062 DEBUG 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     : The subscribed URL[consumer://10.0.75.1/com.fshares.chain.service.core.ICurrencyPairService?application=task-market&category=providers,configurators,routers&dubbo=2.0.2&interface=com.fshares.chain.service.core.ICurrencyPairService&lazy=false&methods=getOneByBase,getByIds,getByChainSymbolId,getAll,addPair,getById,listByQuote,updateStatus,updatePair,listByBase,isExist&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605195046] will notify all URLs : [dubbo://192.168.211.89:8087?anyhost=true&application=service-core&bean.name=ServiceBean:com.fshares.chain.service.core.ICurrencyPairService&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.fshares.chain.service.core.ICurrencyPairService&methods=getOneByBase,getByIds,getByChainSymbolId,getAll,addPair,getById,listByQuote,updateStatus,listByBase,updatePair,isExist&pid=9356&register=true&release=2.7.3&serialization=kryo&side=provider&status=server&timestamp=1565604133842]
2019-08-12 18:19:55.436  WARN 24000 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2019-08-12 18:19:55.436  INFO 24000 --- [           main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-08-12 18:19:55.442  WARN 24000 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2019-08-12 18:19:55.442  INFO 24000 --- [           main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-08-12 18:19:55.760  INFO 24000 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService
2019-08-12 18:19:55.831  INFO 24000 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2019-08-12 18:19:57.506 DEBUG 24000 --- [           main] a.c.d.m.r.DubboServiceMetadataRepository : The metadata of Dubbo service[name : service-market] has been initialized
2019-08-12 18:19:57.506 DEBUG 24000 --- [           main] a.c.d.m.r.DubboServiceMetadataRepository : The metadata of Dubbo service[name : service-core] has been initialized
2019-08-12 18:19:57.506  INFO 24000 --- [           main] a.c.d.m.r.DubboServiceMetadataRepository : The metadata of Dubbo services has been initialized
2019-08-12 18:19:57.526  INFO 24000 --- [           main] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'application-1.matchedInput' has 1 subscriber(s).
2019-08-12 18:19:57.633  INFO 24000 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel matchedInput
2019-08-12 18:19:57.706  INFO 24000 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel errorChannel
2019-08-12 18:19:57.735  INFO 24000 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel nullChannel
2019-08-12 18:19:57.744  INFO 24000 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageHandler errorLogger
2019-08-12 18:19:57.768  INFO 24000 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageHandler org.springframework.cloud.stream.binding.StreamListenerMessageHandler@77988c45
2019-08-12 18:19:57.875  INFO 24000 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2019-08-12 18:19:57.875  INFO 24000 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'application-1.errorChannel' has 1 subscriber(s).
2019-08-12 18:19:57.875  INFO 24000 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2019-08-12 18:19:57.881  INFO 24000 --- [client.listener] uration$$EnhancerBySpringCGLIB$$c59732ec : The event of the service instances[name : service-market , size : 1] change is about to be dispatched
2019-08-12 18:19:57.882  INFO 24000 --- [client.listener] c.a.c.d.registry.SpringCloudRegistry     : The Dubbo Service URL[ID : consumer://10.0.75.1/com.fshares.chain.service.market.IKlineService] is being subscribed for service[name : service-market]
2019-08-12 18:19:57.884 DEBUG 24000 --- [client.listener] c.a.c.d.registry.SpringCloudRegistry     : The subscribed URL[consumer://10.0.75.1/com.fshares.chain.service.market.IKlineService?application=task-market&category=providers,configurators,routers&dubbo=2.0.2&interface=com.fshares.chain.service.market.IKlineService&lazy=false&methods=getLasted,getList,save&pid=24000&qos.enable=false&release=2.7.3&side=consumer&sticky=false&timestamp=1565605191406] will notify all URLs : [dubbo://192.168.211.89:8088?anyhost=true&application=service-market&bean.name=ServiceBean:com.fshares.chain.service.market.IKlineService&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.fshares.chain.service.market.IKlineService&methods=getLasted,getList,save&pid=15292&register=true&release=2.7.3&serialization=kryo&side=provider&status=server&timestamp=1565604117894]
2019-08-12 18:19:57.884  INFO 24000 --- [client.listener] c.a.c.d.registry.SpringCloudRegistry     : The Dubbo Service URL[ID : consumer://10.0.75.1/com.fshares.chain.service.market.IExchangeRateService] is being subscribed for service[name : service-market]
2019-08-12 18:21:03.784  WARN 24000 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:21:03.868  WARN 24000 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] Use random available port(20880) for protocol dubbo, dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:21:04.167  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     :  [DUBBO] Register: dubbo://10.0.75.1:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=task-market&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=task-market&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=24000&register=true&release=2.7.3&revision=2.1.0.RELEASE&side=provider&timestamp=1565605263793&version=1.0.0, dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:21:05.187  INFO 24000 --- [           main] c.a.c.d.registry.SpringCloudRegistry     :  [DUBBO] Subscribe: provider://10.0.75.1:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=task-market&bind.ip=10.0.75.1&bind.port=20880&category=configurators&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=task-market&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=24000&qos.enable=false&register=true&release=2.7.3&revision=2.1.0.RELEASE&side=provider&timestamp=1565605263793&version=1.0.0, dubbo version: 2.7.3, current host: 10.0.75.1
2019-08-12 18:21:05.195  INFO 24000 --- [           main] c.a.c.d.s.DubboMetadataServiceExporter   : The Dubbo service[<dubbo:service path="com.alibaba.cloud.dubbo.service.DubboMetadataService" ref="com.alibaba.cloud.dubbo.service.IntrospectiveDubboMetadataService@731ab49b" prefix="dubbo.service.com.alibaba.cloud.dubbo.service.DubboMetadataService" generic="false" exported="true" interface="com.alibaba.cloud.dubbo.service.DubboMetadataService" unexported="false" version="1.0.0" dynamic="true" group="task-market" deprecated="false" register="true" registryIds="" id="com.alibaba.cloud.dubbo.service.DubboMetadataService" valid="true" />] has been exported.
2019-08-12 18:21:05.340 ERROR 24000 --- [           main] com.alibaba.nacos.client.naming          : request 127.0.0.1:8848 failed.

com.alibaba.nacos.api.exception.NacosException: failed to req API:127.0.0.1:8848/nacos/v1/ns/instance. code:400 msg: instance format invalid:192.168.211.89:unknown:DEFAULT_1.0_true_false_DEFAULT
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:424)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:188)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:205)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:184)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:61)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry$$FastClassBySpringCGLIB$$ca3a8dbd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry$$EnhancerBySpringCGLIB$$5688af4a.register(<generated>)
	at com.alibaba.cloud.dubbo.autoconfigure.DubboServiceRegistrationNonWebApplicationAutoConfiguration.register(DubboServiceRegistrationNonWebApplicationAutoConfiguration.java:92)
	at com.alibaba.cloud.dubbo.autoconfigure.DubboServiceRegistrationNonWebApplicationAutoConfiguration.onApplicationStarted(DubboServiceRegistrationNonWebApplicationAutoConfiguration.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:408)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:97)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:71)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:291)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:192)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:130)
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:337)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:92)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:254)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:48)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at com.fshares.chain.MarketTaskApplication.main(MarketTaskApplication.java:17)

2019-08-12 18:21:05.343 ERROR 24000 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, task-market register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='127.0.0.1:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='task-market', weight=1.0, clusterName='DEFAULT', namingLoadCacheAtStart='false', metadata={dubbo.metadata-service.urls=[ "dubbo://10.0.75.1:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=task-market&bind.ip=10.0.75.1&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=task-market&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=24000&qos.enable=false&register=true&release=2.7.3&revision=2.1.0.RELEASE&side=provider&timestamp=1565605263793&version=1.0.0" ], dubbo.protocols.dubbo.port=20880, preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.211.89', networkInterface='', port=-1, secure=false, accessKey='', secretKey=''}},

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: failed to req API:127.0.0.1:8848/nacos/v1/ns/instance. code:400 msg: instance format invalid:192.168.211.89:unknown:DEFAULT_1.0_true_false_DEFAULT
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:464)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:188)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:205)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:184)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:61)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry$$FastClassBySpringCGLIB$$ca3a8dbd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry$$EnhancerBySpringCGLIB$$5688af4a.register(<generated>)
	at com.alibaba.cloud.dubbo.autoconfigure.DubboServiceRegistrationNonWebApplicationAutoConfiguration.register(DubboServiceRegistrationNonWebApplicationAutoConfiguration.java:92)
	at com.alibaba.cloud.dubbo.autoconfigure.DubboServiceRegistrationNonWebApplicationAutoConfiguration.onApplicationStarted(DubboServiceRegistrationNonWebApplicationAutoConfiguration.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:408)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:97)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:71)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:291)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:192)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:130)
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:337)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:92)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:254)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:48)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at com.fshares.chain.MarketTaskApplication.main(MarketTaskApplication.java:17)

**Comment by khiker007** [comment]
@fangjian0423 现在的情况是，启动的时候会报几次链接超时的错误，但是启动完成时可以正常访问服务

**Comment by fangjian0423** [comment]
could you provide a project that reproduces the issue?

**Comment by khiker007** [comment]
i found that the project not contains spring-boot-start-web depenency will produce this problem

web project is no problem,but task or websocket will found this issue

**Comment by khiker007** [comment]
> could you provide a project that reproduces the issue?
i found that the project not contains spring-boot-start-web depenency will produce this problem

web project is no problem,but task or websocket will found this issue

**Comment by khiker007** [comment]
> could you provide a project that reproduces the issue?


i found that the project not contains spring-boot-start-web depenency will produce this problem

web project is no problem,but task or websocket will found this issue

**Comment by zhouxufu** [comment]
dubbo:
  scan:
    base-packages: 这里配置错误会出现你说的这个问题
