### ISSUE TITLE
From Hystrix to Sentinel, NoSuchMethodError: feign.RequestTemplate.path()Ljava/lang/String;

### ISSUE THREAD

**Issue by Ruoxer** [alibaba/spring-cloud-alibaba#918]
config:
```
feign:
    hystrix:
        enabled: false
    sentinel:
        enabled: true
```

A call B:
```
   exception:  Caused by: java.lang.NoSuchMethodError: feign.RequestTemplate.path()Ljava/lang/String;
	at org.springframework.cloud.alibaba.sentinel.feign.SentinelInvocationHandler.invoke(SentinelInvocationHandler.java:98)
	at com.sun.proxy.$Proxy136.show(Unknown Source)
```

 How should I solve it?

**Comment by fangjian0423** [comment]
Maybe you are using wrong version, refer https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E.

**Comment by Ruoxer** [comment]
tks, have already been solved
