### ISSUE TITLE
invalid IPv6 address

### ISSUE THREAD

**Issue by hyw520110** [alibaba/spring-cloud-alibaba#928]
版本：

               <dubbo.version>2.7.1</dubbo.version>
		<curator.version>4.0.1</curator.version>
		<spring-boot.version>2.1.3.RELEASE</spring-boot.version>
		<spring-cloud-build.version>2.1.3.RELEASE</spring-cloud-build.version>
		<spring-cloud-alibaba.version>2.1.1.BUILD-SNAPSHOT</spring-cloud-alibaba.version>	
		<spring-cloud-commons.version>2.1.2.RELEASE</spring-cloud-commons.version>
		<spring-cloud-zookeeper.version>2.1.2.RELEASE</spring-cloud-zookeeper.version>

consumer和provider的bootstrap.yml配置:

```
spring:
  application:
    name: XXX
  profiles: 
    active: dev
  cloud:
    zookeeper:
      enabled: true
      connect-string: '192.168.1.202:2181'
      config:
        enabled: true
        watcher:
          enabled: false
      discovery: 
        enabled: true
        instanceHost: '192.168.1.202:2181'
dubbo: 
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registries:
    cloud: 
      address: spring-cloud://localhost
```

consumer应用启动报错 ：

`java.net.UnknownHostException: 192.168.1.202:2181: invalid IPv6 address`

详细异常：

```
2019-09-10 19:56:11 [ERROR] org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:51) [dubbo-client-idleCheck-thread-1 169603] [-/  ]:  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [192.168.1.139:0 -> 192.168.1.202:2181:20880]], dubbo version: 2.7.3, current host: 192.168.1.139

org.apache.dubbo.remoting.RemotingException: client(url: dubbo://192.168.1.202:2181:20880/com..XXX..Service?anyhost=true&application=carwash&bean.name=ServiceBean:com..XXX..Service&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&interface=com..XXX..Service&lazy=false&logger=slf4j&.....&side=consumer&sticky=false&timeout=10000&timestamp=1568116150581) failed to connect to server 192.168.1.202:2181:20880, error message is:192.168.1.202:2181: invalid IPv6 address

at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:166) ~[dubbo-2.7.3.jar:2.7.3]

at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:190) ~[dubbo-2.7.3.jar:2.7.3]

at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:246) ~[dubbo-2.7.3.jar:2.7.3]

at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:155) ~[dubbo-2.7.3.jar:2.7.3]

at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49) ~[dubbo-2.7.3.jar:2.7.3]

at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87) ~[dubbo-2.7.3.jar:2.7.3]

at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648) ~[dubbo-2.7.3.jar:2.7.3]

at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727) ~[dubbo-2.7.3.jar:2.7.3]

at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449) ~[dubbo-2.7.3.jar:2.7.3]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Caused by: java.net.UnknownHostException: 192.168.1.202:2181: invalid IPv6 address

at java.net.InetAddress.getAllByName(InetAddress.java:1169) ~[?:1.8.0_161]

at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_161]

at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_161]

at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]

at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:982) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:427) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
````

**Comment by echooymxq** [comment]
The `instanceHost` is not corrent,It is usually a service name or an ip address.

**Comment by fangjian0423** [comment]
yes, you could set port with `instancePort`.

Refer https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-discovery/src/main/java/org/springframework/cloud/zookeeper/discovery/ZookeeperDiscoveryProperties.java#L75.
